### ISSUE TITLE
"setWifiState" and "setBluetoothState" will trigger the error callback

### ISSUE THREAD

**Issue by bau720123** [dpa99c/cordova-diagnostic-plugin#10]
hi @dpa99c 
I am using PGB cli-5.2.0 with your latest plugin 2.2.3 from npm + Android 4.4.2
https://www.npmjs.com/package/cordova.plugins.diagnostic

when I am using "setWifiState" and "setBluetoothState"
it all trigger the error callback
and output these message
```
Value null at 0 of type org.json.JSONObject$1 cannot be converted to boolean
```
could I ask what the words true meaning?

**Comment by dpa99c** [comment]
These methods are working fine for me when I run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) in Android 4.4. emulator. Are you able to try running the example project app?

**Comment by bau720123** [comment]
hi @dpa99c 
could I ask first
in your page it said
https://github.com/dpa99c/cordova-diagnostic-plugin

setWifiState()
Requires the following permissions:
```
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
```

setBluetoothState()
Requires the following permissions:
```
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
```

is these above permissions will add to AndroidMainfest.xml automatically ?
because I am using PGB not cordova cli

**Comment by dpa99c** [comment]
You need to set the required permissions in your config.xml - the plugin will not do this for you, because it depends what functionality your app uses from the plugin as to what permissions you need to add. See the [config.xml in the example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/config.xml) for examples how to do this.

**Comment by bau720123** [comment]
thanks @dpa99c 
solved

**Comment by bhargavas12** [comment]
Added below lines in config:

 <config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
            <uses-permission android:name="android.permission.BLUETOOTH" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
            <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
        </config-file>

Still i'm unable to setBluetoothState.
getting this error: "unable to change bluetooth state since permission is denied"

How to make it work?
