### ISSUE TITLE
isCameraAvailable reporting false even when available

### ISSUE THREAD

**Issue by cfjedimaster** [dpa99c/cordova-diagnostic-plugin#104]
I created a brand new Cordova project, added this plugin, added the Camera plugin, and then used the documented code for isCameraAvailable and it always returns false.

**Comment by dpa99c** [comment]
Just to clarify, on iOS and Android, [isCameraAvailable()](https://github.com/dpa99c/cordova-diagnostic-plugin#iscameraavailable) will return true only if the device has a camera **and** is authorised to use it. So on iOS and Android 6, it will return false until run-time access to the camera has been authorised, by the app requesting run-time permission and the user approving it. Whereas [isCameraPresent()](https://github.com/dpa99c/cordova-diagnostic-plugin#iscamerapresent) will return true if the device has a camera, regardless of the authorisation state. The [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) app illustrates both of these cases.

However, if this is not the issue and isCameraAvailable() appears to be incorrectly returning false when a camera is present and has been authorised for use, if you can provide the following details of the environment is which you're encountering the issue, I'll see if I can reproduce/fix it:

- What Cordova platform and version? e.g. cordova-ios@4.1.1
- What version of this plugin? e.g. cordova.plugins.diagnostic@3.1.1

**Comment by cfjedimaster** [comment]
Oh fascinating. I thought simply having the Camera plugin would flag to iOS "I'm using a Camera", but you're absolutely right - you don't see the prompt until you try to use the camera. So this is a non issue for sure, and thank you so much for helping me out with this.

**Comment by dpa99c** [comment]
No worries, happy camera-ing :-)
