### ISSUE TITLE
Dependencies Error

### ISSUE THREAD

**Issue by bknill** [dpa99c/cordova-diagnostic-plugin#105]
I'm getting this error when I try and build with this plugin in an Ionic App. 

> Error: cmd: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Could not resolve all dependencies for configuration ':_debugCompile'.
>    > Could not find any version that matches com.android.support:support-v4:23.+
> .
>      Versions that do not match:
>          24.1.1
>          24.1.0
>          24.0.0
>          22.2.0
>          22.1.0
>          + 10 more
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met
> adata.xml
>          https://repo1.maven.org/maven2/com/android/support/support-v4/
>          https://jcenter.bintray.com/com/android/support/support-v4/maven-metada
> ta.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/android/m2repositor
> y/com/android/support/support-v4/maven-metadata.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/google/m2repository
> /com/android/support/support-v4/maven-metadata.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/google/m2repository
> /com/android/support/support-v4/
>      Required by:
>          :android:unspecified
>    > Could not find any version that matches com.android.support:appcompat-v7:23
> .+.
>      Versions that do not match:
>          24.1.1
>          24.1.0
>          24.0.0
>          22.2.0
>          22.1.0
>          + 9 more
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/appcompat-v7/maven-m
> etadata.xml
>          https://repo1.maven.org/maven2/com/android/support/appcompat-v7/
>          https://jcenter.bintray.com/com/android/support/appcompat-v7/maven-meta
> data.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/android/m2repositor
> y/com/android/support/appcompat-v7/maven-metadata.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/google/m2repository
> /com/android/support/appcompat-v7/maven-metadata.xml
>          file:/C:/Users/Ben/AppData/Local/Android/sdk/extras/google/m2repository
> /com/android/support/appcompat-v7/
>      Required by:
>          :android:unspecified
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output.

I've been having a good look round for solutions,  which mostly seem to be updating libraries in the Android SDK. 

I've added all the libraries and repositories suggested - to no avail. 

Has anyone else seen this/can help me work out what's missing?

**Comment by dpa99c** [comment]
Looks like this error has started occurring because this [plugin specifies v23 of the Application Support Library ](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L56), but it looks like now Android N/7.0 has been released, v23 has been dropped in place of v24:

    24.1.1
    24.1.0
    24.0.0
    22.2.0
    22.1.0

As a quick fix, you can edit `platforms/android/build.gradle` and change:

    compile "com.android.support:support-v4:23.+"
    compile "com.android.support:appcompat-v7:23.+"
    
to

    compile "com.android.support:support-v4:+"
    compile "com.android.support:appcompat-v7:+"

I'll also update the plugin config to resolve this and publish a new version.

**Comment by dpa99c** [comment]
I've pushed out the fix in `cordova.plugins.diagnostic@3.1.2` - remove/re-add the plugin to get this version and it should resolve the issue.

**Comment by denzelwamburu** [comment]
Updating `Google Play Service` And `Google Repository` Solved the issue for me
