### ISSUE TITLE
getMicrophoneAuthorizationStatus return value does not match Diagnostic.permissionStatus

### ISSUE THREAD

**Issue by gdehaan** [dpa99c/cordova-diagnostic-plugin#115]
Hi,

getMicrophoneAuthorizationStatus() returns "granted" but the Diagnostic.permissionStatus.GRANTED constant is "authorized" 

Cheers,
Gijsbert

**Comment by dpa99c** [comment]
Thanks for reporting this.
Fixed by commit 84a55e23a459f5e8ffc8a66b99d246aae8069917.
Published in [v3.1.5](https://github.com/dpa99c/cordova-diagnostic-plugin/tree/3.1.5)

**Comment by gdehaan** [comment]
Cheers!
