### ISSUE TITLE
iOs 10 and new permissions requirements

### ISSUE THREAD

**Issue by VinceOPS** [dpa99c/cordova-diagnostic-plugin#116]
Hi, 

It seems that iOs 10 restrictions on Permissions now require this plugin to add to the plist:
`NSContactsUsageDescription`, `NSBluetoothPeripheralUsageDescription`, and `NSMicrophoneUsageDescription`

Otherwise, your app will be rejected from the store.

These 3 permissions (that are not used in my app) are, btw, a little bit "critical". I assume I'll fork the plugin in order to create a version which do not use the contacts, bluetooth and microphone features. Or maybe we can discuss of a way (using cordova hooks, or shell scripts) to disable/remove some parts of the plugin "on-the-fly" before compiling? It would be great!

Thanks

Regards

**Comment by dpa99c** [comment]
These new iOS 10 restrictions are a bit of a problem. For now I'm going to add standard key for these usage descriptions to the plugin. But I may consider splitting this plugin down into multiple functionally-separate plugins, e.g. `cordova.plugins.diagnostic.microphone`, `cordova.plugins.diagnostic.bluetooth`, etc.

**Comment by VinceOPS** [comment]
Hi @dpa99c ! Thank you for this quick answer.
I'm kind of a newbie in iOs development, but I see in my Xcode project settings that the `Contacts.Framework`, `CoreBluetooth.Framework`, [...] have `Required` as a status. Is it normal? May it be the reason why adding these `NS[...]Description` is mandatory?

Thanks for this plugin ;)!

**Comment by dpa99c** [comment]
Yes, the plugin will include these frameworks in your XCode project, hence iOS 10 now requires usage descriptions if the frameworks are included. 

However, if your app doesn't use them, it's not a problem and of no consequence to the user. Unless you invoke a plugin method, such as `requestCalendarAuthorization()`, in which case the user will be shown the [default usage description](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L36) that the plugin now adds to the plist. 

If your app does make use of that particular functionality, you can override these default usage descriptions using [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config).

**Comment by tverilytt** [comment]
@dpa99c Great plugin, and I like the thought of splitting it, or being able to choose which components to use for particular apps. In my case now, I am only using the location-related functionality in this plugin. I tried to comment out the Contact-related stuff in plugin.xml, but still I got rejection from App Store (iTunes Connect). I guess they actually scan the code...(?).

Cheers
-jo2
