### ISSUE TITLE
"Compulsory 64-bit support"

### ISSUE THREAD

**Issue by andersborgabiro** [dpa99c/cordova-diagnostic-plugin#128]
I get "Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture." when invoking this plugin and building for iOS. I've checked that it's specifically this one by not including any other. This is via PhoneGap Build.

This is how I invoke it:  `<plugin name="cordova.plugins.diagnostic" />`

I use cli-6.3.0 and these are the iOS-specific settings:

    <preference name="deployment-target" value="8.0" />
    <preference name="target-device" value="universal" />
    <preference name="prerendered-icon" value="false" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="AllowInlineMediaPlayback" value="true" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarStyle" value="default" />
    <preference name="disable-push-notifications" value="1" />

Thanks in advance for any advice,
Anders

**Comment by leetpcuser** [comment]
I get the same issue. It is preventing me from building my application. I also cannot find a release history to include a previous version for my build.

**Comment by leetpcuser** [comment]
I get the same issue. It is preventing me from building my application. I also cannot find a release history to include a previous version for my build.
![capture](https://cloud.githubusercontent.com/assets/1589172/18934834/0e499dac-8591-11e6-872c-a288f9bb60f6.PNG)

**Comment by andersborgabiro** [comment]
Maybe it only happens with PGB. This plugin should be pretty new, so odd that there's an issue.

**Comment by leetpcuser** [comment]
It is possible. However, I did a build around 10 days ago, and I had no issue. I haven't changed my version to build with, and confirmed it was this plugin.

**Comment by andersborgabiro** [comment]
I checked whether it had to do with cli-6.3.0 vs cli-6.1.0, and it didn't. Both give this error. Hopefully someone in the know answers soon.

**Comment by leetpcuser** [comment]
I changed my line in my config.xml to this:

`<plugin name="cordova.plugins.diagnostic" source="npm" spec="3.1.7" />`

It seems the break occurs in release 3.2.0 introduced 7 days ago. Hopefully this helps you, and helps someone track it down.

**Comment by andersborgabiro** [comment]
Thanks. That works.

**Comment by dpa99c** [comment]
As [stated in the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#version-32-for-ios-10):

`cordova.plugins.diagnostic@3.2` adds support for the new UserNotifications framework added in iOS 10. This requires an Xcode 8 build environment. As always, cloud-based build environments lag behind major mobile platform version releases considerably, so Phonegap Build (amongst others) is still using an Xcode 7 build environment. Until such time as Phonegap Build is updated to use Xcode 8, you must use `cordova.plugins.diagnostic@3.1` in your PGB-based projects, or build locally with Xcode 8.

**Comment by andersborgabiro** [comment]
Alrighty. Thanks. And yes, I did not read the documentation.
