### ISSUE TITLE
Android isLocationEnabled always returns '1'

### ISSUE THREAD

**Issue by Yuripetusko** [dpa99c/cordova-diagnostic-plugin#13]
Hello. I have cordova/ionic app. If after installing the app, I go to it's settings and disable location services, I always get successCallback: '1' when doing cordova.plugins.diagnostic.isLocationEnabled. Is it expected? Can I somehow check if location services permission is turned off for current app?

**Comment by Yuripetusko** [comment]
OK I can see that on Android `isLocationEnabled ` always returns global phone's location settings, but not App's specific location permission. Is it possible to get App's location permission value?

**Comment by dpa99c** [comment]
Do you mean the new Android 6 run-time permission (#11)? If so, not yet. The plugin doesn't yet support it, but I intend to add the functionality when I get some time.

**Comment by Yuripetusko** [comment]
Ah, sorry, didn't realise it is specific to Android 6. Thanks, will keep an eye on updates!
