### ISSUE TITLE
Wrong Example Method

### ISSUE THREAD

**Issue by justgeek** [dpa99c/cordova-diagnostic-plugin#130]
In Read.md file the example is as follows:

```
cordova.plugins.diagnostic.isLocationAvailable(function(available){
    console.log("Location is " + (available ? "available" : "not available"));
}, function(error){
    console.error("The following error occurred: "+error);
});
```
Results in error : 

**TypeError: Object #<Object> has no method 'isLocationAvailable'**

But the correct method is:

```
cordova.plugins.diagnostic.isLocationEnabled(function(available){
    console.log("Location is " + (available ? "available" : "not available"));
}, function(error){
    console.error("The following error occurred: "+error);
});
```

**Comment by dpa99c** [comment]
The documentation is correct for [isLocationAvailable()](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationavailable) - this is indeed the method name. It is present in the [Android](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L436), [iOS](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L97) and [Windows](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/windows/diagnostic.js#L16) implementations.

Please make sure you are not using an old version of the plugin - the current version is v3.2.1

You can see this method in use in the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L293)
