### ISSUE TITLE
"registerBluetoothStateChangeHandler" and "registerLocationStateChangeHandler" not work in Android and iOS

### ISSUE THREAD

**Issue by bau720123** [dpa99c/cordova-diagnostic-plugin#132]
hi @dpa99c 
I am using Android 6.0.1、iOS 9.3.5、Cordova Android 5.2.2、Cordova iOS 4.2.1、cordova-diagnostic-plugin 3.2.2
according to these
https://github.com/dpa99c/cordova-diagnostic-plugin#registerbluetoothstatechangehandler
https://github.com/dpa99c/cordova-diagnostic-plugin#registerlocationstatechangehandler
I tried in Android and iOS，but the "console.log" not trigger

```
cordova.plugins.diagnostic.registerBluetoothStateChangeHandler(function(state)
{
//not trigger
});

cordova.plugins.diagnostic.registerLocationStateChangeHandler(function(state)
{
//not trigger
});
```

**Comment by dpa99c** [comment]
Have you tried building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which illustrates use of both [registerBluetoothStateChangeHandler](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L16) and [registerLocationStateChangeHandler](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L23)?

When I run this example project on both Android and iOS, changes to both Bluetooth and Location states are correctly detected via these handlers.

Please confirm if you can reproduce the issue with the example project.

**Comment by bau720123** [comment]
thanks @dpa99c 
abit 132 and 133
let me check for a while
feedback later

**Comment by bau720123** [comment]
hi @dpa99c 
after build your project
https://github.com/dpa99c/cordova-diagnostic-plugin-example
I found something different from yours (others permissions are almost the same)

in your platforms\android\AndroidManifest.xml
you have already set these permission attribute
```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
```
but I have no these attribute in my platforms\android\AndroidManifest.xml (I check many times)

so...should I follow the tutorial
https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions
use the "cordova-custom-config" plugin and manually put these code in my config.xml
```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
```
because after build again，it will cause these permissions add into the AndroidManifest.xml automatically，right ?

**Comment by dpa99c** [comment]
You'll need to add the full config block to your config.xml and install cordova-custom-config plugin:

    <platform name="android">
        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.BLUETOOTH" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
            <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
            <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
        </config-file>
    </platform>

Then cordova-custom-config will automatically add these permissions to your AndroidManifest.xml when you build again.

**Comment by bau720123** [comment]
hi @dpa99c 
I encounter some problem
if I manually add these code in platforms\android\AndroidManifest.xml
```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
```
and use this build command，it will build success and output a apk file
```
cordova build android --release
```

but if I manually add these code in config.xml
```
<platform name="android">
    <config-file target="AndroidManifest.xml" parent="/*">
        ...no matter what permission that I add here
    </config-file>
</platform>
```
and still use this build command，it will build fail（I am sure the "cordova-custom-config" is install correctly），but the AndroidManifest.xml will add these permission automatically
```
cordova build android --release
```
![2016-10-12_220713](https://cloud.githubusercontent.com/assets/5110085/19313209/48e0e6cc-90c8-11e6-86c6-575f47da9de4.png)
![2016-10-12_220913](https://cloud.githubusercontent.com/assets/5110085/19313331/ad40ca56-90c8-11e6-907c-4d5a749c1811.png)
![2016-10-12_221110](https://cloud.githubusercontent.com/assets/5110085/19313380/cf7a5862-90c8-11e6-9faa-43985d227df7.png)

**Comment by dpa99c** [comment]
Is the problem that `cordova-custom-config` is not adding elements to `AndroidManifest.xml`? 
Or is it that it is adding elements, but then the Android build is failing because of invalid XML in the `AndroidManifest.xml`? (This is what the first screenshot suggests).

Try running `cordova prepare android` with your custom  `<config-file>`  block in place in your `config.xml` then post here:

- the exact `<config-file>` block you in your `config.xml`
- the resulting manifest file: `platforms/android/AndroidManifest.xml`

You may also want to have a look at the [example project for cordova-custom-config](https://github.com/dpa99c/cordova-custom-config-example). Note that I have recently updated [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config). The most recent version is 3.0.8

**Comment by bau720123** [comment]
hi @dpa99c 
I compare your's confil.xml and mine
I know what the problem is in Android (iOS not try yet)
in you config.xml，have this line
```
xmlns:android="http://schemas.android.com/apk/res/android"
```
if no this line，it will cause build fail 100% (I tried many times)

**Comment by dpa99c** [comment]
@bau720123 The namespace requirement is stated in the [cordova-custom-config documentation](https://github.com/dpa99c/cordova-custom-config#android-namespace-attribute).
Using the example projects for comparison is your best bet to resolve the issue quickly.

**Comment by bau720123** [comment]
hi @dpa99c 
I really use your project and reproduce the issue
in your index.js
```
function onDeviceReady() {
// Register change listeners for iOS+Android
    if(platform === "android" || platform === "ios") {
        cordova.plugins.diagnostic.registerBluetoothStateChangeHandler(function (state) {
            alert("Bluetooth state changed to: " + state); //I use the "alert" instead of the "console.log"，but not trigger
            checkState();
        }, function (error) {
            alert("Error registering for Bluetooth state changes: " + error); //I use the "alert" instead of the "console.log"，but not trigger
        });

        cordova.plugins.diagnostic.registerLocationStateChangeHandler(function (state) {
            alert("Location state changed to: " + state); //I use the "alert" instead of the "console.log"，but not trigger
            checkState();
        }, function (error) {
            alert("Error registering for location state changes: " + error); //I use the "alert" instead of the "console.log"，but not trigger
        });
    }
}
$(document).on("deviceready", onDeviceReady);
```

**Comment by dpa99c** [comment]
@bau720123 I cannot reproduce the behaviour you observed where the alert is not displayed. My device has Android 5.1.1. See [this video](http://ge.tt/8Q6t8Zf2) using the code you described above. [Here is the APK](http://ge.tt/2ZUu8Zf2) that it is running.

**Comment by bau720123** [comment]
hi @dpa99c 
thanks your apk and video
sorry for my previous wrong "operating step"，anyway...it is work On Android and iOS
