### ISSUE TITLE
"registerPermissionRequestCompleteHandler" not work in Android

### ISSUE THREAD

**Issue by bau720123** [dpa99c/cordova-diagnostic-plugin#133]
hi @dpa99c 
I am using Android 6.0.1、iOS 9.3.5、Cordova Android 5.2.2、Cordova iOS 4.2.1、cordova-diagnostic-plugin 3.2.2
according to these
https://github.com/dpa99c/cordova-diagnostic-plugin#registerpermissionrequestcompletehandler
I tried in Android ，but the "console.log" not trigger

```
cordova.plugins.diagnostic.registerPermissionRequestCompleteHandler(onPermissionRequestComplete);
});

function onPermissionRequestComplete()
{
//not trigger
}
```

**Comment by dpa99c** [comment]
Have you tried building and running the example project which illustrates use of [registerPermissionRequestCompleteHandler](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L32)?

Please confirm if you can reproduce the issue with the example project.

**Comment by bau720123** [comment]
hi @dpa99c 
I really use your project and reproduce the issue
in your index.js
```
function onDeviceReady() {
if(platform === "android"){
        cordova.plugins.diagnostic.registerPermissionRequestCompleteHandler(function(statuses){
            console.info("Permission request complete");
            for (var permission in statuses){
                switch(statuses[permission]){
                    case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                        alert("Permission granted to use "+permission); //I change the "alert" method，but not trigger
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                        alert("Permission to use "+permission+" has not been requested yet"); //I change the "alert" method，but not trigger
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.DENIED:
                        alert("Permission denied to use "+permission); //I change the "alert" method，but not trigger
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                        alert("Permission permanently denied to use "+permission); //I change the "alert" method，but not trigger
                        break;
                }
            }
        });
    }
}
$(document).on("deviceready", onDeviceReady);
```

**Comment by dpa99c** [comment]
@bau720123 I cannot reproduce the behaviour you observed where the alert is not displayed. I ran this on the Android 6.0 emulator. See [this video](http://ge.tt/97wg9Zf2) using the code you described above. [Here is the APK](http://ge.tt/4PPh9Zf2) that it is running.

**Comment by bau720123** [comment]
hi @dpa99c 
thanks your apk and video
but after I install your 133.apk and run it
I can't see "Request Camera Authorization" button
![01](https://cloud.githubusercontent.com/assets/5110085/19409792/b17ac53e-930e-11e6-87e5-f5249283609f.jpg)
![02](https://cloud.githubusercontent.com/assets/5110085/19409793/b17bd78a-930e-11e6-8166-8b57cc654ca7.jpg)
![03](https://cloud.githubusercontent.com/assets/5110085/19409802/f579550c-930e-11e6-9a4c-20fbf1fb5fdb.jpg)
is it because I am already granted ? so the registerPermissionRequestCompleteHandler is not work for me anymore ?

**Comment by dpa99c** [comment]
Runtime permissions were only added in Android 6.0 so you must test on Android 6.0 or above

**Comment by bau720123** [comment]
oh...thanks @dpa99c 
solved
