### ISSUE TITLE
Could isCalendarAuthorized return an error when permission not yet defined?

### ISSUE THREAD

**Issue by peterpeterparker** [dpa99c/cordova-diagnostic-plugin#134]
Hi,

First of all, thx for the plugin, really like it :)

I'm particularly using the function "isCalendarAuthorized" and I noticed that I will get a return value "false" in two cases

- When the app doesn't have the permission to access the calendar (permission on device == false)
- When the permission to access the calendar isn't yet set  (permission on device == null)

Would it be possible to extend the function to have not a boolean value as result but another type to be able to make a difference between these two cases? Or maybe send an error when the permission is not yet defined?

Thx in advance for your feedback

**Comment by dpa99c** [comment]
You'll be wanting [getCalendarAuthorizationStatus()](https://github.com/dpa99c/cordova-diagnostic-plugin#getcalendarauthorizationstatus) which returns the current status as a constant in `cordova.plugins.diagnostic.permissionStatus`, i.e.

    cordova.plugins.diagnostic.getCalendarAuthorizationStatus(function(status){
       switch(status){
              case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                  console.log("Permission not requested");
                  break;
              case cordova.plugins.diagnostic.permissionStatus.DENIED:
                  console.log("User denied access to permission");
                  break;
              case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                  console.log("User granted access to permission");
                  break;
              case cordova.plugins.diagnostic.permissionStatus.RESTRICTED:
                  console.log("Permission access restricted and unavailable");
                  break;
       }
    }, onError);

**Comment by peterpeterparker** [comment]
@dpa99c thx a lot for your answer, you are right, it's exactly what I'm looking for, sorry for the dumb question.

I implemented that an noticed that while debugging with XCode7 and iPhone 6s and the version of the plugin 3.1.7, I've got the permissionsStatus "authorized" back and not "granted". Is that normal?
