### ISSUE TITLE
[FEATURE] Support to switch to Bluetooth settings (or other) for iOS

### ISSUE THREAD

**Issue by mpk2** [dpa99c/cordova-diagnostic-plugin#135]
Currently, there is another plugin that supports this functionality, but 1) it's not as well set up, and 2) bluetooth settings is already supported for android. I don't think it's outside of the scope of this project to include different specific settings, so hopefully at minimum bluetooth can be supported for iOS.

(See: `https://github.com/guyromb/Cordova-open-native-settings`)

**Comment by mpk2** [comment]
I see that there are some things in iOS 10 that affect this.

**Comment by dpa99c** [comment]
AFAIK there is no officially-sanctioned method of opening specific settings pages on iOS.

Firstly, as the README says for [https://github.com/guyromb/Cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings):

> NO SUPPORT FOR IOS 10 SINCE APPLE DISABLED THIS FUNCTIONALITY

And secondly, as the [Gist upon which it's based indicates](https://gist.github.com/phynet/471089a51b8f940f0fb4):

> Note: Apple will reject apps that are using private url schemes (Ugh, Apple....) if they are pretty much obvius. Some apps are rejected and others are not, so, be aware of this issue before implementing any of those URL's in your app as a feature.

For the above reasons, I don't feel it's wise to implement functionality for iOS which Apple regards as reason to reject an app.

**Comment by mpk2** [comment]
Thanks for the response. I jumped the gun a bit on the issue.
