### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by kaynz** [dpa99c/cordova-diagnostic-plugin#137]
Hi,

my iOS build fails with cordova-plugin-diagnostic installed under Xcode 7 and El Capitan.

Here's the error: https://paste.xinu.at/WTvPJ/

Same project builds under Xcode 8 and macOS Sierra.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#version-32-for-ios-10):

> `cordova.plugins.diagnostic@3.2.0` adds support for the new UserNotifications framework added in iOS 10. To build using v3.2.0, you will need to use XCode 8+ because there's no way to conditionally include a framework using the <framework> tag in the plugin.xml.

If you want to build with Xcode 7, you must use `cordova.plugins.diagnostic@3.1`
