### ISSUE TITLE
[FEATURE] Request SIM information

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#140]
This would most likely be an Android only feature (don't know about the Windows environment) as I know this is not possible on iOS.  However adding it in here would be a great tool for Android developers.

If this is already possible please direct me to the correct documentation.  If not, this could be a good reference to get this implemented:   [cordova-plugin-sim](https://github.com/pbakondy/cordova-plugin-sim)

**Comment by kodeine** [comment]
i was looking for same. but looks like `READ_PHONE_STATE` is needed which is already supported in this plugin as per the readme. But not exactly sure how to use it.

**Comment by kodeine** [comment]
@rolinger found it, try 
```
Diagnostic.requestRuntimePermission('READ_PHONE_STATE').then()....
```
