### ISSUE TITLE
[FEATURE] Detect if Speech Recognition is enabled

### ISSUE THREAD

**Issue by psirenny** [dpa99c/cordova-diagnostic-plugin#142]
Speech recognition was recently added in iOS 10.

**Comment by lassevalentini** [comment]
Authorization status can be found in SFSpeechRecognizer.authorizationStatus
https://developer.apple.com/reference/speech/sfspeechrecognizer/1649884-authorizationstatus

Requesting authorization is done via SFSpeechRecognizer.requestAuthorization
https://developer.apple.com/reference/speech/sfspeechrecognizer/1649892-requestauthorization
