### ISSUE TITLE
requestMicrophoneAuthorization on iOS

### ISSUE THREAD

**Issue by telekosmos** [dpa99c/cordova-diagnostic-plugin#144]
Hi
is there any chance to get `requestMicrophoneAuthorization` effectively called after denying microphone access previously? 

The scenario is like it follows:

- the user accidentally chose *not* when requested for microphone use by app
- the next time the user wants to use the feat for using the microphone, we check in our code if the microphone is authorized, and in fact it isn't.
- as the documentation says, requestMicrophoneAuthorization is not working

We are using the following code:
```javascript
cordova.plugins.diagnostic.getMicrophoneAuthorizationStatus(function(status) {
          // console.log("App is " + (authorized ? "authorized" : "denied") + " access to the microphone");
          var authorized = status === cordova.plugins.diagnostic.permissionStatus.GRANTED;
          var notDetermined = status === cordova.plugins.diagnostic.permissionStatus.NOT_DETERMINED;
          var denied = status === cordova.plugins.diagnostic.permissionStatus.DENIED;
          if (!authorized) {
            cordova.plugins.diagnostic.requestMicrophoneAuthorization(function(status){
               if(status === cordova.plugins.diagnostic.permissionStatus.GRANTED){
                   console.log("Microphone use is authorized");
                   getUserMediaChecked();
               }
            }, function(error){
                console.error(error);
            });
          }
          else{
            // Microphone use is already authorized
            getUserMediaChecked();
          }
``` 
(Some vars are for testing purposes only)

Any idea on how to effectively request the mic authorization over and over if the mic auth is denied?

Thanks!!!!

**Comment by dpa99c** [comment]
> Any idea on how to effectively request the mic authorization over and over if the mic auth is denied?

This is exactly what Apple doesn't want you to do and exactly why they don't allow you re-request a permission once it has been denied. iOS allows you to specify the [NSMicrophoneUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW25) which instructs the user as to why they should allow your app to use their microphone. This plugin [provides a default](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L48) which you should override with your specific need for microphone access. From Apple's perspective, if the user presses "Deny" after reading this, then they have not agreed with your justification, hence you cannot request again to use the microphone.

So, in the case that the user presses "Deny" by mistake, the best that you can do is to detect that they have denied usage and display an appropriate message instructing them how to manually re-enable microphone usage for the app, something like this:

    function handleError(error){
        console.error(error);
    }

    function evaluateStatus(status){
        // console.log("App is " + (authorized ? "authorized" : "denied") + " access to the microphone");
        switch(status){
            case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                console.log("Microphone use is authorized");
                getUserMediaChecked();
                break;
            case cordova.plugins.diagnostic.permissionStatus.NOT_DETERMINED:
                cordova.plugins.diagnostic.requestMicrophoneAuthorization(evaluateStatus, handleError);
                break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED:
                // Use cordova-plugin-dialogs
                var dialogTitle = "Microphone access is denied";
                var dialogText = "You have denied access to use the microphone - without it this app cannot function. You'll now be switched to the Settings page for this app. Please enable the switch for 'Microphone' then return to this app.";
                navigator.notification.alert(dialogTitle, function(){
                    cordova.plugins.diagnostic.switchToSettings();
                }, dialogText);
                break;
        }
    }

    function checkMicrophoneAuthorization(){
        cordova.plugins.diagnostic.getMicrophoneAuthorizationStatus(evaluateStatus, handleError);
    }

    document.addEventListener("deviceready", checkMicrophoneAuthorization, false); // check on app start
    document.addEventListener("resume", checkMicrophoneAuthorization, false); // check on app resume

**Comment by telekosmos** [comment]
Many huge THANKS for the quick, concise and (I guess that) complete answer.
