### ISSUE TITLE
Question about registerLocationStateChangeHandler and initial location permission request on Android 6

### ISSUE THREAD

**Issue by pdrosos** [dpa99c/cordova-diagnostic-plugin#145]
Hi,

I am using the registerLocationStateChangeHandler method to detect location on/off change from user on Android 6 and it works well. However, it does not work when the app initially asks the user for permission to use location and user allows it.

Could you please let me know how to handle this situation and the app to be immediately notified when user grants initial location permissions?

Thanks!

**Comment by dpa99c** [comment]
To listen for changes in permissions, use [registerPermissionRequestCompleteHandler()](https://github.com/dpa99c/cordova-diagnostic-plugin#registerpermissionrequestcompletehandler)

**Comment by pdrosos** [comment]
Thank you a lot! 

What about iOS 10, registerLocationStateChangeHandler also doesn't seem to work when user initially grants location permissions. Is it expected, or I am doing something wrong?

**Comment by dpa99c** [comment]
I can't reproduce any issue with `registerLocationStateChangeHandler ()` on iOS 10 - it works fine when I test it using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) - see [this screen capture](http://ge.tt/6CNZOqf2). 
Tested on device and simulator, and in both cases, the callback registered by `registerLocationStateChangeHandler ()` is invoked after the user responds to the dialog to grant/deny permission.

**Comment by dpa99c** [comment]
Reopen if still an issue
