### ISSUE TITLE
iOS class `CLLocationManager` is responding slow on iOS 9.1

### ISSUE THREAD

**Issue by ektasawant** [dpa99c/cordova-diagnostic-plugin#15]
```
- (void) isLocationEnabled: (CDVInvokedUrlCommand*)command
{
   dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
    NSLog(@"Loading Location status...");
    CDVPluginResult* pluginResult;
       if([self isLocationEnabled] && [self isLocationAuthorized]) {
           pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsInt:1];
       }
       else {
           pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsInt:0];
       }
       [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
       dispatch_async(dispatch_get_main_queue(), ^{
       });
   });
}


- (BOOL) isLocationEnabled
{
   if([CLLocationManager locationServicesEnabled]) {
       NSLog(@"Location is enabled.");
       return true;
   } else {
       NSLog(@"Location is disabled.");
       return false;
   }
}
- (BOOL) isLocationAuthorized
{
   if([CLLocationManager  authorizationStatus] != kCLAuthorizationStatusDenied) {
       NSLog(@"This app is authorized to use location.");
       return true;
   } else {
       NSLog(@"This app is not authorized to use location.");
       return false;
   }
}
```
Checked timestamps entries with NSLog for 'isLocationEnabled' and 'isLocationAuthorized', it takes more than 10 seconds to execute isLocationEnabled and 1 second to execute isLocationAuthorized.And also giving warning '['Diagnostic'] took '52807.718994' ms. Plugin should use a background thread'. Mostly happened when we resume the app from background. Could anyone please answer why it is taking more time to execute isLocationEnabled?

Xcode Log:
```
2015-11-17 19:35:58.026 AppName Loading Location status...
2015-11-17 19:36:50.481 AppName Location is enabled.
2015-11-17 19:36:50.816 AppName This app is authorized to use location.
2015-11-17 19:36:50.833 AppName THREAD WARNING: ['Diagnostic'] took '52807.718994' ms. Plugin should use a background thread.
```

**Comment by dpa99c** [comment]
What device/iOS version are you testing on?

I'm unable to reproduce this - the maximum time I have seen this operation take on iPad 2 running iOS 9.1 is around 100ms.

Are you able to build/test the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on the same test platform to confirm if the plugin behaves the same way in isolation?

**Comment by dpa99c** [comment]
@ektasawant Can this be closed?

**Comment by ektasawant** [comment]
@dpa99c yes, we can close this issue because I tested https://github.com/dpa99c/cordova-diagnostic-plugin-example with iPhone5 and iOS version 9.1. I unable to reproduce mentioned issue.Thanks!!!
