### ISSUE TITLE
cordova.plugins.diagnostic-tests.ts has a bad reference path

### ISSUE THREAD

**Issue by ekrapfl** [dpa99c/cordova-diagnostic-plugin#150]
The following line breaks the cordova build for my company's application, as we do not have a cordova directory under our plugins directory.  We have typings for cordova, but they are not located in the directory that the test file expects:

`/// <reference path='../cordova/cordova.d.ts'  />`

Thanks,
Eben

**Comment by dpa99c** [comment]
There's no real need to include the tests along with the type defs, so I'll remove them.

**Comment by dpa99c** [comment]
Tests removed in cordova.plugins.diagnostic@3.3.2 - now published to npm
