### ISSUE TITLE
Can't compile in ios - isPedometerEventTrackingAvailable

### ISSUE THREAD

**Issue by brevleq** [dpa99c/cordova-diagnostic-plugin#153]
I'm trying run my application in ios after added you plugin, but I'm getting the following message when I execute `ionic run ios`:

    /Users/huroapps/Documents/cervejeiros-app/platforms/ios/Cervaki/Plugins/cordova.plugins.diagnostic/Diagnostic.m:826:25: error: no known class method for selector 'isPedometerEventTrackingAvailable'
    return [CMPedometer isPedometerEventTrackingAvailable];
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/huroapps/Documents/cervejeiros-app/platforms/ios/Cervaki/Plugins/cordova.plugins.diagnostic/Diagnostic.m:826:12: warning: incompatible pointer to integer conversion returning 'id' from a function with result type 'BOOL' (aka 'signed char') [-Wint-conversion]
    return [CMPedometer isPedometerEventTrackingAvailable];
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.

    ** BUILD FAILED **
    
    The following build commands failed:
	CompileC build/Cervaki.build/Debug-iphonesimulator/Cervaki.build/Objects-normal/i386/Diagnostic.o Cervaki/Plugins/cordova.plugins.diagnostic/Diagnostic.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

    (1 failure)

    Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/huroapps/Documents/cervejeiros-app/platforms/ios/cordova/build-debug.xcconfig,-project,Cervaki.xcodeproj,-target,Cervaki,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,build,CONFIGURATION_BUILD_DIR=/Users/huroapps/Documents/cervejeiros-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/huroapps/Documents/cervejeiros-app/platforms/ios/build/sharedpch

I'm just using the functions relative to localization. Is there something I can do to solve this?

**Comment by dpa99c** [comment]
> no known class method for selector 'isPedometerEventTrackingAvailable'

What version of XCode are you attempting to build with?

`isPedometerEventTrackingAvailable` was added in iOS 10 SDK so you need to build with XCode 8 ([as documented](https://github.com/dpa99c/cordova-diagnostic-plugin#version-32-for-ios-10))

**Comment by carlo318** [comment]
Hi,
I faced the same issue with Ionic and an app of mine.
I found out that it's not necessary to upgrade to Xcode 8, I am still using Xcode 7.3.1.
I solved by using old versions of some plugins, so they don't require the new features of IOS 10.
In my case, these are the plugins I am using and the versions I have forced to allow Ionic to compile:
(see the plugin you use and select the version)
`
  "cordovaPlugins": [
    "cordova-plugin-camera@2.3.0",
    "cordova-plugin-console@1.0.2",
    "cordova-plugin-device@1.1.0",
    "cordova-plugin-file@4.2.0",
    "cordova-plugin-file-transfer@1.5.1",
    "cordova-plugin-inappbrowser@1.2.1",
    "cordova-plugin-network-information@1.2.0",
    "cordova-plugin-splashscreen@3.0.0",
    "cordova-plugin-statusbar@2.0.0",
    "cordova-plugin-whitelist@1.2.0",	
    "cordova.plugins.diagnostic@3.1.7"
  ],
  "cordovaPlatforms": [
    "ios@3.9.2"
  ]
`

For example, to downgrade diagnostic to 3.1.7, just type:
`ionic platform remove cordova.plugins.diagnostic`
`ionic platform add cordova.plugins.diagnostic@3.1.7`

**Comment by yuriploc** [comment]
I would just add a detail:

to remove plugin:
`cordova plugin remove cordova.plugins.diagnostic --save`

to reinstall downgraded version:
`cordova plugin add cordova.plugins.diagnostic@3.1.7 --save`

**Comment by carlo318** [comment]
Thankyou yuriploc, I have updated my comment.
