### ISSUE TITLE
Merging getPermissionsAuthorizationStatus and requestRuntimePermissions

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#155]
First off...what an awesome and powerful plugin - took me a while to figure things out but your documentation is quite thorough and has helped me understand a few more things I previously didn't get.  (I searched for this answer but couldn't find it)

I am currently using chaining several permission functions together like:
```
function getPhoneStateAuth() {
    var q = $q.defer();
    cordova.plugins.diagnostic.getPermissionAuthorizationStatus(function(status) {
      if (status == "NOT_REQUESTED") {   //if not requested, then ask
        cordova.plugins.diagnostic.requestRuntimePermission(function(status){
          q.resolve(status) ;
        },function(err) {console.log("runTime ask Permission error: "+err) ;
        },cordova.plugins.diagnostic.permission.READ_PHONE_STATE) ;
      } else {
        q.resolve(status) ;
      }
    },function(err) {console.log("runTime check permission error: "+err) ;
    },cordova.plugins.diagnostic.permission.READ_PHONE_STATE) ;
    return q.promise ;
  }
function getLocationAuth() {
  ...
}

// and then chaining the function into a Angular promise:
getPhoneStateAuth().then(function(status) {   // popup question #1 
 ... do something with results
return getLocationAuth()    // popup question #2
}) .then(function(status) {
...do something with results
return getNextAuthorizationBlah()   // popup question #3
}).then(function(status) { 
...do something with results
}) ;  /// and on and on if necesssary.
```
It asks for each permission one at a time...but if I merge the above functions using getPermissionsAuthorizationStatus & requestRuntimePermissions (plural) will it still ask for each permission one at a time or will it merge the requests into a single pop up window for the user to respond to?  Or is there another method that could be used to reduce the questions or merge them so there aren't so many popups for the user to answer.  This is all happening on app initialization, so there are additional setups (intro, user registration, etc) - I am just trying to reduce the steps the user has to manually interact with.

**Comment by dpa99c** [comment]
You should batch multiple permissions into a single call to `requestRuntimePermissions()`. The native Android run-time permissions API handles this by presenting a series of linked native dialogs so the user can quickly review multiple permissions.

This is noted in the documentation, but somewhat hidden away under [isRequestingPermission()](https://github.com/dpa99c/cordova-diagnostic-plugin#isrequestingpermission):

> Note that only one request can be made concurrently because the native API cannot handle concurrent requests, so the plugin will invoke the error callback if attempting to make more than one simultaneous request. Multiple permission requests should be grouped into a single call since the native API is setup to handle batch requests of multiple permission groups.
