### ISSUE TITLE
Would it be possible to disable some usage? Like my app does not need camera and microphone features. So wondering if I can disable particular feature.

### ISSUE THREAD

**Issue by agnosco** [dpa99c/cordova-diagnostic-plugin#156]

**Comment by dpa99c** [comment]
What do you mean "disable some usage"? What platform are you referring to - Android or iOS? On both platforms, the user will not be asked to approve permission to use a feature until you use an operation associated with that feature.

**Comment by agnosco** [comment]
I don't need to access camera for my app. For IOS, when I try to submit it in app store, it says that  app attempts to access privacy-sensitive data without a usage description. So, I need to remove camera usage code from Diagnostic.h and Diagonostic.m files to get it approved. So, looking for better solution that if I should just edit the plugin or is there something else better to be done.

**Comment by dpa99c** [comment]
The plugin should add a [default usage description](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L52) to your app .plist, which is enough to satisfy the app store checks. But if you dont request camera usage, this will not be used.

**Comment by agnosco** [comment]
Thank you so much! the app was using version 2.3.17 while submitting to app store.
