### ISSUE TITLE
isRemoteNotificationsEnabled() always returning false on iOS 10.1.1

### ISSUE THREAD

**Issue by vivekpd15** [dpa99c/cordova-diagnostic-plugin#159]
I have rechecked that notifications are on and alert type is set to banner. I can see that the device is receiving a registration id as we. The same build is working fine on iOS 9 and on iOS 10.0.

Any clue what might be happening?

**Comment by dpa99c** [comment]
Not able to reproduce this: I tested with the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on iOS 10.1.1 on my iPad and isRemoteNotificationsEnabled() is working correctly - see [this screen capture](http://ge.tt/7sBmDoh2).

Please try with the example project and see if you can reproduce.

**Comment by vivekpd15** [comment]
Hey. It was a bug from the onesignal plugin. I had to update my cordova platform. Thanks anyways. You can close this now. :)
