### ISSUE TITLE
Issues with the library

### ISSUE THREAD

**Issue by srameshr** [dpa99c/cordova-diagnostic-plugin#16]
<code>platforms/android/src/cordova/plugins/Diagnostic.java:411: cannot find symbol
symbol  : method shouldShowRequestPermissionRationale(android.app.Activity,java.lang.String)
location: class android.support.v4.app.ActivityCompat
                boolean showRationale = ActivityCompat.shouldShowRequestPermissionRationale(this.cordova.getActivity(), androidPermission);
                                                      ^
platforms/android/src/cordova/plugins/Diagnostic.java:565: cannot find symbol
symbol  : method shouldShowRequestPermissionRationale(android.app.Activity,java.lang.String)
location: class android.support.v4.app.ActivityCompat
                    boolean showRationale = ActivityCompat.shouldShowRequestPermissionRationale(this.cordova.getActivity(), androidPermission);
                                                          ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /platforms/android/src/cordova/plugins/Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
100 warnings
:compileDebugJava FAILED

FAILURE: Build failed with an exception.</code>

```
* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED```

**Comment by bastian-meier** [comment]
I can confirm this Isssue when building the Android Version on phonegap build:

```
:compileDebugJava/project/src/cordova/plugins/Diagnostic.java:411: error: cannot find symbol
                boolean showRationale = ActivityCompat.shouldShowRequestPermissionRationale(this.cordova.getActivity(), androidPermission);
                                                      ^
  symbol:   method shouldShowRequestPermissionRationale(Activity,String)
  location: class ActivityCompat
/project/src/cordova/plugins/Diagnostic.java:565: error: cannot find symbol
                    boolean showRationale = ActivityCompat.shouldShowRequestPermissionRationale(this.cordova.getActivity(), androidPermission);
                                                          ^
  symbol:   method shouldShowRequestPermissionRationale(Activity,String)
  location: class ActivityCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.
```

**Comment by dpa99c** [comment]
@srameshr are you also encountering this on phonegap build or is your build environment local?

In order to support Android 6 runtime permissions, the plugin now has a dependency on the Android support library. From the error messages, it seems this dependency is not being satisfied.

I have tested this in a local build environment, building against API 22 (Android 5.1) and API 23 (Android 6.0) and both work fine, however local build uses Gradle to satisfy the dependency on the Android support library.

According to their blog, Phonegap build [now uses a Gradle build process](http://phonegap.com/blog/2015/09/28/android-using-gradle/) so this shouldn't be an issue.

**Comment by bastian-meier** [comment]
phonegap-build uses gradle, and i forced to use it per config. But it doesnt work ...

**Comment by dpa99c** [comment]
According to [their twitter feed](https://twitter.com/PhoneGapBuild), you may need to add `<preference name="android-build-tool" value="gradle" />` - have you done this?

**Comment by bastian-meier** [comment]
yes ... and in the build log i can see that gradle is used ...

**Comment by dpa99c** [comment]
OK, I may be able to put a workaround in the plugin for phonegap build (as I said, locally it builds fine) by using reflection. I'll look into it when I get some time.

**Comment by srameshr** [comment]
@dpa99c I am using cordova CLI to build. Cordova version is 5.4.0 and the latest android and building on api 23 and I get this error. I am not using phone gap build.

**Comment by dpa99c** [comment]
I'm using the same version of cordova cli and it builds fine so must be an implicit dependency that I have installed and you do not.  Will look into it when I get a chance.

**Comment by dpa99c** [comment]
I've updated the plugin (v2.3.1) to add a dependency on the v7 AppCompat support library. This should pull in the required dependencies via Gradle and resolve these build issues. Note that this means the app __must be built with SDK v23__ or above - that means `cordova-android@5.0.0` or above - and also that Android Support Library v23+ is installed in the build environment via the SDK manager.

**Comment by srameshr** [comment]
@dpa99c I will update the plugin and give it a try. Thanks.

**Comment by srameshr** [comment]
After updating to SDK 23 both on AndroidManifest.xml and project.properties, I get the following error
<code>
  UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
</code>

This is because of some jar file issue. It appears your lib includes annotations.jar file and I am using some other plugins that provide a android-support-v4.jar.

**Comment by dpa99c** [comment]
Until other plugins are updated to use Gradle to resolve Android library dependencies, this will be an issue. In the meantime, you can add a file `platforms/android/build-extras.gradle` containing the following lines:

    configurations {
        all*.exclude group: 'com.android.support', module: 'support-v4'
    }

This should override the library dependencies injected by this plugin. Note that if the android-support-v4.jar file included by other plugin(s) isn't v23+, build errors will occur due to this plugin's dependency on android-support-v4:23+

**Comment by srameshr** [comment]
Ok, Will try this out

**Comment by srameshr** [comment]
@dpa99c Thanks for this!
It works.

**Comment by srameshr** [comment]
@dpa99c 
I have once more issue. I am not really familiar with gradle, so bear with me!

When I try to build my project via cordova cli, I get the following error 
```
Found com.google.android.gms:play-services-location:+, but version 8.3.0 is needed for the google-services plugin.
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 8.3.0.
```

I guess, this is occuring because of this in my build.gradle file:
```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.facebook.android:facebook-android-sdk:4.+"
    compile "com.google.android.gms:play-services-location:+" // This line in particular
    // SUB-PROJECT DEPENDENCIES END
}
```

So to overcome this, can I add something like this in build-extras.gradle ?
```
dependencies {
  compile "com.google.android.gms:play-services-location:8.3.0"
}
```

I tried this and cordova build is not working nor failing. It is just stuck at 
```
> Configuring > 0/2 projects > root project > Resolving dependencies ':classpat
```

**Comment by dpa99c** [comment]
@srameshr 
This plugin doesn't add a dependency on location services, so it's likely that error is being caused by another plugin. This plugin only adds dependencies on the Android Support library as you can see in the [plugin.xml](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L53):

    <framework src="com.android.support:support-v4:23.+" />
    <framework src="com.android.support:appcompat-v7:23.+" />

**Comment by srameshr** [comment]
@dpa99c Can you let me know how to fix this?

**Comment by dpa99c** [comment]
@srameshr it has nothing to do with this plugin, so no I can't help. Raise an issue on the GCMPushPlugin repo.

**Comment by srameshr** [comment]
@dpa99c Nobody responds there. If you have time please do try to look at it. Thanks for the help.

**Comment by ArjunNagraj** [comment]
@dpa99c I get the following error when i am trying to make a build.

 Could not find any version that matches com.android.support:support-v4:23.+.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
    https://repo1.maven.org/maven2/com/android/support/support-v4/
<androidadt>/sdk/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml

the similar error follows for the appcompat dependency.

I have installed the latest version of support via sdk manager.
Wat could be the possibilities for the error.

**Comment by dpa99c** [comment]
@ArjunNagraj Make sure you have downloaded Android Support Repository (not only Android Support Library)

**Comment by sarunkumar1990** [comment]
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/
v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoV
ersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.


BUILD FAILED

Total time: 25.583 secs
* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.
common.process.ProcessException: org.gradle.process.internal.ExecException: Proc
ess 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non
-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\poorvika\platforms\android\src\cordova\plugins\Diagnostic.java uses unc
hecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/
v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoV
ersionImpl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/acce
ssibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionI
mpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
4)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.
common.process.ProcessException: org.gradle.process.internal.ExecException: Proc
ess 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non
-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.



I am developing ionic project. please help me

**Comment by ArjunNagraj** [comment]
i do not know why this occurs ....Everything workd fine on my debug build.....In the release build it fails to get cordova.plugin
