### ISSUE TITLE
Plugin is undefined when using phonegap build. Cannot read property 'isLocationEnabled' of undefined

### ISSUE THREAD

**Issue by klotim** [dpa99c/cordova-diagnostic-plugin#160]
Hello, I used your test zip from https://github.com/dpa99c/cordova-diagnostic-plugin/issues/68
test_project.zip

Using samsung Galaxy s6

And When I build this with phonegap, I get this on the phonegap console: 
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=LZuhM6j
200 /socket.io/?EIO=3&transport=polling&t=LZuhM7H&sid=RwUbf2avgQdF3ByMAAAC
200 /socket.io/?EIO=3&transport=polling&t=LZuhM8h&sid=RwUbf2avgQdF3ByMAAAC
 deviceready
 An exception occurred: Cannot read property 'isLocationEnabled' of undefined

**Comment by dpa99c** [comment]
Works fine for me with Phonegap Build: I've put that zipped project into a [github repo](https://github.com/dpa99c/cordova-diagnostic-plugin-phonegap-build-example) with appropriate PGB metadata and created a [PGB project from it](https://build.phonegap.com/apps/2396044/builds) which builds fine and if you [download the built APK](https://build.phonegap.com/apps/2396044/download/android) it works as expected.

**Comment by klotim** [comment]
Oh, Seems like it doesn't work my emulate with phonegap, an actual build was needed. Thanks.
Sorry for your time.
