### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by kiwipal** [dpa99c/cordova-diagnostic-plugin#162]
Hi,

Could you please confirm that the plugin can only work in a 100% native environment?

I can't make it work with # PhoneGap Serve
and the iOS phonegap test app (on iOS 10)
(I know that it wont work in the browser)

I have tried lots of different configs, including "hello world" versions, and the latest branch as precised in your documentation. But after a full day of tests, I give up :-)

I have also double checked that the test are done when device is ready, etc.

I have also teste your demo project:
https://github.com/dpa99c/cordova-diagnostic-plugin-example#ios
And it doesn't work, even in a:
#phonegap run ios

Regards,

Guillaume.

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="mobile.partner.expedicar.com" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>test</name>
    <description>
        A basic Framework7 template for PhoneGap.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="https://s3-eu-west-1.amazonaws.com/*" />
    <access origin="http://192.168.1.53:8081" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <preference name="android-minSdkVersion" value="14" />
        <allow-intent href="market:*" />
        <splash density="land-hdpi" src="res/screen/android/splash-land-hdpi.png" />
        <splash density="land-ldpi" src="res/screen/android/splash-land-ldpi.png" />
        <splash density="land-mdpi" src="res/screen/android/splash-land-mdpi.png" />
        <splash density="land-xhdpi" src="res/screen/android/splash-land-xhdpi.png" />
        <splash density="land-xxhdpi" src="res/screen/android/splash-land-xxhdpi.png" />
        <splash density="land-xxxhdpi" src="res/screen/android/splash-land-xxxhdpi.png" />
        <splash density="port-hdpi" src="res/screen/android/splash-port-hdpi.png" />
        <splash density="port-ldpi" src="res/screen/android/splash-port-ldpi.png" />
        <splash density="port-mdpi" src="res/screen/android/splash-port-mdpi.png" />
        <splash density="port-xhdpi" src="res/screen/android/splash-port-xhdpi.png" />
        <splash density="port-xxhdpi" src="res/screen/android/splash-port-xxhdpi.png" />
        <splash density="port-xxxhdpi" src="res/screen/android/splash-port-xxxhdpi.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="BackupWebStorage" value="none" />
        <splash src="res/screen/ios/Default@2x~universal~anyany.png" />
    </platform>
    <platform name="browser">
        <preference name="SplashScreen" value="static/img/splashscreen/browser.png" />
        <preference name="SplashScreenDelay" value="1000" />
        <preference name="SplashScreenBackgroundColor" value="#464646" />
        <preference name="ShowSplashScreen" value="true" />
        <preference name="SplashScreenWidth" value="170" />
        <preference name="SplashScreenHeight" value="200" />
    </platform>
    <preference name="DisallowOverscroll" value="true" />
    <preference name="SplashScreen" value="screen" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="permissions" value="none" />
    <preference name="orientation" value="default" />
    <preference name="target-device" value="universal" />
    <preference name="fullscreen" value="false" />
    <preference name="webviewbounce" value="true" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <engine name="ios" spec="~4.3.1" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.0" />
    <plugin name="cordova-plugin-console" spec="~1.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="~1.0.1" />
    <plugin name="cordova-plugin-device" spec="~1.1.4" />
    <plugin name="cordova-plugin-camera" spec="~2.3.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="conveyor pictures" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="conveyors pictures" />
    </plugin>
    <plugin name="cordova-plugin-dialogs" spec="~1.3.1" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.6.1" />
    <plugin name="cordova-plugin-geolocation" spec="~2.4.1" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.1" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="cordova-plugin-vibration" spec="~2.1.3" />
    <plugin name="cordova-plugin-globalization" spec="~1.0.5" />
    <plugin name="cordova.plugins.diagnostic" source="npm" />
</widget>


```

**Comment by dpa99c** [comment]
> https://github.com/dpa99c/cordova-diagnostic-plugin#native-environment-required
> I can't make it work with # PhoneGap Serve and the iOS phonegap test app

[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#native-environment-required):

Note that this plugin is intended for use in a native mobile environment. It will NOT work in a browser-emulated Cordova environment, for example by running cordova serve or using the Ripple emulator.

> I have also tested your demo project and it doesn't work, even in phonegap run ios

It works fine on iOS 10 - see [this video](http://ge.tt/7sBmDoh2).

If you have a specific problem with the demo project then you should open an issue under that repo giving full details such as component versions, screenshots and verbose console output. Without these details it's not possible to determine if a problem exists and the issue will be closed.

Foot note: This plugin is intended for use by professional Cordova/Phonegap developers with a comprehensive understanding of the ecosystem.

**Comment by kiwipal** [comment]
Well, the problem is that your documentation is not clear here:

> Note that this plugin is intended for use in a native mobile environment. It will NOT work in a browser-emulated Cordova environment, for example by running cordova serve or using the Ripple emulator.

Because when I read it (and I did), I thought you were saying that it won't work if I use phonegap serve, and check the result in Chrome... Most other plugins works in PhoneGAp iOS app on the mobile device (which many will consider to be a native environment since it runs on a mobile).

So I suggest that you update the documentation with this:

> Note that this plugin is intended for use in a native mobile environment. It will NOT work in a browser-emulated Cordova environment, for example by running cordova serve (you can't check the result in web browsers like Chrome or in the Phonegap iOS App)  or using the Ripple emulator. If not used in a native environment, the cordova.plugins.diagnostic will return an undefined error.

For the rest, I won't lose any more time, since your are in RTFM mode, but I think updating the documentation may save other mortals like me.
