### ISSUE TITLE
isRemoteNotificationsEnabled is not a function

### ISSUE THREAD

**Issue by inngage** [dpa99c/cordova-diagnostic-plugin#163]
Hi,
when i try to call function **isRemoteNotificationsEnabled** the following error is displayed:
01-01 00:57:59.965 11731-11731/br.com.inngage.upbrasil I/chromium: [INFO:CONSOLE(314)] "Uncaught TypeError: cordova.plugins.diagnostic.isRemoteNotificationsEnabled is not a function", source: file:///android_asset/www/cordova.js (314)

Strangely, i can call the function **isLocationEnabled** without problem.

Call example:
           cordova.plugins.diagnostic.isRemoteNotificationsEnabled(function(enabled){
                console.log("Remote notifications are " + (enabled ? "enabled" : "disabled"));
            }, function(error){
                console.error("The following error occurred: "+error);
            });

**Comment by sagarkulkarni3592** [comment]
I am facing the similar issue. What was the solution for this?

**Comment by KishanIos007** [comment]
I have the same(test in android device).. i know this is for the only IOS device buts still i want to see whether the use has allow notification on android or not ???
   if anyone has the solution plz share.. :-)
