### ISSUE TITLE
getMicrophoneAuthorizationStatus not calling success or error functions

### ISSUE THREAD

**Issue by AhsanAyaz** [dpa99c/cordova-diagnostic-plugin#166]
cordova -v
6.4.0
Ionic -v
2.1.18

cordova.plugins.diagnostic 3.2.2 "Diagnostic"

````
cordova.plugins.diagnostic.requestMicrophoneAuthorization(function(status){
           if(status === cordova.plugins.diagnostic.permissionStatus.GRANTED){

           }
           else{
            // alert("Microphone not authorized");
           }
        }, function(error){
            console.error(error);
        });
````

The above function in an ionic application is not calling neither success nor error callback function. 
Can anyone help me with that?

**Comment by dpa99c** [comment]
Which platform (Android/iOS) and platform version are you testing on? And what device?

Try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which [includes a call to `requestMicrophoneAuthorization()`](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L73) which logs a message to the console when the success callback is invoked. Try running this in the same device environment and see if you can reproduce the issue - I just tested it and the log message appears fine using Android 7.1 and iOS 10.2

**Comment by dpa99c** [comment]
Reopen if still an issue
