### ISSUE TITLE
Timeout when adding plugin from registry

### ISSUE THREAD

**Issue by emreiser** [dpa99c/cordova-diagnostic-plugin#170]
I have tried adding this plugin multiple times from the registry using cordova.plugins.diagnostic and cordova-plugin-diagnostic and am getting timeouts every time. Has plugin hosting changed?

Fetching plugin "cordova.plugins.diagnostic" via plugin registry
npm http GET http://registry.cordova.io/cordova.plugins.diagnostic
npm http GET http://registry.cordova.io/cordova.plugins.diagnostic
/Users/emreiser/code/ccm/promise-tracker-mobile/plugins/fetch.json npm http GET http://registry.cordova.io/cordova.plugins.diagnostic
Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by dpa99c** [comment]
This has nothing to do with the plugin - it's hosted with npm as are all Cordova plugins in the registry.

Either your connection or the registry server are the problem.

You could try adding the plugin directly from the Github repo in the meantime:

    cordova plugin add https://github.com/dpa99c/cordova-diagnostic-plugin
