### ISSUE TITLE
module.exports missing in v3.4.0 (for Android)

### ISSUE THREAD

**Issue by cyparu** [dpa99c/cordova-diagnostic-plugin#173]
The instance export is missing in **android/diagnostic.js** module in v3.4.0 (see [v3.3.3](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/3.3.3/www/android/diagnostic.js#L1079)). 
``` javascript
module.exports = new Diagnostic();
```
Maybe it was deleted by accident.

**Comment by dpa99c** [comment]
Oops, you're right. Not sure how that got missed. Will push out v3.4.1 as a patch to fix it.

**Comment by cyparu** [comment]
:open_mouth: you've been really fast ! :clap: 
Already solved my problem with your :rocket: support !
