### ISSUE TITLE
Taking action on success that requires a parameter -- example requested

### ISSUE THREAD

**Issue by wwhyte** [dpa99c/cordova-diagnostic-plugin#174]
Thanks for making this plugin!

In the Android version of my app, I want to:
* Check if I have access to external storage
* If I do, write a file to it

It seems like the natural way to do this is to pass the file as an argument to the success callback, but the success callback only takes one argument, so I'm not sure what I'm meant to do.

Could you post an example for this use case?

**Comment by dpa99c** [comment]
You can pass through additional arguments using [bind()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind), for example:

    function successFn(myArg1, myArg2, status){
        switch(status){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted to use the camera");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission to use the camera has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied to use the camera - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use the camera - guess we won't be using it then!");
                break;
        }
        
        console.log("myArg1: "+myArg1);
        console.log("myArg2: "+myArg2);
    }
    
    function errorFn(myArg1, myArg2, error){       
        console.error("The following error occurred: "+error);
        console.log("myArg1: "+myArg1);
        console.log("myArg2: "+myArg2);
    }
    
    
    var myArg1 = "foo";
    var myArg2 = "bar";
    
    cordova.plugins.diagnostic.getPermissionAuthorizationStatus(
        successFn.bind(this, myArg1, myArg2), 
        errorFn.bind(this, myArg1, myArg2),
        cordova.plugins.diagnostic.runtimePermission.CAMERA
    );

**Comment by wwhyte** [comment]
That worked great, thanks! Since the levels of auth are a little tricky, here's the exact code I ended up writing -- feel free to use it as the basis of an example if you think it'd help others. It uses the cordova-plugin-save-image plugin.

```
function pictureSaver(photoData) {
  console.log("saving photo"); 
  var photoParams = { data: "", prefix: "MyApp_"};
  photoParams.data = photoData;
  window.imageSaver.saveBase64Image(photoParams, function(filePath) {
    console.log("File saved at " + filePath);
  },
  function(err) {
    console.log("Error saving with message " + err);
  });
}

function pictureHandlerAfterAuthRequest(photoData, allowed) {
  if(allowed == cordova.plugins.diagnostic.permissionStatus.GRANTED) {
    pictureSaver(photoData);
    return;
  }
  
  var errStr = "access to storage not allowed";
  console.log(errStr);
  alert(errStr);
}



function pictureHandler(photoData, allowed) {
  if(allowed) {
    pictureSaver(photoData);
    return;
  }
  // not allowed, need to request permissions
  cordova.plugins.diagnostic.requestExternalStorageAuthorization(
    pictureHandlerAfterAuthRequest.bind(this, photoData),
    function (err) { 
      var errStr = "error '" + err + "' requesting access to photo gallery storage";
      console.log(errStr);
      alert(errStr);
    }
  );
}

document.addEventListener('deviceready', function () {
  CameraPreview.setOnPictureTakenHandler(function(photoData){
    cordova.plugins.diagnostic.isExternalStorageAuthorized(
      pictureHandler.bind(this, photoData),
      function (err) { 
        var errStr = "error '" + err + "' checking access to photo gallery storage";
        console.log(errStr);
        alert(errStr);
      }
    );
  });
}, false);
```

**Comment by dpa99c** [comment]
Great, glad it worked. Closing now as the original question is resolved.
