### ISSUE TITLE
error isGpsLocationEnabled is not a function

### ISSUE THREAD

**Issue by gbelmm** [dpa99c/cordova-diagnostic-plugin#176]
ERROR: Error: window.cordova.plugins.diagnostic.isGpsLocationEnabled is not a function

code

window.cordova.plugins.diagnostic.isGpsLocationEnabled(function(enabled){
          alert("GPS location is " + (enabled ? "enabled" : "disabled"));
      }, function(error){
          alert("The following error occurred:");
      });
plugins instaled

![captura de pantalla 2017-02-06 a las 15 00 46](https://cloud.githubusercontent.com/assets/731936/22659687/5464ffcc-ec7d-11e6-9614-6f4b0e953d78.png)

**Comment by gbelmm** [comment]
In android, the first use works, I close the app and it no longer works

**Comment by dpa99c** [comment]
Please check you are only calling `isGpsLocationEnabled` once the `deviceready` event has fired.

You can refer to the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for [illustrated usage](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L400) and to validate the plugin method works under all expected circumstances.

I would also suggest using Chrome Dev Tools to connect a remote debug session and place a breakpoint on your invocation of the method to determine if the plugin object is defined when the call fails.

**Comment by gbelmm** [comment]
gracias

**Comment by sagarkulkarni3592** [comment]
I am facing the same issue in ionic app for `switchToLocationSettings()`.
And yes the Diagnostic plugin is called after the deviceready event.

The strange thing is, when I add the plugin using `cordova plugin add cordova.plugin.diagnostic` and when I see the plugin code as in files `diagnostic.js` and `diagnostic.d.ts` I do not find some of the function definitions like `switchToLocationSettings()`. Plugin version installed is `3.6.5`.

What should I do? In fact my android platform is also up to date.

**Comment by dpa99c** [comment]
@sagarkulkarni3592 If you are using the [Ionic Native Typescript wrapper](https://github.com/driftyco/ionic-native/tree/master/src/%40ionic-native/plugins/diagnostic) to reference the plugin, check you are using an up-to-date version.

Or you can reference the plugin directly via the `cordova.plugins.diagnostic` namespace.

If you look in the [plugin source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L286), you'll see that all the documented functions are defined.
