### ISSUE TITLE
Include a couple of functions included in this plugin into the location accuracy plugin.

### ISSUE THREAD

**Issue by srameshr** [dpa99c/cordova-diagnostic-plugin#177]
The diagnostics plugins when installed, increases the release size by 2 MB. How about adding a couple of functions related to geo location, into the location accuracy plugin. For starters you could do ``` cordova.plugins.diagnostic.isLocationEnabled ``` and few others that makes sense. In order to use a couple of checks related to geolocation I end up downloading rest of the plugin.

**Comment by dpa99c** [comment]
I don't have any plans to duplicate functionality from this plugin into the location accuracy plugin but you are welcome to fork the plugin and do that yourself
