### ISSUE TITLE
requestCameraAuthorization should not request EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-diagnostic-plugin#178]
According to the readme the reason the `requestCameraAuthorization` also requests storage permission is the referenced (default cordova) camera plugin. 
However, I am using a QR scanner plugin, which uses the camera nativly and not facilitates the camera plugin. So the `EXTERNAL_STORAGE` is not required and confuses the users.

Therefore, in favour of less than more permissions, I'd argue for a slightly changed behaviour:

The combined permissions are only requested when a newly introduced static config property `diagnostics.combineCameraPermissions` is set to true (default). Then users who do not use the default camera plugin can opt out of bugging their users with requesting `EXTERNAL_STORAGE` permissions.

What you think? Would provide a PR

**Comment by dpa99c** [comment]
I understand your requirement. I think an additional config property is bit confusing though, so I'd be inclined to add an additional optional argument to `requestCameraAuthorization` which allows platform-specific options to be passed, something like this:

    cordova.plugins.diagnostic.requestCameraAuthorization(successCallback, errorCallback, opts);
     
Parameters

- {Function} successCallback -  The callback which will be called when operation is successful.
This callback function is passed a single string parameter indicating whether access to the camera was granted or denied:
`cordova.plugins.diagnostic.permissionStatus.GRANTED` or `cordova.plugins.diagnostic.permissionStatus.DENIED`
- {Function} errorCallback -  The callback which will be called when operation encounters an error.
This callback function is passed a single string parameter containing the error message.
- {Object} opts - (optional) platform-specific options:
    - {Boolean} externalStorage - (Android only) If true, requests permission for `READ_EXTERNAL_STORAGE` in addition to `CAMERA` run-time permission. [cordova-plugin-camera@2.2+](https://github.com/apache/cordova-plugin-camera) requires both of these permissions. Defaults to true.
    
    
So you could call:

    cordova.plugins.diagnostic.requestCameraAuthorization(successCallback, errorCallback, {
        externalStorage: false
    });

This wouldn't affect the iOS implementation which would simply ignore the `opts` argument, but allows iOS-specific options to be passed in future.

`isCameraAuthorized()` and `getCameraAuthorizationStatus()` would also need an equivalent argument.

What do you think?

**Comment by pke** [comment]
I am ok with that. I just don't like options to be passed as the last arg generally. Because then, if you don't want to handle errors, you have to pass `null` as the second param, just to pass some options.
There is a way to handle this in a back-compatible way:

``` es6
function requestCameraAuthorization(options, success, error) {
  if (typeof options === "function") {
    options = undefined
    success = arguments[0]
    error = arguments[1]
  }
}

cordova.plugins.diagnostic.requestCameraAuthorization({externalStorage: false}, success, error)
// and 
cordova.plugins.diagnostic.requestCameraAuthorization(success, error)
// would work
```

But you are the author and if you prefer options as the last arg I am all fine with that.

**Comment by dpa99c** [comment]
Options as the first parameter is a bit counter-intuitive to me given all the other functions in the plugin put success first. 
Also, success is also optional, so really the cleanest would be to put all arguments under a single options object, since they're all optional:

    /**
    * {Object} options - (optional) parameters:
    *   - {Function} successCallback - ...
    *   - {Function} errorCallback - ...
    *   - {Boolean} externalStorage - (Android only) ...
    */
    function requestCameraAuthorization(options) {
      options = options || {};
      if (typeof options === "function") {
        options = {
            success: arguments[0],
            error = arguments[1]    
        };
      }
      
      var permissions = [Diagnostic.permission.CAMERA];
      if(options.externalStorage !== false){
        permissions.push(Diagnostic.permission.READ_EXTERNAL_STORAGE);
      }
      
      options.success = options.success || function(){};
      var onSuccess = function(statuses){
        options.success(statuses.length > 1 ? combineCameraStatuses(statuses): statuses[0]);
      }
      
      Diagnostic.requestRuntimePermissions(onSuccess, options.error, permissions);
    }
    
    
    // New API
    cordova.plugins.diagnostic.requestCameraAuthorization({
        success: success,
        error: error,
        externalStorage: false
    });
    
    // Old API
    cordova.plugins.diagnostic.requestCameraAuthorization(success, error);
    cordova.plugins.diagnostic.requestCameraAuthorization(success);
    cordova.plugins.diagnostic.requestCameraAuthorization();
   
Make sense?

**Comment by pke** [comment]
Make it so 👍

**Comment by pom421** [comment]
Very interested by this issue as well. 
We use the barcode scanner only and have achieved to reduce the number of permissions requested (by removing the need of external storage permission which was frustrating for users who didn't understand the reason why it was needed).

Did i have well understood when i say that local storage (to distinguish between denied and denied_always statuses) doesn't need any extra permission?

**Comment by dpa99c** [comment]
@pom421 this issue concerns requesting of EXTERNAL_STORAGE permission (not local storage) in addition to CAMERA permission. This is because cordova-plugin-camera requires both these permissions but other plugins do not, so the intent is to make requesting of EXTERNAL_STORAGE optional.

**Comment by dpa99c** [comment]
Published in `cordova.plugins.diagnostic@3.5.0`

**Comment by pke** [comment]
:fireworks: Thanks!
