### ISSUE TITLE
Adding the plugin has compilation problems

### ISSUE THREAD

**Issue by NicoJuicy** [dpa99c/cordova-diagnostic-plugin#18]
I'm having the following error when building using cordova-diagnostic-plugin.

The build error comes as soon as i add the plugin and doesn't even go away when i remove the plugin.
I don't have any resources there, yet it searches for them.

Any thoughts on what it could be?

![debug-runtime-permissions](https://cloud.githubusercontent.com/assets/445937/11380929/5c9e63ba-92f9-11e5-85d6-e56eb779c57d.png)

**Comment by dpa99c** [comment]
Are you compiling against API 23 (cordova-android@5.0.0) or lower (e.g. API 22 / cordova-android@4.1.1)? 

The error message looks like it's being raised when compiling the v23 support library. Since introducing support for Android 6 runtime permissions, the plugin must depend on `com.android.support:support-v4:23.+` so will only compile using SDK v23 (Android 6.0).

**Comment by dpa99c** [comment]
To entirely remove the plugin (i.e. the libraries it depends on), you may need to either remove/re-add the android platform or manually remove these lines from `platforms/android/build.gradle`:

    compile "com.android.support:support-v4:23.+"
    compile "com.android.support:appcompat-v7:23.+"

**Comment by NicoJuicy** [comment]
K. I thought i already removed the following lines:

    compile "com.android.support:support-v4:23.+"
    compile "com.android.support:appcompat-v7:23.+"

But i checked further, and i'm building cordova on Visual Studio Tools for Cordova, which has a seperate file: project.properties, where the libraries are also mentioned for building..

So i didn't really remove the libraries ( they got back in later) :-(

I thought i also build against v23, but there is a chance that it also got overridden. I'll check it when i can, currently i'll close this issue, because it seems to be a correct / possible answer because of the overwritten build properties :(

Thanks a lot! Good job!
