### ISSUE TITLE
Bug: Diagnostic.registerNFCStateChangeHandler doesn't exist

### ISSUE THREAD

**Issue by daviddbeasy** [dpa99c/cordova-diagnostic-plugin#184]
When trying to use this method in Diagnostic i have this error:
`Property 'registerNFCStateChangeHandler' does not exist on type 'typeof Diagnostic'.`

Tested with "ionic-native":  versions 2.8.1 and 2.4.1, even in a clean Ionic blank project.

I think this method has been lost.

**Comment by dpa99c** [comment]
`registerNFCStateChangeHandler()` is present in both the [most recent plugin release](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/3.4.1/www/android/diagnostic.js#L1222) and is [wrapped by ionic-native@2.8.1](https://github.com/driftyco/ionic-native/blob/v2.8.1/src/plugins/diagnostic.ts#L595). Its use is also [illustrated in the example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L53).

Please make sure you are using the most recent version of the plugin and of Ionic native.

**Comment by daviddbeasy** [comment]
The problem is that i get a Typescript error whent trying to call the
method, and the call doesn't go to the plugin. Also, with Microsoft Visual
Studio i get an error saying the method doesn¡t exist. This is my
package.json file:
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.8.1",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "promise.prototype.finally": "^2.0.1",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "@types/promise.prototype.finally": "^2.0.0",
    "typescript": "2.2.1"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-globalization",
    "cordova.plugins.diagnostic",
    "phonegap-nfc"
  ],
  "cordovaPlatforms": [],
  "description": "ProserviceApp: An Ionic project"
}


2017-03-15 15:47 GMT+01:00 Dave Alden <notifications@github.com>:

**Comment by daviddbeasy** [comment]
Hi, have you been able to use the method registerNFCStateChangeHandler?
Even if i create a new blank ionic project, and try to use it, i have an
error.

2017-03-15 16:39 GMT+01:00 David Domínguez Briante <daviddbeasy@gmail.com>:

**Comment by dpa99c** [comment]
As I've said, you can try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which illustrates and validates usage of all plugin API methods, [including `registerNFCStateChangeHandler()`](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L53).

In terms of Ionic v2/Typescript, [Ionic Native](https://github.com/driftyco/ionic-native) provides a [Typescript wrapper](https://github.com/driftyco/ionic-native/blob/master/src/plugins/diagnostic.ts) around the plugin API, which provides a promise API and type definitions, therefore any issues with typings or the Ionic Native API (`Diagnostic` namespace as opposed to `cordova.plugins.diagnostic`) should be raised on their [issue tracker](https://github.com/driftyco/ionic-native/issues).

This plugin also provides its own [type definitions](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/cordova.plugins.diagnostic.d.ts) for the asynchronous plugin API (as opposed to the Ionic Native promise API).

**Comment by daviddbeasy** [comment]
Thanks, you are right.
