### ISSUE TITLE
requestLocationAuthorization successcallback triggers too early

### ISSUE THREAD

**Issue by HuaHub** [dpa99c/cordova-diagnostic-plugin#185]
cordova.plugins.diagnostic.requestLocationAuthorization(successCallback, errorCallback, mode);

The successcallback triggers too early, resulting in "status" in always "not determined", instead of the user's choice.

**Comment by dpa99c** [comment]
Please provide some more information:

- Cordova platform version (cordova-android/cordova-ios) e.g. cordova-android@6.1.0
- Platform (Android or iOS)
- Platform type (device or emulator)
- Platform version e.g. iOS 10.3
- Platform details (device type or emulator details) e.g. iPhone 6

**Comment by HuaHub** [comment]
Cordova 6.5.0
IOS
Device: iPhone 6
iOS: 10.2.1

**Comment by dpa99c** [comment]
I'm unable to reproduce your issue running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) in the iOS 10.2 Simulator - see [this screencast](http://ge.tt/4qBZyQj2).

Please try building and running the example project and confirm if you get the same result.

**Comment by HuaHub** [comment]
Thanks for the screencast.

IOS Platform 4.3.1 btw.
I upgraded to iOS10.3, but the successcallback still runs instantly. 

Sorry, I don't have the opportunity to run the example project this week.

**Comment by dpa99c** [comment]
Notify with details if still an issue and I will reopen

**Comment by 0x62** [comment]
This is still an issue (encountered myself), however I've found a way to resolve it.

If you use `requestLocationAuthorization` before calling `getLocationAuthorizationStatus`, it sees the change of authorization state from `undefined` to `not_determined`, and triggers the callback. If you use `getLocationAuthorizationStatus`, then request authorization it functions as expected.

**Comment by dpa99c** [comment]
Will look into it

**Comment by 0x62** [comment]
I've only debugged on iOS, so not sure whether the issue is the same for Android. 

```
ionic: 3.0.0
cordova: 7.0.0
iOS: 10.3.1
```

**Comment by dpa99c** [comment]
@0x62 Thanks for your explanation of the issue - I was able to reproduce it and have fixed it in the above commit, published to npm as v3.6.3.
