### ISSUE TITLE
Not working still

### ISSUE THREAD

**Issue by shamun** [dpa99c/cordova-diagnostic-plugin#187]
I have successfully installed the plugin for Cordova 6.0.1. Then i tried this: http://stackoverflow.com/a/36343809/285594

But i do not see any permission request nor i can see anything related to plugin happening in my setup.

Could you please explain please?

**Comment by dpa99c** [comment]
See the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which fully illustrates/validates the plugin, including Android runtime permissions.

For an explicit example of using it with Android runtime permissions see [cordova-diagnostic-plugin-android-runtime-example](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example)

**Comment by shamun** [comment]
Thank you.

How strange, both sample apps are working absolutely without any issue. But my app is failing. very frustrating. i even inclued all the third party plugins in the 2 sample apps but yet it works
