### ISSUE TITLE
getMicrophoneAuthorizationStatus makes iOS app lose focus?

### ISSUE THREAD

**Issue by KidBit** [dpa99c/cordova-diagnostic-plugin#189]
I don't know if I'm doing something wrong, but my cordova app checks/requests microphone authorization, and it looks like the app loses focus on the iPad. It seems to hang until I swipe bottom-to-top (view all active apps and select one), where I reselect my app, and then it continues (or request the status). Has anybody any idea why this is?

**Comment by dpa99c** [comment]
Check that you have a suitable Content Security Policy in place - see [this SO answer](http://stackoverflow.com/a/38410379/777265).

You can also build+run/analyse the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which illustrates+validates the plugin functionality, including [getMicrophoneAuthorizationStatus](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L535)

**Comment by dpa99c** [comment]
Closing due to no response from OP.
