### ISSUE TITLE
Android 6.0 Permission granted but not allowed for requesting CurrentLocation

### ISSUE THREAD

**Issue by NicoJuicy** [dpa99c/cordova-diagnostic-plugin#19]
Hi,

I'm not entirely sure that the runtime permissions on Android 6.0 work. I added everything as told, received granted everytime i requested the permissions ( build was set on Android sdk 23 and it was the only version).

Then i request my current position, i always receive:

    message: application does not have sufficient geolocation permissions.

But i requested the runtime permissions earlier on, and the return was:

    Successfully requested location authorization

My Androidmanifest was the same as the one when i had sdk 22 as target, so i didn't remove anything there. The issue seemed the runtime permissions.

Could you add a button on your example app which requests your current location? Because i think it doesn't receive the right permissions somehow.

    - Add the geolocation plugin

                var posOptions = { timeout: 35000, enableHighAccuracy: true, maximumAge: 5000 };
                navigator.geolocation
                  .getCurrentPosition(function(position) {
                      var lat = position.coords.latitude;
                      var long = position.coords.longitude;
                  }, function (err) {
                      console.log(err.code + " " + err.message);
                  });

**Comment by dpa99c** [comment]
I can't actually test this since I don't have a device running Android 6 and due to [this bug](https://issues.apache.org/jira/browse/CB-9945), I can't test it in the Android 6 emulator.

I've updated the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to include a request location button, so could you test that on an Android 6 device and let me know the result?

I've also created a [test project](https://dpa99c@bitbucket.org/dpa99c/android-m-location-test) to illustrate the Android 6 emulator issue. This uses the latest versions of [cordova-android](https://github.com/apache/cordova-android) (@5.0.1-dev) and [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation) (@2.0.0) which now includes code to request Android 6 runtime permission for location.
I'd be interested to know if you encounter the same runtime permissions problem with that project, since the runtime permissions logic in this plugin is based on that within these updated cordova packages.

**Comment by NicoJuicy** [comment]
Hi,

Ran it with the latest possible Cordova using Visual Studio

![screenshot_20151130-020513](https://cloud.githubusercontent.com/assets/445937/11461629/49f736da-9707-11e5-9e46-85dc1c17ff13.png)
![screenshot_20151130-020556](https://cloud.githubusercontent.com/assets/445937/11461628/49f6f260-9707-11e5-92d9-e0090163d527.png)

Seems to be the same issue as i thought. I'll follow up tomorrow on possible dependency issues though. Eg. isn't the cordova-plugin-geolocation @1.0.1 ? 

But currently, i have the same issues with that project. It says it's okay, but i don't have any permissions.

**Comment by NicoJuicy** [comment]
The camera also doesn't seem to work, this is my android manifest ( for use with your app)

    <?xml version='1.0' encoding='utf-8'?>
    <manifest android:hardwareAccelerated="true" android:versionCode="2" android:versionName="0.0.2" package="uk.co.workingedge.phonegap.plugins.example.diagnostic" xmlns:android="http://schemas.android.com/apk/res/android">
        <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
        <uses-permission android:name="android.permission.INTERNET" />
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
        <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
            <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
                <intent-filter android:label="@string/launcher_name">
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
        </application>
        <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
        <uses-permission android:name="android.permission.BLUETOOTH" />
        <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
        <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
        <uses-permission android:name="android.permission.CAMERA" />
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
        <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    </manifest>

If you have any advice on how i can help. I'd be happy to, cause i wouldn't know how to fix this.    

![screenshot_20151201-002311](https://cloud.githubusercontent.com/assets/445937/11487783/051b125a-97c2-11e5-9f31-970b54edca99.png)

**Comment by NicoJuicy** [comment]
Weird thing is, if i open up Google Maps, my "HIgh Location accuracy" is shared with my Cordova app. I can't initiate it by itselve though.

**Comment by dpa99c** [comment]
I've updated my Android 6.0 emulator to revision 9 (of "Google APIs Intel x86 Atom System Image") and now I'm having more success. 

Camera permissions work fine: I'm able to request camera permissions and then take a photo.

With location, everything works apart from when current location is requested, the success (or error) callback is not called. However, after requesting location permissions, then requesting location, if I open Location Settings I can see that there is an entry under "Recent Location Requests" which would indicate that the application request for location was successful, but that the OS did not return a mock location back to the application - I will put this down to a bug in the Android emulator.

I've made a screen capture video demonstrating the above: [http://ge.tt/api/1/files/5W2PMqS2/0/blob?download](http://ge.tt/api/1/files/5W2PMqS2/0/blob?download)

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by NicoJuicy** [comment]
Sorry for the late reply, didn't noticed it in my emails. But i will check it out. 
Definatly a big thanks for checking it out!

**Comment by sugir93** [comment]
hi am facing the same problem in the gps...

can any one help me out.... 


thi\e bellow url is also not working
http://w812091.blob3.ge.tt/streams/5W2PMqS2/demo.wmv?sig=-VMi54sPQL9dcOUOjWoPeoScK2tnjaz0KZo&type=download

**Comment by dpa99c** [comment]
@sugir93 It's not clear what "the same problem in the gps" is and link you provided is invalid/broken.

Please provide useful information such as a detailed description, details of the build environment (local, Phonegap Build, etc.), runtime environment (Android version, device make/model), etc.

**Comment by sugir93** [comment]
message: application does not have sufficient geolocation permissions.
the above message am getting when am trying to access the location in high accuracy mode

**Comment by sugir93** [comment]
@dpa99c

**Comment by dpa99c** [comment]
@sugir93 if you use a recent version of [cordova-plugin-geolocation](https://github.com/apache/cordova-plugin-geolocation) it will request this permission for you.

To do so with this plugin use [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization), making sure you've [added appropriate permissions to your manifest](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions).

Without more details (e.g. code sample illustrating your usage), i cannot be more specific.

**Comment by sugir93** [comment]
@dpa99c 
yeah added all the codes in the manifest and in config aswell.
only this is happening in android 6.0 rest all its working.
the requestLocationAuthorization() is trowing undefined in all the devices, so i removed this function from my code.
and am using "cordova-plugin-request-location-accuracy" plugin aswell :-)

plz help me to fix this issue

**Comment by dpa99c** [comment]
>the requestLocationAuthorization() is trowing undefined in all the devices, so i removed this function from my code.

This function works fine - see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for an [example of usage on Android](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L68)

>plz help me to fix this issue

The only way I can help you further is if you paste all your relevant code somewhere I can see it, otherwise I'm just guessing.

**Comment by sugir93** [comment]
@dpa99c 
am using diagnostic 22 plugin... 
will it be available in that version?

**Comment by dpa99c** [comment]
>am using diagnostic 22 plugin... 
will it be available in that version?

Does this mean you're using [`cordova.plugins.diagnostic.api-22`](https://www.npmjs.com/package/cordova.plugins.diagnostic.api-22)? Please be explicitly clear with your terminology.

If so, this branch of the plugin is intended for use with API 22 (Android 5.1) and below. Hence it does not support Android 6.0 runtime permissions so will not define functions such as `requestLocationAuthorization()` for Android. You should only use this if you are building against API 22 or below.

If you wish to support Android 6.0 runtime permissions, you should use the master branch of the plugin which is available on NPM as `cordova.plugins.diagnostic`, and make sure you are building against API 23.

**Comment by sugir93** [comment]
@dpa99c  cordova.plugins.diagnostic this plugin will support  with the older devices then?


thanks for your support dpa99c

**Comment by dpa99c** [comment]
Yes, cordova.plugins.diagnostic will work fine on devices running older versions of Android. 

Like any Android API, API 23 (Android 6.0) is backwardly compatible to devices running older versions. When you build your app containing cordova.plugins.diagnostic against API 23, the APK will still work fine on older versions of Android. The only difference is that any runtime permissions will automatically be returned as GRANTED since on older versions of Android, all permissions are granted at installation time.

**Comment by sugir93** [comment]
thanks dpa99c (y)

**Comment by sugir93** [comment]
@dpa99c 
its working f9 nw :-)

Thank you very much for your help :+1:
