### ISSUE TITLE
how to enable location progmatically in ionic 

### ISSUE THREAD

**Issue by manojkumar7488** [dpa99c/cordova-diagnostic-plugin#190]
i want to enable location  when app is start .on startup page i want to enable location if user not  get access

**Comment by dpa99c** [comment]
Please read the [documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) and [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for instructions on how to use this plugin.
