### ISSUE TITLE
[FEATURE] Add support for WRITE_SETTINGS PERMISSION

### ISSUE THREAD

**Issue by mugenyi** [dpa99c/cordova-diagnostic-plugin#192]
My cordova app requires a write_settings permissions how can i do it with this plugin

**Comment by dpa99c** [comment]
This plugin doesn't currently support requesting that permission, although it could theoretically be extended to do so.

This feature will go into the requested. enhancement backlog.

Details of what's required [are here](http://stackoverflow.com/questions/32083410/cant-get-write-settings-permission) if you'd like to fork the plugin and implement this yourself for a more immediate solution.

**Comment by rolinger** [comment]
@mugenyi - write-settings for what?  My app does local file storage, create/read, etc using standard cordova file read/writes with `FileReader()` and `fileEntry.createWriter(...)`

**Comment by dpa99c** [comment]
@rolinger [WRITE_SETTINGS](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS) enables reading/writing of System Settings. However, unlike other run-time permissions, it can only be granted by invoking an [ACTION_MANAGE_WRITE_SETTINGS](https://developer.android.com/reference/android/provider/Settings.html#ACTION_MANAGE_WRITE_SETTINGS) intent. 

Hence this is an enhancement of existing functionality, although an edge case as not many apps need to/should modify system settings, so this is relatively low on my priority list.

**Comment by matrixreal** [comment]
How did ou guys manage this ?
what's the js call to request the WRITE_SETTINGS-permissions using this plugin ?
Thanks
