### ISSUE TITLE
Always getting DENIED_ALWAYS when call requestLocationAuthorization

### ISSUE THREAD

**Issue by RaiTamarindo** [dpa99c/cordova-diagnostic-plugin#193]
I tested all possibilities when the app requests permission: grant, deny and deny and not ask again. In all of them the result is always DENIED_ALWAYS.

**Comment by dpa99c** [comment]
Check you have added the relevant `<uses-permission/>`elements to your `AndroidManifest.xml` - see [documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions).

I also suggest looking at the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which illustrates/validates plugin functionality, [including requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L113).
Try build and running it to confirm whether or not you get the same result.

**Comment by RaiTamarindo** [comment]
You're right! I run the example project and the error did not appear. I checked the permissions as you recommended, but they were all already there. I have not found what I'm doing wrong, but thank you anyway.
Code:
```
var deferred = $q.defer();

cordova.plugins.diagnostic
  .requestLocationAuthorization(function(status)
  {
    console.log('[devicePermissionService] status: '+ status);
    deferred.resolve();
  }, function(error)
  {
    deferred.reject(error);
  }, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS);
```
