### ISSUE TITLE
[FEATURE] Get current Battery mode on iOS

### ISSUE THREAD

**Issue by pooi-pooi** [dpa99c/cordova-diagnostic-plugin#194]
Hello guys, can I get the Battery/Power Mode on iOS?
I need to notify the user when he turn **Low Power Mode** on.

**Comment by dpa99c** [comment]
This plugin doesn't currently offer such functionality but it seems from the [Apple documentation](https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/LowPowerMode.html) that it is possible to do programmatically.

Added to requested enhancements backlog.
