### ISSUE TITLE
TypeError: Cannot read property 'GRANTED' of undefined

### ISSUE THREAD

**Issue by sugandhaverma** [dpa99c/cordova-diagnostic-plugin#195]
when i run the app on my device its showing error Here

![screen shot 2017-04-17 at 12 09 00 pm](https://cloud.githubusercontent.com/assets/21327501/25086129/76a166ec-2383-11e7-8f62-f13896237e5f.png)

Here is my config.xml file

![screen shot 2017-04-17 at 3 34 18 pm](https://cloud.githubusercontent.com/assets/21327501/25086142/8863f80e-2383-11e7-9218-a5cb9f8047de.png)

The actual problem is when i start my app and select the option after option get selected then in listing its start blinking and showing error. I attached the screenshot.
Pls help me out

**Comment by dpa99c** [comment]
The screenshots of the config.xml and 401 error are not at all relevant to the error implied by the issue title.

If the plugin constants are undefined, most likely the plugin is not installed or you are attempting to reference the plugin before the `deviceready` event has fired: Cordova dynamically loads the JS components of plugins at runtime.

Please see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for an illustrated example of how to use the plugin.

**Comment by sugandhaverma** [comment]
I already added and define all the plugins after taking permission for location its start blinking. there is some error showing like "Uncaught TypeError: cannot read property 'GRANTED' of undefined" in diagnostic cordova plugin.

What i have to do .how to solve this error.?

**Comment by dpa99c** [comment]
The error message `"Uncaught TypeError: cannot read property 'GRANTED' of undefined"` is not enough information to diagnose your issue. You need to post more information: the exact Javascript error (including stacktrace) and your code which is calling the plugin and raising the error.

And as I've said, you can look at the example project which clearly demonstrates how to use call the functionality provided by the plugin.

**Comment by sugandhaverma** [comment]
can u share your skype id so that u can help me out with the error. If possible

**Comment by dpa99c** [comment]
> can u share your skype id so that u can help me out with the error.

I've outlined what is required from you above - the full error trace and the code which is calling the plugin and raising the error. I don't have time to teach you to debug your app. 

Please post the requested information or this issue will be closed.

**Comment by dpa99c** [comment]
Closed due to no response from OP
