### ISSUE TITLE
build android failed when add cordova.plugins.diagnostic plugin

### ISSUE THREAD

**Issue by reza-mazarlou** [dpa99c/cordova-diagnostic-plugin#196]
I try to create ionic 2 app with below steps:

1-` npm install -g cordova`

2- `npm install -g ionic`

3-` npm install -g typescript`

4-` ionic start sampleApp tutorial --v2`

for serve and see in browser use this command :

`ionic serve `
for build android apk file download jdk 8 and android sdk manager and install all api and set ANDROID-HOME and after use this command :

`ionic platform add android`

`ionic build android`
every things is ok and work very well but I want give GPS state and for this reason add `cordova.plugins.diagnostic` with this command :

`ionic plugin add cordova.plugins.diagnostic`

`npm install --save @ionic-native/diagnostic`
but after add diagnostic plugin and run ionic build android console give me error and build failed .I search in google and find this page :

Ionic android build fails, no matches found

and this pages :

https://forum.ionicframework.com/t/build-failed-android/38071/6

but I don't know how to solve this problem

my project and system info:

```
ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v6.10.0
Xcode version: Not installed
```
```

<preference name="android-minSdkVersion" value="19" />
<preference name="android-targetSdkVersion" value="23" />
```

**Comment by dpa99c** [comment]
Please post the full console output including the build error message - what you have posted is not sufficient to diagnose a problem.

However, it's an Android build failure is most likely because you have missing/outdated components from the Android SDK which are required by the plugin - see [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#building-for-android) for detailed requirements.

**Comment by reza-mazarlou** [comment]
console give me this error :
```
Error: cmd: Command failed with exit code 1 Error output: 
FAILURE: Build failed with an exception. 

* What went wrong: 
A problem occurred configuring root project 'android'. 
> java.lang.NullPointerException (no error message) 

* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

but when android platform change 
```
ionic platform remove android 
ionic platform add android@5
```

and change diagnostic plugin to api-22 :

`ionic plugin add  cordova.plugins.diagnostic.api-22 --save`

build is successfully

my min-sdk of project is 19 and target-sdk id 25 .
How to use diagnostic plugin with 19-25 Api range?
if I use android platform 5 and cordova.plugins.diagnostic.api-22 them is worked for api 24 or 25?

**Comment by dpa99c** [comment]
The `cordova-android` version explicitly sets the *compile SDK* version and you cannot override this. So to target API 23+, you must use `cordova-android@6+`. Unless you have a very good reason, there's no reason to use `cordova-android@5`.

So your choices are:

- Use `cordova-android@6` (`ionic platform add android@latest`) and the main branch of this plugin (`ionic plugin add cordova.plugins.diagnostic`) to compile for API 23+

- Or use `cordova-android@5` (`ionic platform add android@5`) and the legacy branch of this plugin (`ionic plugin add cordova.plugins.diagnostic.api-22`) to compile for API 22.

I strongly recommend the first option. Read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#building-for-android-runtime-permissions) for more details.

**Comment by reza-mazarlou** [comment]
I try with below steps :
1-` ionic platform remove android`
2-` ionic plugin remove cordova.plugins.diagnostic.api-22  --save`

3-` ionic platform add android@latest`
4- `ionic plugin add cordova.plugins.diagnostic --save`

but when run `ionic build android` console give me this error :

```
Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio
```

**Comment by bharathirajatut** [comment]
Hi,
I also had the same problem, while trying to check the location enabled or not. I solved by adding the cordova gradle support plugin.

**Solution:**
`
cordova plugin add cordova-android-support-gradle-release
`
Please execute the above code on your project. It will work.

**Comment by cagb80** [comment]
@bharathirajatut TY
