### ISSUE TITLE
diagnostic is undefined

### ISSUE THREAD

**Issue by jabas06** [dpa99c/cordova-diagnostic-plugin#2]
If I access the plugin thought cordova.plugins.diagnostic I get an error because is undefined.

I solved it accessing the plugin like this -> window.Diagnostic (with a capital D)

**Comment by dpa99c** [comment]
If the plugin is installed correctly into a Cordova 3.0+ project, the `cordova.plugins.diagnostic` object is created by the cordova plugin mechanism; you can see this in the plugin's [plugin.xml](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml):

    <clobbers target="cordova.plugins.diagnostic" />

It can then be referenced as `cordova.plugins.diagnostic` from the app; see the [example project source code](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js)

When the plugin is installed via `cordova plugin add cordova-diagnostic-plugin`, cordova will wrap the contents of the Javascript module to expose the object above. For example, for the Android platform you should end up with the file `platforms/android/assets/www/plugins/cordova.plugins.diagnostic/www/android/diagnostic.js`

and it should look like:

    cordova.define("cordova.plugins.diagnostic.Diagnostic", function(require, exports, module) {
      var Diagnostic = function() {
      };
      ...
      module.exports = new Diagnostic();
    });

If `cordova.plugins.diagnostic` is not defined but `window.Diagnostic` is, it means the plugin hasn't been installed correctly so the `cordova.define` wrapper is missing and `Diagnostic` is being declared as a variable in global scope.

This is not an issue with the plugin, hence closing the issue.
