### ISSUE TITLE
getLocationAuthorizationStatus returns wrong value after manually disabling permissions on Android 6

### ISSUE THREAD

**Issue by ReyRod** [dpa99c/cordova-diagnostic-plugin#200]
Hi, great plugin guys! 

i'm developing an ionic app and i've started testing a new module in an Android 6 smartphone. In this module i present a list of offices ordered by proximity if location is available and alphabetically if not.

Trouble happens when i evaluate if location is available with a flow using these functions: isLocationEnabled, getLocationAuthorizationStatus and requestLocationAuthorization

At first startup of the App, getLocationAuthorizationStatus function warn me permissions hasn't been requested

![screenshot_1](https://cloud.githubusercontent.com/assets/5686144/25411242/a43a9364-29e9-11e7-8d8a-211bee19e3e5.png)

So i present the user an option to grant permissions

![screenshot_20170425-160732](https://cloud.githubusercontent.com/assets/5686144/25411325/2083b144-29ea-11e7-9af2-2d1641d75056.png)

If the user grant permissions the list is ordered by proximity and by default if not.

![screenshot_2](https://cloud.githubusercontent.com/assets/5686144/25411393/75cd2db0-29ea-11e7-93bb-ad269cdea3cc.png)

Then if i manually disable permissions in the security settings of Android

![screenshot_20170425-161841](https://cloud.githubusercontent.com/assets/5686144/25411413/9063e9fc-29ea-11e7-851c-73e8987e8fac.png)

Consecutive startups shows permission is GRANTED and throws an exception while attempting to get the location.

![screenshot_3](https://cloud.githubusercontent.com/assets/5686144/25411457/c87276c4-29ea-11e7-8d3a-55fe005a01c2.png)

![screenshot_20170425-162102](https://cloud.githubusercontent.com/assets/5686144/25411509/11a3c8e8-29eb-11e7-94ff-b10842e4d8ac.png)

Is this a bug or i should not rely on getLocationAuthorizationStatus and ask permissions every time?

PD. Sorry for my English.

**Comment by dpa99c** [comment]
I'm unable to reproduce this issue when testing with the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which correctly updates the location authorization status to unauthorized [on calling `getLocationAuthorizationStatus()`](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L383) if the user revokes the permission via Settings.

Please build and test with the example project to see if you can reproduce the issue. This will eliminate any possible bugs in your implementation.

**Comment by ReyRod** [comment]
I've build the example project and tested in a LG Optimus G smartphone with Android 6.0.1, same behaviour happens, it's not unable to obtain location after revoking permissions via settings

![screenshot_20170426-091641](https://cloud.githubusercontent.com/assets/5686144/25436754/4ab67f28-2a62-11e7-8b7d-3555d4536d02.png)

![screenshot_20170426-091652](https://cloud.githubusercontent.com/assets/5686144/25436759/4fb74cfa-2a62-11e7-8c6c-c1ecbf1c1835.png)

![screenshot_20170426-091755](https://cloud.githubusercontent.com/assets/5686144/25436767/55adc8fa-2a62-11e7-8754-c98060ec2a67.png)

![screenshot_20170426-091706](https://cloud.githubusercontent.com/assets/5686144/25436780/5e2c1e46-2a62-11e7-94a5-e82ad686cafe.png)

![screenshot_20170426-084336](https://cloud.githubusercontent.com/assets/5686144/25436828/76a6d1fa-2a62-11e7-9c51-34ab0c4491d7.png)

![screenshot_20170426-091700](https://cloud.githubusercontent.com/assets/5686144/25436875/981b5c48-2a62-11e7-898a-e5cefbf2668f.png)

![screenshot_20170426-091842](https://cloud.githubusercontent.com/assets/5686144/25436886/9ca4ad14-2a62-11e7-8ad0-3f4d7a8348c7.png)

perhaps it's a hardware/rom malfunction, i'll test on another smartphone also i'll leave my code as it is and i'll wait feedback on this case because i need to cover android 6 version

**Comment by dpa99c** [comment]
Very strange, maybe that Android build is buggy, because I don't get that behaviour on my test devices: [Here's a screencast](http://ge.tt/3g6Q1rj2) from a Samsung Galaxy Tab A running Android 6.0.1.
Also tested on Samsung Galaxy S6 flashed with Android 7.1.1 and it works the same as this.

**Comment by ReyRod** [comment]
Thanks for the feedback, i see it's no related to the plugin but to the android build itself, i'll continue the development, you can close the issue.
