### ISSUE TITLE
Bluetooth in iOS 10

### ISSUE THREAD

**Issue by juancafe4** [dpa99c/cordova-diagnostic-plugin#207]
I have some issues running getBluetoothState. I get status UNKNOWN.
I also tried to run isBluetoothAvaliable and it says  WARN: Install the Diagnostic plugin: 'ionic plugin add cordova.plugins.diagnostic'

I think I have to do something in the plist in xCode
Any suggestions?

Thanks

**Comment by dpa99c** [comment]
> WARN: Install the Diagnostic plugin: 'ionic plugin add cordova.plugins.diagnostic'

This message is generated by [Ionic Native](https://github.com/driftyco/ionic-native) when using the [Typescript wrapper for this plugin]([Ionic Native](https://github.com/driftyco/ionic-native/blob/master/src/%40ionic-native/plugins/diagnostic/index.ts) when Ionic Native determines the plugin itself is not installed in the project. Consequently, this has nothing to do with this plugin itself and is related to Ionic Native.

> I have some issues running getBluetoothState. I get status UNKNOWN.

This could happen if you run the containing app inside an iOS Simulator where no Bluetooth hardware is present, or it's possible the Ionic Native wrapper could return this result if it's unable to find the plugin in the project. See the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin) for a working reference how to use the plugin. You can also take a look at the [Ionic example project](https://github.com/dpa99c/cordova-diagnostic-plugin-ionic2-example) - note: this is a work in progress.

**Comment by dpa99c** [comment]
Closed due to no response from OP
