### ISSUE TITLE
requestCameraAuthorization should not request EXTERNAL_STORAGE (2)

### ISSUE THREAD

**Issue by pom421** [dpa99c/cordova-diagnostic-plugin#209]
Hello,

I can't reopen the #178 issue so i open a new one. 

I can't make things go as it is expected, that is to say to ignore the EXTERNAL_STORAGE permission when I call requestCameraAuthorization. I use false for the last arg but my app still asks 2 (permissions camera + external storage). 

May I do something wrong or is it a bug? 

My code is : 

```
app.scanOnPermission = function() {
	cordova.plugins.diagnostic.getCameraAuthorizationStatus(function(status){
		if (status === cordova.plugins.diagnostic.permissionStatus.GRANTED) {
			cordova.plugins.barcodeScanner.scan(app.authent_successCB, app.errorCB);
		} else if (status === cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS) {
			navigator.notification.alert(app.messages.android_pb_permission_camera);
		} else {
			// cas NOT_REQUESTED ou DENIED
			cordova.plugins.diagnostic.requestCameraAuthorization(function(status) {
				if (status === cordova.plugins.diagnostic.permissionStatus.GRANTED) {
					app.scanOnPermission();
				} else {
          navigator.notification.alert(app.messages.android_pb_permission_camera);	
				}
			}, function(err) { 
				console.log('err',err); 
				app.displayPermissionsDialog('erreur' + err);
			}, false)
		}
	}, function(error){
		console.error("The following error occurred: "+error);
	}, false);  
};
```

I have don't define any permission in config.xml because the others plugins doesen't seem to need it. 

After a 'cordova run android', my generated AndroiManifest.xml includes :

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
```

NB : I use Cordova 7.0.1 and cordova.plugins.diagnostic 3.6.2. My device is on Android 6.0.1.

**Comment by dpa99c** [comment]
Looks like a bug that affects the legacy call signature `cordova.plugins.diagnostic.requestCameraAuthorization(successCallback, errorCallback, externalStorage)`

The other call signatures work as expected:

    cordova.plugins.diagnostic.requestCameraAuthorization(params); 
    cordova.plugins.diagnostic.requestCameraAuthorization(successCallback, errorCallback, params) 

I'll fix and push out in a patch release.

**Comment by dpa99c** [comment]
Fix published in `cordova.plugins.diagnostic@3.6.4`.

**Comment by pom421** [comment]
It works! Thanks Dave!
