### ISSUE TITLE
Nice to have - a better NPM package / plugin name

### ISSUE THREAD

**Issue by zarko-tg** [dpa99c/cordova-diagnostic-plugin#21]
If I may recommend a slight twist to the current NPM package / plugin name cordova.plugins.diagnostic.
How about **cordova-plugin-diagnostics**?

Most (and the more popular) Cordova and third-party plugin names start with "cordova-plugin-". Seems to be the standard these days.

**Comment by dpa99c** [comment]
The plugin name is historical - it pre-dates the npm switchover. Given that this plugin is now quite widely used, and there's no easy way to rename an existing cordova plugin registered in npm, changing the ID now would simply lead to confusion with no actual benefit other than following what is just a naming convention.

**Comment by zarko-tg** [comment]
Ok, cheers.
