### ISSUE TITLE
Notification always false

### ISSUE THREAD

**Issue by shrijan** [dpa99c/cordova-diagnostic-plugin#210]
If Notification is disallowed during the app installation and turn on later then it always return false.

But if notification is allowed initially than it works perfectly.

Thanks

**Comment by dpa99c** [comment]
Hi, I'm not able to reproduce this behaviour using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) testing on an iPad with iOS 10.3.1. After pressing "Don't Allow" for notification permission at install time, then manually enabling access via settings, the example app correctly changes "Remote notifications enabled?" from "DISABLED" to "ENABLED" - see [this screencast](http://ge.tt/8Na1UQk2).

Please can you try either building and running the example project to repeat the test and confirm whether you can still reproduce the issue, or provide an example Cordova project which reproduces the problem.

**Comment by dpa99c** [comment]
Closed due to no response from OP
