### ISSUE TITLE
Error in cordova-diagnostic-plugin-example

### ISSUE THREAD

**Issue by jrlandau** [dpa99c/cordova-diagnostic-plugin#213]
The error is at #request-external-sd-details and #write-external-sd-file. Same error in both places.  Apparently "cordova.file" is undefined

index.js:280 Uncaught (in promise) TypeError: Cannot set property 'externalSdCardDirectory' of undefined
    at file:///android_asset/www/js/index.js:280:58
    at Array.forEach (native)
    at file:///android_asset/www/js/index.js:272:21
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:293:58)
    at processMessage (file:///android_asset/www/cordova.js:1119:17)
    at processMessages (file:///android_asset/www/cordova.js:1142:9)

**Comment by dpa99c** [comment]
> "cordova.file" is undefined

This indicates `cordova-plugin-file` is missing from the project and can be rectified with `cordova plugin add cordova-plugin-file`. However, I'll add it to the `config.xml` as it should be getting installed by default.

**Comment by dpa99c** [comment]
Fixed by commit [43d9d5437c5d9b403bdc744c27989ef62d452905](https://github.com/dpa99c/cordova-diagnostic-plugin-example/commit/43d9d5437c5d9b403bdc744c27989ef62d452905)

**Comment by jrlandau** [comment]
That plugin is a great contribution.  Many thanks.
