### ISSUE TITLE
Cordova ready not fired

### ISSUE THREAD

**Issue by pke** [dpa99c/cordova-diagnostic-plugin#215]
After updating cordova to 6.5.0 and using cordova-android 6.2.3 the app stalls in the splashscreen as it never receives the `deviceready` event:

```
deviceready has not fired after 5 seconds.
cordova.js:1216 Channel not fired: onCordovaInfoReady
cordova.js:1216 Channel not fired: onDeviceNameReady
```

Removing this plugin makes the app work again.

**Comment by dpa99c** [comment]
The [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) seems to build and run fine using cordova-diagnostic-plugin@3.6.5, cordova@7.0.1 and cordova-android@6.2.3.

Can you try building and running it in your build env?

**Comment by pke** [comment]
Thanks for the swift response Dave! We will try that later.

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by pke** [comment]
Will check today

**Comment by pke** [comment]
Will check today

**Comment by pke** [comment]
With Cordova@7.x it works.

**Comment by pke** [comment]
@dpa99c Problem is we cannot use cordova 7.x because it uses npm to fetch plugins now and puts them in the package file, which does not work in our whitelabel setup.
Do you have any other idea, why it might be stuck with 6.5.0 cordova?

**Comment by dpa99c** [comment]
@pke 
> Do you have any other idea, why it might be stuck with 6.5.0 cordova?

No, this doesn't make sense to me since `cordova` is just the CLI that assembles the native project, and it's `cordova-android` that actually contains the app code. Does this happen when building the example project with `cordova@6.5.0`?

> Problem is we cannot use cordova 7.x because it uses npm to fetch plugins now and puts them in the package file, which does not work in our whitelabel setup.

Just a heads up that you might want to sort this out because [cordova@8 will remove support for the non-npm installation method](http://disq.us/p/1im8sx7).

**Comment by pke** [comment]
Hmmm, the example project runs with cordova-android@6.2.3

Might be another plugin that is preventing yours from receiving the ready event then.

**Comment by kfiryahalom** [comment]
have the same issue with cordova 6.5.0
