### ISSUE TITLE
How to get boolean from (cordova.plugins.diagnostic.isLocationAvailable) instead of callbacks

### ISSUE THREAD

**Issue by aubrey-fowler** [dpa99c/cordova-diagnostic-plugin#221]
In the code I am writing it will be helpful for me to be able to get a simple true/false Boolean instead of having to manage the callbacks.

cordova.plugins.diagnostic.isLocationAvailable(onLocationAvailable, onLocationError);

I am writing an angularJs app and because this is in callback format it's disrupting my $scope/$digest cycle.

**Comment by dpa99c** [comment]
Cordova plugins are asynchronous by nature of interaction between the Javascript and native code, so it is not possible to return synchronous values when the operation is asynchronous, hence callbacks are needed to deliver the asynchronous result. 

You could use Promises to abstract away the async nature of the interface, as the [Ionic Native Typescript wrapper](https://ionicframework.com/docs/native/diagnostic/) does.
