### ISSUE TITLE
AUTHORIZED_WHEN_IN_USE instead of GRANTED_WHEN_IN_USE in ios

### ISSUE THREAD

**Issue by ergurjeet** [dpa99c/cordova-diagnostic-plugin#222]
Hi,
It returns AUTHORIZED_WHEN_IN_USE instead of GRANTED_WHEN_IN_USE in ios. Do you accept pull requests for these kind of changes?

Thanks,

**Comment by dpa99c** [comment]
This is a quirk of making it work consistently cross platform: natively Android refers to [granting permission](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L1030) and iOS refers to [authorizing permission](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L875) - the native iOS constant is actually `kCLAuthorizationStatusAuthorizedWhenInUse`.

However, to maintain cross-platform consistency, i.e. so the same Javascript constants can be used on both platform, iOS ["authorized" constants are mapped to "GRANTED"](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L47) and therefore "authorized_when_in_use" is mapped to "GRANTED_WHEN_IN_USE" for consistency.

This means you can write `if(status === cordova.plugins.diagnostic.GRANTED)` and it will work on both platforms, but the value of `cordova.plugins.diagnostic.GRANTED` on iOS is "authorised" and on Android it's "granted." Hence, the value of `cordova.plugins.diagnostic.GRANTED_WHEN_IN_USE` on iOS is "authorized_when_in_use".
