### ISSUE TITLE
check ios notification requested status

### ISSUE THREAD

**Issue by josh-m-sharpe** [dpa99c/cordova-diagnostic-plugin#226]
Similar to how getLocationAuthorizationStatus returns a "NOT REQUESTED" status if the perm hasn't been prompted yet,  is there a way to detect if (remote) notification perms have been previously requested?  From what I can tell - isRemoteNotificationsEnabled() just returns true/false and getRemoteNotificationTypes() doesn't change before/after perms have been granted. Is it possible to detect remote permissions status?

**Comment by dpa99c** [comment]
This is currently not exposed, but can probably be added pretty easily: just need to return the [UNAuthorizationStatus](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus?language=objc) value.

**Comment by josh-m-sharpe** [comment]
This is my first ever attempt at obj-c...  Here's a branch, but it doesn't compile. I was hoping copy/pasting getLocationAuthorizationStatus and changing things would be all thats necessary, but alas... no luck. Any pointers?

https://github.com/dpa99c/cordova-diagnostic-plugin/compare/master...josh-m-sharpe:getNotificationAuthorizationStatus?expand=1&w=1

**Comment by dpa99c** [comment]
I'd already implemented this, just not got around to publishing until now: https://github.com/dpa99c/cordova-diagnostic-plugin#getremotenotificationsauthorizationstatus

It's available in `cordova.plugins.diagnostic@3.6.7`
