### ISSUE TITLE
Compatibility with ios 11.

### ISSUE THREAD

**Issue by 1nfinite** [dpa99c/cordova-diagnostic-plugin#227]
Would be glad to know if this plugin is currently compatible with ios 11. 
I heavily used this plugin on my mobile app, especially the location part and i afraid that it will break on upcoming iOS 11 release.

```
getLocationAuthorizedStatus
requestLocationAuthorization
switchToLocationSettings
```

**Comment by dpa99c** [comment]
I've tested this plugin with iOS 11 Beta and everything seems to work OK. 
The only tweak you may need to made with regard to location is if you use background geolocation, you'll need to add the `NSLocationAlwaysAndWhenInUseUsageDescription` key to your `.plist` ([see here](https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/)), but to do so is not the direct responsibility of this plugin. However, I'll add a placeholder key to the `plugin.xml` of this plugin to make it clear that this key is now required as of iOS 11.

**Comment by dpa99c** [comment]
Commit bc0cd8b67a6c285e469ededfc3e6e1f8401fa4ab adds the placeholder key
