### ISSUE TITLE
TypeError: cordova.plugins.diagnostic.requestLocationAuthorization is not a function

### ISSUE THREAD

**Issue by jatinbphp** [dpa99c/cordova-diagnostic-plugin#228]
After installing package with in ionic, i write below code in my controller, but is giving TypeError: cordova.plugins.diagnostic.requestLocationAuthorization is not a function
 error.
` document.addEventListener('deviceready', function() {
            console.log("REQUESTING....")
            cordova.plugins.diagnostic.requestLocationAuthorization(function(status) {
                switch (status) {
                    case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                        console.log("Permission not requested");
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                        console.log("Permission granted");
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.DENIED:
                        console.log("Permission denied");
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                        console.log("Permission permanently denied");
                        break;
                }
            }, function(error) {
                console.error(error);
            });
        });`
Any idea how to fix this ?

**Comment by dpa99c** [comment]
Please give more information such as test platform: Android or iOS?

Also see/try building+running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-) which illustrates/validates all plugin API functions [including this one](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L118).

**Comment by jatinbphp** [comment]
Hello,
I am using this for android.
I have used cordova plugin add cordova.plugins.diagnostic.api-22 to install it.
cordova.plugins.diagnostic.isLocationEnabled(successCallback, errorCallback); is working well, but i want to ask location permission.

**Comment by dpa99c** [comment]
> I have used cordova plugin add cordova.plugins.diagnostic.api-22 to install it.

That branch is deprecated and no longer maintained and therefore does not contain all the functionality of the master branch. Please use the master version of the plugin in order to obtain this functionality:

    cordova plugin add cordova.plugins.diagnostic

**Comment by jatinbphp** [comment]
Okay, Thanks. will update you here once i done with that.

**Comment by jatinbphp** [comment]
i am getting below error in that command now, how can i remove previous package ?
Total time: 3.503 secs
Error during processing of action! Attempting to revert...
Failed to install 'cordova.plugins.diagnostic': CordovaError: Uh oh!
"/home/empowrdev/ionic/platforms/android/src/cordova/plugins/Diagnostic.java" already exists!
    at copyNewFile (/home/empowrdev/ionic/platforms/android/cordova/lib/pluginHandlers.js:248:15)
    at install (/home/empowrdev/ionic/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at Object.process (/home/empowrdev/ionic/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/empowrdev/ionic/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/home/empowrdev/ionic/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /home/empowrdev/ionic/platforms/android/cordova/Api.js:254:18
    at _fulfilled (/home/empowrdev/ionic/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/empowrdev/ionic/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/empowrdev/ionic/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /home/empowrdev/ionic/platforms/android/cordova/node_modules/q/q.js:624:44
Error: Uh oh!
"/home/empowrdev/ionic/platforms/android/src/cordova/plugins/Diagnostic.java" already exists!

**Comment by jatinbphp** [comment]
Thank you very much.......it is working.. you save my day.

**Comment by AndreVicenteWeb** [comment]
I already did it and continue receiving 

```
Native:  tried calling Diagnostic.isLocationAuthorized, but the Diagnostic plugin is not installed.
Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic
```

**Comment by AndreVicenteWeb** [comment]
Forget, I just put in `this.platform.ready().then(() => {` and works

**Comment by worktoday** [comment]
TypeError: cordova.plugins.diagnostic.switchToLocationSettings is not a function
above is what i am getting.

platform ios
ionic v1
