### ISSUE TITLE
Cannot add this Plugin anymore

### ISSUE THREAD

**Issue by dmastag** [dpa99c/cordova-diagnostic-plugin#229]
Today I am getting this error when pulling the plugin.
Any idea why ?

```
> cordova plugin add cordova.plugins.diagnostic.api-22 --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add cordova.plugins.diagnostic.api-22 --save (exit code 1):

Error: Cannot find plugin.xml for plugin "cordova.plugins.diagnostic.api-22". Please try adding it again.
```

**Comment by dpa99c** [comment]
The API 22 branch has been deprecated for a while and today was removed to avoid confusion and anomalous bug reports such as #228.

It was no longer feasible to maintain it in parallel with the master branch, which has moved on significantly to support Android API 26 (and iOS 11). 

Please move to using the master branch version of the plugin:

    cordova plugin rm cordova.plugins.diagnostic.api-22
    cordova plugin add cordova.plugins.diagnostic

**Comment by dmastag** [comment]
Ok noted.

The reason I need this is that I am still building for API 19 for my App and I can't build as per https://github.com/dpa99c/cordova-diagnostic-plugin/issues/228 so I am going to use

`cordova plugin add cordova.plugins.diagnostic.api-22@2.3.10-api-22`

For older builds
