### ISSUE TITLE
requestLocationAuthorization - Can't find variable: error

### ISSUE THREAD

**Issue by meeeu** [dpa99c/cordova-diagnostic-plugin#23]
When using requestLocationAuthorization in iOS with and without passing in "when_in_use"

cordova.plugins.diagnostic.requestLocationAuthorization(function(){
    console.log("Successfully requested location authorization always");
}, function(error){
    console.error(error);
}, "when_in_use");

Error in Error callbackId: Diagnostic786250294 : ReferenceError: Can't find variable: error

**Comment by dpa99c** [comment]
I'm not able to reproduce this - `requestLocationAuthorization ` is working fine [when used](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L42) in the example [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example). Tested on iOS 7.0, 8.0, 9.1

So first I'd suggest to try building+running the example project to confirm that the plugin works OK in your build environment. Then I'd suggest using Safari to remote debug the WebView in your app and insert a breakpoint on the `console.error(error);` line to see if error is indeed undefined. If so, run the app via Xcode and see if there's any error in the Objective-C log output.

**Comment by meeeu** [comment]
Figure out the problem
For iOS 8 and above, your app must have a value for NSLocationAlwaysUsageDescription in its Info.plist

Adding
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app will now only track your location when the screen is on and the app is displayed.</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>This app requires constant access to your location in order to track your position, even when the screen is off.</string>

fixed it
