### ISSUE TITLE
iOS - Diagnostic plugin is not installed

### ISSUE THREAD

**Issue by ruben82** [dpa99c/cordova-diagnostic-plugin#233]
Hi,
I'm trying to use this plugin on a ionic 3 ios app.
On android all works properly but on ios I receive this message 

 

> Native: tried calling Diagnostic.getLocationMode, but the Diagnostic plugin is not installed.
Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic'
plugin_not_installed

 when I try to execute this function.

> sync getLocationStatus() {
    var isEnabled = false;
    await this.diagnostic.getLocationMode()
      .then((state) => {
        if (state == this.diagnostic.locationMode.LOCATION_OFF) {
          this.toastProvider.showGPSError();
        } else {
          isEnabled = true;
        }
      }).catch(e => {
        console.error(e);
        this.toastProvider.showGPSError();
      });
    return isEnabled;
  }

My ionic info are 

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.2
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v8.1.3
    npm               : 5.1.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

I try to remove and add the platform with no result..

Any ideas please... I'm stuck :-(

**Comment by dpa99c** [comment]
[getLocationMode()](https://github.com/dpa99c/cordova-diagnostic-plugin#getlocationmode) is an [Android only](https://github.com/dpa99c/cordova-diagnostic-plugin#android-only) function - iOS does not have an equivalent.

**Comment by ruben82** [comment]
Sorry. In Ionic documentation is not specified that.
I'm trying to use 

> isLocationEnabled()

for iOS but it returs always false :-(

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationenabled):

> On iOS this returns true if Location Services is switched on.

as can be [seen in the code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L62).

You can see it working correctly by building and running the [example app](https://github.com/dpa99c/cordova-diagnostic-plugin-example)
