### ISSUE TITLE
Adding additional text to permissions pop-up message?

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#234]
Is there anyway to add specific text to the standard text during a permissions request?  I am finding users are saying "no/deny" to certain permissions because they don't feel/believe the app should have access to certain things.  Like Android's `cordova.plugins.diagnostic.permission.READ_PHONE_STATE` - the permission actually asks "Allow APP to make phone calls?"  This is very misleading.  Our app does not make phone calls but our app does have areas where it needs to interface with SMS messaging.  I don't want to add additional popups explaining what the next permission is about - users tire quickly of too many installation popups & permissions.

Thus I am looking for a way to add additional text to the default language of the permission request.  Something like "Our app uses this permission to text message order confirmations..  Allow APP to make phone calls?"  

I have a hunch the answer is no, but I need to ask or find a way of doing this so the users knows what we are asking for yet it doesn't annoy them with too many popups.

**Comment by dpa99c** [comment]
There's no way to customise the text of these permission request dialogs - the are system dialogs so the app has no control over their content. The approach taken by many apps is to precede these request dialogs with a custom dialog which explains why the following system dialog will appear (you can use `cordova-plugin-dialogs`), e.g. (off the top of my head): 

`We need your permission to send/receive SMS messages: Android will ask you to "Allow app to make phone calls" but this is not what we will do! Press Accept if you're happy to agree on Cancel if you're not.`.

**Comment by rolinger** [comment]
Ok...as I thought.  Pop up dialog "This is why we are asking for this permission"....then a second pop-up permission dialog "Allow/Deny the permission".  Not ideal...too many popups, too many explanations and/or questions.  Obviously not a diagnostics-plugin issue, but one would think Android/iPhone would give the ability add on to the native system dialog to minimize the amount of popups the user has to endure.  

Gonna have to rethink this.  thanks though.

**Comment by ljcp** [comment]
you can customise the permissions on iOS from the p.list
