### ISSUE TITLE
iOS 11 runtime warning

### ISSUE THREAD

**Issue by asangadev** [dpa99c/cordova-diagnostic-plugin#238]
Hi there,

I'm getting below warning on Version 9.1 beta (9B37) in iOS 11. Could you please have a look for us?

WARNING:
-[UIApplication isRegisteredForRemoteNotifications] must be used from main thread only

LINE:
BOOL remoteNotificationsEnabled = [UIApplication sharedApplication].isRegisteredForRemoteNotifications;

**Comment by dpa99c** [comment]
This occurring due to the newly introduced [Main Thread Checker](https://developer.apple.com/documentation/code_diagnostics/main_thread_checker) in iOS 11.

Need to go through the code and change any UIKit/UIApplication calls to be made on the main thread.

**Comment by asangadev** [comment]
Thanks for the quick replay mate!

**Comment by asangadev** [comment]
Hey there, do you have an ETA on this todo? Thanks!

**Comment by asangadev** [comment]
Fixes #238
