### ISSUE TITLE
cordova.plugins.diagnostic.getLocationAuthorizationStatus return me "not_determined" on ios 

### ISSUE THREAD

**Issue by eKABIA** [dpa99c/cordova-diagnostic-plugin#246]
since the new OS version 11.0.3 this function return me "not_determined" as status and the requestLocationAuthorisation function didn't work.
thx for help ^^

**Comment by dpa99c** [comment]
I've tested the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on devices running iOS 10.3 and iOS 11.1 Beta and these functions work as expected.

Please build and run the example project to eliminate the possibility of a bug in your code as the cause of the issue.

**Comment by dpa99c** [comment]
See [this screencapture](http://ge.tt/2yOii4n2) which demonstrates the example project working correctly on iOS 11.1 Beta

**Comment by eKABIA** [comment]
hi thx for this fast response i will check it

**Comment by eKABIA** [comment]
It's work, i miss the update of your plugin ....
