### ISSUE TITLE
isMotionRequestOutcomeAvailable returning false on iPhone 5s

### ISSUE THREAD

**Issue by cmlarsen** [dpa99c/cordova-diagnostic-plugin#248]
Phone 5s ME307LL/A
iOS: 10.3.2 (14F89)
Diagnostic plugin version: 3.7.1

Running the example code (below) the result is `false`, running the same code on an iPhone 7, iOS 11 returns `true`.

The expected behavior is that an iPhone 5s should (per docs) return `true`

```
cordova.plugins.diagnostic.isMotionRequestOutcomeAvailable(function(available){
    console.log("Motion tracking authorization request outcome is " + (available ? "available" : "not available") + " on this device");
}, function(error){
    console.error("The following error occurred: "+error);
});
```

**Comment by dpa99c** [comment]
Thanks for reporting this. 

The plugin method `isMotionRequestOutcomeAvailable()` [calls a native iOS function](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic.m#L958) which is [isPedometerEventTrackingAvailable()](https://developer.apple.com/documentation/coremotion/cmpedometer/1778440-ispedometereventtrackingavailabl). Hence if this is returning `false`, then the native Core Motion API is indicating the device does not support motion tracking.

I based the documented list of supported devices on [list of iPhones which contain a motion co-processor](https://en.wikipedia.org/wiki/Apple_motion_coprocessors#Products), hence the iPhone 5s is the earliest (although iPads contain also contain the motion coprocessor, pedometer functionality is not supported - [see here](https://github.com/leecrossley/cordova-plugin-pedometer/issues/1#issuecomment-69605787)).

Can you confirm that Motion Tracking is enabled on your iPhone 5s? Go to Settings > Privacy > Motion & Fitness > make sure "Fitness Tracking" is toggled "on."

Assuming it's enabled, then it's a question of debugging the plugin's Objective-C implementation when running on an iPhone 5s. I don't have a physical iPhone 5s device to test this with, however I will try to get hold of one. In the meantime, you can try debugging in Xcode yourself to see exactly what native values are being returned.

**Comment by dpa99c** [comment]
Closed due to no response from OP
