### ISSUE TITLE
[FEATURE] Add getCurrentInterruptionFilter() for Android

### ISSUE THREAD

**Issue by luigi37** [dpa99c/cordova-diagnostic-plugin#249]
Hi, would be possible to add the possibility know if the notifications are enabled in "Standby mode"?
Thanks
Luigi

**Comment by dpa99c** [comment]
I assume by "Standby mode" you are referring to [Doze mode](https://developer.android.com/training/monitoring-device-state/doze-standby.html) on Android 6+?

As far as I'm aware, the only notifications that will be received in Doze mode are Firebase high priority messages - see the [Doze checklist](https://developer.android.com/training/monitoring-device-state/doze-standby.html#assessing_your_app).

I don't know of any native Android API that will help with this. 
Can you provide a native implementation example of how this would work?

**Comment by luigi37** [comment]
Hi and thanks for fast reply.
I'm working on a special type of alarm clock (which will be issued depending on external, variable conditions).
Usually people will put the phone in "do not disturb" but in this case I need the app to be receiving the notification.
And yes, it's right it arrives as a Firebase high priority notification.
To work properly, I'd need users to setup the App to be able to receive notifications even during stand by. So a  warning would help.

**Comment by dpa99c** [comment]
Currently the plugin exposes [isRemoteNotificationsEnabled()](https://github.com/dpa99c/cordova-diagnostic-plugin#isremotenotificationsenabled) which on Android [calls](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L664) the native method [NotificationManagerCompat.areNotificationsEnabled()](https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()): "Returns whether notifications from the calling package are not blocked." I.e. whether notifications are blocked or not for the app.

The only other native method that might be of use to you is [NotificationManager.getCurrentInterruptionFilter()](https://developer.android.com/reference/android/app/NotificationManager.html#getCurrentInterruptionFilter()) which returns the global setting for which notifications are allowed to interrupt the user.

**Comment by luigi37** [comment]
That sounds helpful. Will give it a try and report back .
Thanks
