### ISSUE TITLE
Push Notifications Permissions

### ISSUE THREAD

**Issue by QuentinFchx** [dpa99c/cordova-diagnostic-plugin#25]
Do you think it would make sense to detect notifications permissions in this plugin ?

**Comment by dpa99c** [comment]
Yep, I think it would be useful to check whether push notification permissions has been granted on iOS.

But I think requesting that permission would be beyond the scope of this plugin, and there are many plugins that already do this anyway.

**Comment by QuentinFchx** [comment]
You're right, it seems that phonegap-push-plugin [will-have](https://github.com/phonegap/phonegap-plugin-push/pull/305) built-in support for permissions.
However, it does not go further and I still need your plugin to open the proper settings pane.

That's why it could have been interesting to have both permissions check and settings opening into your plugin.
Up to you if you think that's beyond its scope :)

Thanks for this very useful plugin anyway :+1:

**Comment by dpa99c** [comment]
Just to clarify: I think that checking the whether the app has push notification permission is useful and within scope, so is something I will add when I get time.

But what I don't think is within scope is the ability to request (setup) push notifications for the app - as you said, there are many other plugins that can already do this.

**Comment by dpa99c** [comment]
Fixed by commit 567b44323ab12e9b2712f30c184e0c1d5ea2c3f0
