### ISSUE TITLE
Getting error at build time because of plugin

### ISSUE THREAD

**Issue by Anurag-Sing** [dpa99c/cordova-diagnostic-plugin#251]
Hi at the time of build i am getting the following error

cordova\plugins\Diagnostic.java:378: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing this.cordova.getActivity() to this.cordova.getActivity().getApplicationContext() [WifiManagerLeak]
        WifiManager wifiManager = (WifiManager) this.cordova.getActivity().getSystemService(Context.WIFI_SERVICE);

and

Diagnostic.java:451: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing this.cordova.getActivity() to this.cordova.getActivity().getApplicationContext() [WifiManagerLeak]
        WifiManager wifiManager = (WifiManager) this.cordova.getActivity().getSystemService(Context.WIFI_SERVICE);

my plugin version is cordova.plugins.diagnostic 3.1.7 "Diagnostic"

please reply ASAP

**Comment by hugomenesesp** [comment]
As a fast workaround, you can downgrade your Android Platform to <6.4

```
cordova platform rm android
cordova platform add android@6.3 
```

Full answer explanation here: https://stackoverflow.com/a/47319534/1583507
