### ISSUE TITLE
Exception occurred: WifiService: Neither user nor current process has android.permission.ACCESS_WIFI_STATE

### ISSUE THREAD

**Issue by WeaponX86** [dpa99c/cordova-diagnostic-plugin#252]
This exception is thrown on Android 8.0.0 when calling cordova.plugins.diagnostic.isWifiAvailable 

Phonegap version is cli-7.0.1.

I've been trying to append the permission to the AndroidManifest.xml but Phonegap Build no longer supports the config-file element in config.xml.

**Comment by dpa99c** [comment]
> Phonegap Build no longer supports the config-file element in config.xml

According to the [Phonegap Build documentation](http://docs.phonegap.com/phonegap-build/configuring/config-file-element/), you should be using [`<edit-config>`](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config) with `cli-7.0.1` instead of `<config-file>`.

**Comment by WeaponX86** [comment]
I posted a question about it in the Phonegap Forum already.
https://forums.adobe.com/thread/2412353

I have yet to find a way to append an element using edit-config. It will only alter an existing element.

I tried this, which just changes the manifest element attributes:
	<edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
		<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	</edit-config>

And I tried this:
I tried this, which ends up replacing the first existing uses-permission element it finds:
	<edit-config file="AndroidManifest.xml" target="/manifest/uses-permission" mode="merge">
		<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	</edit-config>

**Comment by dpa99c** [comment]
OK, best of luck, but closing this as the problem lies with Phonegap Build, not this plugin.
