### ISSUE TITLE
Include access fine location by default 

### ISSUE THREAD

**Issue by elijthomas** [dpa99c/cordova-diagnostic-plugin#257]
The plugin only asks for coarse location permission by defualt in config.xml 
can we add  
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
by default, 

this is because adding it using edit-config on PGB (7.0.1) doesnt  work so we are stuck

**Comment by dpa99c** [comment]
This plugin does not add any Android `<uses-permission>` requests to the `config.xml`, as can be seen from the [`platform="android"` section of its `plugin.xml`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L93).

[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions), it is the responsibility of the plugin user (i.e. you) to add appropriate `<uses-permission>` entries to the `AndroidManifest.xml`.

In a local build environment, this can be achieved using [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) however you are using Phonegap Build which doesn't support hook scripts, so you will be unable to use this method.

In versions of PGB prior to `cli-7.0.1` you could use `<config-file>` blocks directly in the `config.xml` (without needing `cordova-custom-config`), however [as documented by PGB](http://docs.phonegap.com/phonegap-build/configuring/config-file-element/), v7.0.1 drops support for `<config-file>` blocks.

So I think your best option is to switch to using PGB `cli-6.5.0` which does support `<config-file>` blocks in `config.xml`, then you can add something like this:

    <platform name="android">
        <plugin name="cordova-custom-config" version="*"/>
        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
        </config-file>
    </platform>
