### ISSUE TITLE
Problem on android earlier version than kitkat

### ISSUE THREAD

**Issue by jgm196** [dpa99c/cordova-diagnostic-plugin#26]
Hi,

I´m developing an app using ionic, and I have used this plugin to detect if the user has the location enabled or not.

I was having an exception problem if the android version was earlier than kitkat (19). So I have modified the plugin code to get it works, but I don´t know if my changes are correct.

In the function getLocationMode() I have change the code with this:

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT){
			return Settings.Secure.getInt(this.cordova.getActivity().getContentResolver(), Settings.Secure.LOCATION_MODE);
		}else{

			LocationManager locationMgr = (LocationManager) this.cordova.getActivity().getSystemService(Context.LOCATION_SERVICE);
			if(!locationMgr.isProviderEnabled(LocationManager.NETWORK_PROVIDER) && !locationMgr.isProviderEnabled(LocationManager.GPS_PROVIDER)){
				return 0;
			}else{
				if(locationMgr.isProviderEnabled(LocationManager.GPS_PROVIDER)){
					return 3;
				}else{
					if(locationMgr.isProviderEnabled(LocationManager.NETWORK_PROVIDER)){
						return 2;
					}else{
						return 0; //no provider detected
					}
				}
			}
		}

I have change the functions isgpslocationenabled and isnetworklocationenabled too, because there was a problem with Settings.Secure. I don´t lnow if is there another way to solve my problem.

Thanks and greetings

**Comment by dpa99c** [comment]
Hi, I have to admit I haven't done much testing on pre-Kitkat devices. When I get some time, I will test/fix the plugin methods for pre-Kitkat where possible.

**Comment by jagdishadusumalli** [comment]
I guess i am also facing the same issue.

I tested with diagnostic plugin versions 2.3.3, 2.3.4 and the latest 2.3.5
on Genymotion simulators for Android versions 4.1.1(HTCOne XL), 4.2.2(Moto X) 
& 4.3 (Google Nexus 4) and on Lava Iris 504Q (Physical Device) running android 4.2.1
i get "Error Exception occcured: location_mode" & makes my app unresponsive
See the error screenshot attached below
<img width="1440" alt="screen shot 2015-12-23 at 18 11 52" src="https://cloud.githubusercontent.com/assets/1783043/12196690/c1bd4130-b626-11e5-8e9f-a3f328834113.png">

App is working fine on Android 4.4.x + version

Have for now downgraded to 2.2.4 on which the app works fine on all versions

I will try the @jgm196 patch and report back

**Comment by dipanjanc** [comment]
hi, 
the patch by @jgm196 did not work for me :(
could you share the changed files or provide access to your fork of this repo with the changes?

**Comment by jgm196** [comment]
Hi, I´m only using this plugin in my app to check if the location is enabled or not, so, I have only changed the piece of code that I need. The problem was that "Settings.Secure.LOCATION_MODE" returns an exception in versions below kitkat, so I have changed some functions in the code to get this works.

    private int getLocationMode() throws Settings.SettingNotFoundException {
		if (Build.VERSION.SDK_INT >= 19){
			return Settings.Secure.getInt(this.cordova.getActivity().getContentResolver(), Settings.Secure.LOCATION_MODE);
		}else{

			LocationManager locationMgr = (LocationManager) this.cordova.getActivity().getSystemService(Context.LOCATION_SERVICE);
			if(!locationMgr.isProviderEnabled(LocationManager.NETWORK_PROVIDER) && !locationMgr.isProviderEnabled(LocationManager.GPS_PROVIDER)){
				return 0;
			}else{
				if(locationMgr.isProviderEnabled(LocationManager.GPS_PROVIDER)){
					return 3;
				}else{
					if(locationMgr.isProviderEnabled(LocationManager.NETWORK_PROVIDER)){
						return 2;
					}else{
						return 0;
					}
				}
			}
		}
    }


    public boolean isGpsLocationEnabled() throws Exception {
        int mode = getLocationMode();
        boolean result = (mode == 3 || mode == 2) && isLocationAuthorized();
        Log.d(TAG, "GPS enabled: " + result);
        return result;
    }

    public boolean isNetworkLocationEnabled() throws Exception {
        int mode = getLocationMode();
        boolean result = (mode == 3 || mode == 2) && isLocationAuthorized();
        Log.d(TAG, "Network enabled: " + result);
        return result;
    }


I hope this will be helpfull

**Comment by sachinnaik** [comment]
Hi @dpa99c,

I am also facing same issues on android 4.1/ 4.2/ 4.3. It will be awesome if you can fix this issue asap as i am still sticking to version 2.2.4 which is working.

**Comment by dipanjanc** [comment]
thanks @jgm196 
but it didn't work :( my release is stuck because of this issue. 
@dpa99c would really appreciate it if this could be fixed & released. 
cheers.

**Comment by dpa99c** [comment]
@dipanjanc I'll try to have a look tonight after work

**Comment by dipanjanc** [comment]
cheers mate! works like a charm.
