### ISSUE TITLE
getBluetoothState() give only powered_off on iOS11

### ISSUE THREAD

**Issue by sKuD51** [dpa99c/cordova-diagnostic-plugin#260]
Hello, 

first, thanks for this great plugin. I used it for my app and it is very usefull.
On iOS 11, I must detect if bluetooth is enabled or not, so I use cordova.plugins.diagnostic.getBluetoothState(function(state) {},function(error){}), but state is always  powered_off.

Anybody have this error?
Thanks.

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate that the plugin works correctly on iOS 11 and rule out the cause as a bug in your own code. The example app illustrates/validates all plugin functionality [including `getBluetoothState()`](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L536)

Below is a screenshot of the example project running on iPad Air 2 running iOS 11.2. 
As can be seen in the screenshot, "Bluetooth state" is reported as "POWERED_ON".

![screen shot 2017-12-13 at 14 20 33](https://user-images.githubusercontent.com/2345062/33943568-6928c546-e011-11e7-8649-4d276e2423dc.png)

**Comment by sKuD51** [comment]
So, I test with your example project, very usefull ;-).
First test : I go to iOS settings and enable bluetooth => app said me Bluetooth UNAVAILABLE , state POWERED_OFF
![img_2275](https://user-images.githubusercontent.com/9740348/33961192-6866612c-e04d-11e7-8ee6-7fed67fe6035.PNG)


Second test : I unable Bluetooth by using the shortcut by sliding bottom to top and tap on bluetooth icon to deactivate and re-tap to activate. I open the example app and it's magic, bluetooth is available and state is POWERED_ON
![img_2276](https://user-images.githubusercontent.com/9740348/33961223-8a5faff4-e04d-11e7-929e-78d9c86ad155.PNG)

Conclusion : it's bug from iOS 11. I've seen it by using AirDrop between my iPhone and my Mac, if we only enable bluetooth from iOS settings, it doesn't work. We must enable it from the short cut menu.

Thanks @dpa99c and great job.

**Comment by dpa99c** [comment]
I tested this on my iPad running iOS 11.2 and it seems that on iOS 11, turning off Bluetooth in the Control Centre (swipe up from bottom) is not the same as turning off Bluetooth in the Settings app:

When I turn off Bluetooth in the Control Centre on my iPad, a message pops up saying "Disconnecting Bluetooth Devices until tomorrow". At this point `getBluetoothState()` returns `POWERED_OFF` but in the Settings app the "Bluetooth" switch is ON.

However, below it is a "Allow New Connections" button. If I press it, the Bluetooth switch in Control Centre is turned back on and  `getBluetoothState()` returns `POWERED_ON`.

When I turn the Bluetooth switch in the Settings app off, "Allow New Connections" button does not appear below it, the Bluetooth switch in Control Centre is off, and `getBluetoothState()` returns `POWERED_OFF`. 

If I then turn on Bluetooth in the Control Centre, the "Bluetooth" switch in the Settings app is ON and `getBluetoothState()` returns `POWERED_ON`.

Horribly inconsistent behaviour from Apple here :-(

**Comment by sKuD51** [comment]
Same test and same conclusion.
Thanks @dpa99c
