### ISSUE TITLE
How can I tell if I'm running on iOS to not call Android-only methods

### ISSUE THREAD

**Issue by Mac351** [dpa99c/cordova-diagnostic-plugin#261]
Some methods only work on Android (eg: https://www.npmjs.com/package/cordova.plugins.diagnostic#hasbluetoothsupport)

However, I don't know if my app is running on android or iOS. If I'm on iOS the method above crashes the app.

If I want to use this useful function, how can I make it work for ios and android? Wrap the call in a try/catch block? I'd much prefer have the plugin fail more gracefully if possible.

**Comment by JoergHolz** [comment]
That is the way to do it:

 if (cordova.platformId === "android") {
   
   // Here your Android code

}

**Comment by dpa99c** [comment]
Yes, it is
