### ISSUE TITLE
iOS App Reject due to prefs:root non-public URL

### ISSUE THREAD

**Issue by danfleck** [dpa99c/cordova-diagnostic-plugin#262]
My app got rejected from Apple due to this plugin using prefs:root. 

"Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change."

Any simple way to change how it works internally to use supported Apple functions?

**Comment by dpa99c** [comment]
This code was introduced by PR #223. By the looks of my comment in September, it doesn't work anyway so I was planning to remove it (but apparently forgot to). 

However, given that it's resulted in your app being rejected, I will prioritise its removal.

**Comment by danfleck** [comment]
To add to it... the rejection said: 

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

So both prefs:root and App-Prefs:root aren't allowed.

**Comment by dpa99c** [comment]
I'm going to revert that entire PR which added both "prefs:root" and "App-Prefs:root", after which it should be safe for App Store Reviews again.

**Comment by dpa99c** [comment]
This offending code has been removed in `cordova.plugins.diagnostic@3.7.3` so that version should be safe for re-submission to the App Store.

**Comment by jassiwaliaVC** [comment]
its still coming issue in @3.9.2

**Comment by dpa99c** [comment]
@jassiwaliaVC Please update to the latest version: 4.0.8

**Comment by AgNm** [comment]
@dpa99c My plugin is already updated with version 4.0.8 still my got rejected yesterday, any solution?

**Comment by dpa99c** [comment]
@AgNm Are you sure the cause of the rejection was the same as outlined in this issue?

> "Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change."

If the rejection cause is the same, search your local code for occurrences of `prefs:root` to find where it is located.

The code causing this issue was removed by [this commit](https://github.com/dpa99c/cordova-diagnostic-plugin/commit/7f5bae2de997345e6acfa204d4f0163d0b14912a) so is no longer present in the plugin. You can confirm this by [searching the plugin source for the offending `prefs:root`](https://github.com/search?utf8=%E2%9C%93&q=prefs%3Aroot+user%3Adpa99c+repo%3Adpa99c%2Fcordova-diagnostic-plugin+fork%3Atrue&type=Repositories&ref=advsearch&l=&l=) and see that it is no longer present.

**Comment by dpa99c** [comment]
@AgNm Did Apple give exactly the same reason for rejection as above?

> "Your app uses the "prefs:root=" non-public URL scheme..."

**Comment by AgNm** [comment]
Yes, I have removed & added latest plugin in the app & uploaded again. Lets see. Hoping for best.

**Comment by AgNm** [comment]
@dpa99c Can you please confirm that after using the latest version `4.0.8` of the plugin, the app will not get rejected, but apple warns me that he will close my account: 

`Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store. `

**Comment by brodybits** [comment]
@AgNm it is your own job to check that you have resolved the issues with your app. You should be able to get a more clear explanation from Apple. Then you would have to double-check your own app code and every single plugin for whatever may be violating their terms.

Questions and issues with the other plugin should be raised there. I suspect it wasn't meant for app stores, better ask for confirmation there. TBH I think you would be much better off using a more standard location plugin. Customize it if necessary, be very careful not to violate the app store terms.

If you do find a problem with any of the other plugins I am sure a report would be really appreciated there.

**Comment by AgNm** [comment]
@brodybits thank you for your response...
