### ISSUE TITLE
strings in switch are not supported in -source 1.6

### ISSUE THREAD

**Issue by shayoo** [dpa99c/cordova-diagnostic-plugin#264]
Support Information:
cordova: 8.0.0
android 6.3.0

My build fails after adding this plugin. Anyone please help me out. Thanks in advance

Error:
/myProject/platforms/android/src/cordova/plugins/Diagnostic.java:1262: error: strings in switch are not supported in -source 1.6
        switch(abi){
              ^
  (use -source 7 or higher to enable strings in switch)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /myProject/platforms/android/src/cordova/plugins/Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by dpa99c** [comment]
Fixed in [v3.8.1](https://github.com/dpa99c/cordova-diagnostic-plugin/releases/tag/3.8.1) by PR #263.
