### ISSUE TITLE
Diagnostic Error While Build

### ISSUE THREAD

**Issue by seagate25** [dpa99c/cordova-diagnostic-plugin#265]
Error: /Users/macbook/Desktop/IONIC/Ionic2Diagnostic/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/macbook/Desktop/IONIC/Ionic2Diagnostic/platforms/android/src/cordova/plugins/Diagnostic.java:1262: error: strings in switch are not supported in -source 1.6
        switch(abi){
              ^
  (use -source 7 or higher to enable strings in switch)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/macbook/Desktop/IONIC/Ionic2Diagnostic/platforms/android/src/cordova/plugins/Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v6.10.3
    npm               : 5.0.3 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.2 Build version 8E2002 

Environment Variables:

    ANDROID_HOME : /Users/macbook/Library/Android/sdk/

Misc:

    backend : legacy

**Comment by dpa99c** [comment]
Duplicates #264

**Comment by seagate25** [comment]
thanks @dpa99c i will try again the plugins
