### ISSUE TITLE
Cordova mobile application error

### ISSUE THREAD

**Issue by Prakashharsa** [dpa99c/cordova-diagnostic-plugin#266]
I am developing cordova jquery mobile application, previously it is working fine. but when i add stripe plugin in my application it's showing this error...       
    
                                                                          MSBUILD : cordova-build error : > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.3\aapt.exe'' finished with non-zero exit value 1
1>  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.3\aapt.exe'' finished with non-zero exit value 1

**Comment by dpa99c** [comment]
This plugin has nothing to do with Stripe. Please do not open issues that are irrelevant.
