### ISSUE TITLE
App build fails due to plugin when upgraded to cordova-ios 4.0.x

### ISSUE THREAD

**Issue by jagdishadusumalli** [dpa99c/cordova-diagnostic-plugin#27]
I upgraded to cordova-ios 4.0.1 post which my ionic app is failing to build

There are many plugins which are failing out of which diagnostic is also the one.
i had posted the issue on cordova-ios issue tracker and @shazron have reverted with suggestions to fix the plugin as many deprecated methods have been removed in cordova-ios 4.0.1.
https://issues.apache.org/jira/browse/CB-10310 

**Info on the code breaks and fixing them**
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html
http://cordova.apache.org/news/2015/11/24/plugins-release.html

Also attaching the exact error for the plugin with cordova-ios@4.0.1
<img width="1440" alt="screen shot 2015-12-23 at 22 26 00" src="https://cloud.githubusercontent.com/assets/1783043/12228063/3559e45e-b85c-11e5-9418-0cc5d63bdb90.png">

**Comment by Zapmobilegames** [comment]
Same using Intel XDK, the debug module gives an error and I can't add the plugin. Hope this would be soon fixed

**Comment by srikanthv** [comment]
@dpa99c we are facing the same issue that Jagdish has posted. Could you please fix this ASAP...

Thanks

**Comment by dpa99c** [comment]
Just published cordova.plugins.diagnostic@2.3.6 to npm which contains this fix. Sorry it took a while. Been busy.

**Comment by dpa99c** [comment]
Actually, use cordova.plugins.diagnostic@2.3.7 - this comments out support for WKWebView for now as it was causing compile errors on cordova-ios@3

**Comment by gsanjeevkumar** [comment]
Hi. Is there are work around for this.

My app needs to change orientation to show a video and switch back both android and iOS. Need help on this.

Please let me know.

Thanks in advance

**Comment by dpa99c** [comment]
cordova.plugins.diagnostic@2.3.6 fixed this issue. The current release is 2.3.10 - make sure you're using an up-to-date version and it should work fine with cordova-ios@4+

btw, this plugin has nothing to do with changing screen orientation - are you sure you didn't mean to post here: [https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/84](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/84)
