### ISSUE TITLE
getBluetoothState() returns UNKNOWN the first time

### ISSUE THREAD

**Issue by luisenrike** [dpa99c/cordova-diagnostic-plugin#271]
I'm developing an ionic app, and, on iOS, the `getBluetoothState()` function always returns `UNKNOWN` the first time that it's called, after that, it works OK.

Here is my system info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v9.1.0
    npm               : 5.5.1
    OS                : macOS Sierra
    Xcode             : Xcode 9.2 Build version 9C40b
```

**Comment by dpa99c** [comment]
I can reproduce this and I think I know what the issue is. Should able to push out a patch release containing a fix shortly.

**Comment by dpa99c** [comment]
Published to NPM in `cordova.plugins.diagnostic@3.9.2`

**Comment by luisenrike** [comment]
Awesome, thanks

**Comment by burbia** [comment]
This is happening again in version 6.0.2

Ionic:

   Ionic CLI                     : 6.11.10 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.901.12
   @angular-devkit/schematics    : 9.1.12
   @angular/cli                  : 9.1.12
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   :   cordova.plugins.diagnostic: ^6.0.2

System:

   ios-sim : 8.0.2
   NodeJS  : v14.13.0 (/usr/local/Cellar/node/14.13.0/bin/node)
   npm     : 6.14.8
   OS      : macOS Catalina
   Xcode   : Xcode 12.0.1 Build version 12A7300

**Comment by SamuelMichelRiad** [comment]
Is there a workaround for this?
