### ISSUE TITLE
Thread warning Method isLocationAvailable IOS > 10

### ISSUE THREAD

**Issue by Clonk-HTML5** [dpa99c/cordova-diagnostic-plugin#272]
Issue with IOS Version greater 10.
Using Method isLocationAvailable.

`
THREAD WARNING: ['Diagnostic'] took '252.113037' ms. Plugin should use a background thread.
`

**Comment by dpa99c** [comment]
Published to NPM in `cordova.plugins.diagnostic@3.9.2`
