### ISSUE TITLE
getLocationAuthorizationStatus and isLocationAuthorized not working on iOS 10.2

### ISSUE THREAD

**Issue by sbatezat** [dpa99c/cordova-diagnostic-plugin#273]
On my iPhone 5S - iOS 10.2, if the user has refused to accept the authorization after a call to requestLocationAuthorization(), both functions getLocationAuthorizationStatus and isLocationAuthorized() never return a result (neither then nor catch are called - I'm using ionic/native). I've even tried to restart the app, both functions cannot be called anymore.

**Comment by dpa99c** [comment]
I don't have a device running iOS 10.2, however I haven't been able to reproduce the issue in the Simulator running iOS 10.3.1 - see [this screen capture](http://ge.tt/8Hq4eIo2). I'd be suprised if there's a difference between those minor versions of iOS. 

To validate that the plugin is working correctly, please follow the same steps as in the screen capture video:

- Create a blank Cordova test project: `cordova create test && cd test`
- Add the latest iOS platform: `cordova platform add ios@latest`
- Add the latest version of this plugin: `cordova plugins add cordova.plugins.diagnostic@latest`
- Run the test project on your device either via XCode or the command line: `cordova run ios --device`
- Open Safari and use the Develop menu to connect Web Inspector to the app Webview running on the device
- Run the following commands in order from the Console:

      cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){console.log(status);alert(status)})
      cordova.plugins.diagnostic.isLocationAuthorized(function(status){console.log(status);alert(status)})
      cordova.plugins.diagnostic.requestLocationAuthorization(function(status){console.log(status);alert(status)})

- Select "Don't Allow" then:

      cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){console.log(status);alert(status)})
      cordova.plugins.diagnostic.isLocationAuthorized(function(status){console.log(status);alert(status)})

**Comment by sbatezat** [comment]
1. alert with "denied"
2. alert with "false"
3. ask to activate location, and using of the "cancel" button
4. alert with "denied"
5. alert with "false" 

Ok - my bad. I'll try to figure out why it's not working on my project. It could be a lot of things... I'm coming back to you today. Thanks anyway

**Comment by sbatezat** [comment]
I think my Safari debugger has made fun of me! I cannot reproduce the issue described above... However I do have an issue, I've just misunderstood which function was not working fine. 

With the blank project created with command lines you wrote above :

cordova.plugins.diagnostic.requestLocationAuthorization(function(result){console.log(result);alert(result)}, function(result){console.log(result);alert(result)})

No alert, but the popup asking me to authorize appears

cordova.plugins.diagnostic.requestLocationAuthorization(function(result){console.log(result);alert(result)}, function(result){console.log(result);alert(result)})

No alert, no popup
Restart the app

cordova.plugins.diagnostic.requestLocationAuthorization(function(result){console.log(result);alert(result)}, function(result){console.log(result);alert(result)})

No alert, but the popup asking me to authorize appears
Restart the app

cordova.plugins.diagnostic.requestLocationAuthorization(function(result){console.log(result);alert(result)}, function(result){console.log(result);alert(result)})

No alert, no popup

Seems to be related to https://github.com/dpa99c/cordova-plugin-request-location-accuracy#ios-cancel-button-caveat. Hopefully it's not as there is no solution...

**Comment by dpa99c** [comment]
I think what you're saying is, if you press "Don't Allow" when the permission request prompt appears, that the dialog doesn't appear again then permission is requested again?

If so, then that's because, once a user refuses, the app isn't allow to ask again and consequently cannot show the prompt again - [see here](https://stackoverflow.com/questions/4245299/cllocation-ask-again-for-permission)
My favoured approach is to use `getLocationAuthorizationStatus()` to check the authorization state and respond accordingly, something like this:


    function onError (error){
        console.error("The following error occurred: "+error);
    }

    function checkStatus(){
        cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
           switch(status){
               case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                   console.log("Permission not requested");
                   cordova.plugins.diagnostic.requestLocationAuthorization(checkStatus, onError);
                   break;
               case cordova.plugins.diagnostic.permissionStatus.DENIED:
                   console.log("Permission denied");
                   navigator.notification.confirm( // cordova-plugin-dialogs
                   "The app has been denied permission to use location but requires it because blah.\nWould you like to open the Settings page to manually allow location for the app?", 
                   function (i) {
                        if (i === 1) {
                            navigator.notification.alert(
                                "The Settings page for the app will now open. Select \"Location\" and set it to \"Always\" then return to this app via the Home screen",
                                cordova.plugins.diagnostic.switchToSettings,
                                "Opening Settings page"
                            );
                        }
                    }, "Location permission is required", [
                        'Yes',
                        'No'
                    ]);
                   break;
               case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                   console.log("Permission granted always");
                   break;
           }
        }, onError);
    }

    document.addEventListener("deviceready", checkStatus, false); // check on app startup
    document.addEventListener("resume", checkStatus, false); // check on app resume from background

**Comment by sbatezat** [comment]
Cheers, I'll proceed that way

**Comment by alexandranb** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/273#issuecomment-361200401

You just made my night... I would say my day... but I just spent the last 8 daytime hours debugging this inexistent bug....
