### ISSUE TITLE
Revoking Permission? Forcing Permission Dialog?

### ISSUE THREAD

**Issue by rikkuporta** [dpa99c/cordova-diagnostic-plugin#274]
Hi, is there a wazy to force to opening of the permission dialog or to revoke permissions - or is this plugin the wrong one for this? As of right now, when a user grants a permission, it cannot be revoked from inside the app.

**Comment by dpa99c** [comment]
Neither Android nor iOS provides an API to enable programmatic revoking of runtime permissions or forcing opening of a permission dialog.
