### ISSUE TITLE
 No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha

### ISSUE THREAD

**Issue by msd117** [dpa99c/cordova-diagnostic-plugin#275]
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.803 secs
Error: /home/swxuser/Desktop/SOHEL/OCS/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/swxuser/Desktop/SOHEL/OCS/platforms/android/build/intermediates/res/merged/debug/values-v11/values-v11.xml:93:54-92: AAPT: No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

Failed to generate resource table for split ''
/home/swxuser/Desktop/SOHEL/OCS/platforms/android/build/intermediates/res/merged/debug/values-v11/values-v11.xml:93: error: Error: No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by dpa99c** [comment]
This log fragment is not sufficient proof that this plugin is the cause of the build failure - in fact [this SO post](https://stackoverflow.com/questions/35628572/update-support-library-23-2-0-build-bug) would suggest not.

To verify the cause of this error, please do the following:

- Create a new blank Cordova project
- Add your target cordova-android platform version
- Install only this plugin into the project 
- Build the Android platform

If the build then fails, please post the **full** console output and include the following details:

- Cordova CLI version 
	- `cordova -v`
- Cordova Android platform version
	- `cordova platform ls`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`


If the above details are not provided, the issue will be assumed invalid and will be closed.
