### ISSUE TITLE
Permission localization iOS

### ISSUE THREAD

**Issue by malmatalla** [dpa99c/cordova-diagnostic-plugin#278]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

I need the permission message to be localized to different languages. In the current state, I cant find a solution for localizing it, it only seems to support one language.

This should be implemented since many apps are multilingual.

**Comment by dpa99c** [comment]
Localization of iOS permission messages must be done at the native Xcode project level ([see here for details](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-102276)).

There already exists a plugin that enables you to do this for a Cordova project: [cordova-plugin-localization-strings](https://github.com/kelvinhokk/cordova-plugin-localization-strings) and it specifically enables you to [localize iOS permissions](https://github.com/kelvinhokk/cordova-plugin-localization-strings#localizing-ios-permissions).

Therefore implementing such a feature in this plugin would be duplicating the purpose of that plugin.
