### ISSUE TITLE
Unable to download the plugin in visual studio

### ISSUE THREAD

**Issue by rahulgannerlla** [dpa99c/cordova-diagnostic-plugin#284]
**I'm submitting a ...**  (check one with "x"):
- [ x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

1) I am trying to install the plugin from Visual Studio using plugin ID or git and it fails.
2) I am sure this is nothing to do with my code as I have not started using this plugin yet. 

**Expected behavior:**

1) Navigate to Visual Studio Cordova (Config.xml).
2) Click 'Plugins' tab.
3) Search by plugin ID 'cordova-diagnostic-plugin'.
4) Should download the plugin in visual studio.
5) Search by GIT URL 'https://github.com/dpa99c/cordova-diagnostic-plugin.git' and it should download.

**Steps to reproduce:**

1) Navigate to Visual Studio Cordova (Config.xml)
2) Click 'Plugins' tab.
3) Search by plugin ID 'cordova-diagnostic-plugin'.
4) The search bar is greyed out searching for the plugin and it shows nothing.
5) I tried search by GIT URL 'https://github.com/dpa99c/cordova-diagnostic-plugin.git' and displays the message 'Visual Studio was unable to parse plugin.xml. Please ensure plugin.xml exists and contains no errors'.

**Environment information**

- Cordova CLI version 
	- `6.3.1`
- Cordova platform version
	- `5.2.1`
- Plugins & versions installed in project (including this plugin)
        - `cordova-plugin-camera`
        - `cordova-plugin-file`
        - `cordova-plugin-geolocation`
        - `cordova-sqlite-storage`
        - `cordova-plugin-file-transfer`
- Dev machine OS and version, e.g.
    - Windows 10
        - ` version 1607`
        
_Runtime issue_
- Device details
    - Samsung Galaxy S5
- OS details
    - _e.g.  Android 6.0.1	
	
_Android build issue:_	
- Node JS version
    - `4.4.3`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `21` 
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
<br/><br/>

**Comment by dpa99c** [comment]
Seems the literal `<` in the `comment` attribute on [this line](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L58) of `plugin.xml` is causing Visual Studio to take issue with it.

Will push out a patch release to resolve it shortly.

**Comment by dpa99c** [comment]
Fix published in v4.0.3
