### ISSUE TITLE
add node_modules to the repository gitignore

### ISSUE THREAD

**Issue by TianleZhang** [dpa99c/cordova-diagnostic-plugin#287]
Hello, 

We are currently using this plugin, and we implemented a build process by using git submodule. And what happens is this plugin's node_modules are not added to gitignore. Can you please add them to the gitignore? That will be great for us. thx. :)

**Comment by dpa99c** [comment]
The node dependencies of this modules are installed by Cordova into the project root.

For example, if your project is at `/projects/foo/` then the modules will be installed to `/projects/foo/node_modules/`. e.g. the [minimist dependency](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/package.json#L40) is installed to `/projects/foo/node_modules/minimist/`.

Cordova installs the plugin via npm then copies it to the plugins folder so there are 2 copies located at `/projects/foo/node_modules/cordova.plugins.diagnostic/` and `/projects/foo/plugins/cordova.plugins.diagnostic/`

Therefore, a `.gitignore` in `/projects/foo/node_modules/cordova.plugins.diagnostic/` or `/projects/foo/plugins/cordova.plugins.diagnostic/` is unable to exclude modules in `/projects/foo/node_modules/` and neither should it: these modules are project-level and so it is up to the project owner (i.e. you) to define exclusions at or above the level of `/projects/foo/node_modules/`. I would recommend you create a `.gitignore` at `/projects/foo/.gitignore` and use this to exclude some or all of the node_modules.

Closing as excluding project-level node_modules cannot/should not be implemented by a plugin with that project.

**Comment by TianleZhang** [comment]
Yes, you are right, but the issue is we are using sub-modules. So we add the plugin as a sub-module to the project, so the project gitignore won't work for sub-modules. So if you guys can help us just add them to your gitignore, that will be great to help us.

**Comment by TianleZhang** [comment]
And if you see other plugins, many of them does add node_modules to the repo.

**Comment by dpa99c** [comment]
so you just want node_modules ignored in the plugin root? 
I guess it will not affect most users as they don't have any node_modules located there.

**Comment by dpa99c** [comment]
I've made the change in the master branch so it will be published in the next release.

**Comment by TianleZhang** [comment]
Thx :)
