### ISSUE TITLE
How can I remove permissions?

### ISSUE THREAD

**Issue by marcoas** [dpa99c/cordova-diagnostic-plugin#288]
(Translated by Google)

How can I remove permissions?
I need the user to remove the GPS permission, and allow it again, when he wants it.

**Comment by dpa99c** [comment]
It's not possible to revoke permissions programmatically on either Android or iOS. 
Once a permission is granted, only the user is able to do revoke it manually via the Settings app.

**Comment by MahaMinar** [comment]
Is there any chance to get information that mock location is set enable or disable?
Thanks
