### ISSUE TITLE
Crdova Plugin Add cordova.plugins.diagnostic ??????

### ISSUE THREAD

**Issue by EngMohammadAbdullah** [dpa99c/cordova-diagnostic-plugin#289]
I think it's impossible to add this plugin to Cordova project , 
I tried all solutions to add this plugin , I failed

**Comment by dpa99c** [comment]
See the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example)

**Comment by EngMohammadAbdullah** [comment]
Thanks a lot , The problem was with Vistual Studio cordova tools , 
it's create Android platform 5.3.2 or about 5,_,_ , so this was the problem , 
and of course install higher android api
