### ISSUE TITLE
error! on cli 5.2.0 Gradle android build in values-v23/values.xml 

### ISSUE THREAD

**Issue by martin-eq** [dpa99c/cordova-diagnostic-plugin#29]
I need help with a compile error on Phonegap Build caused by this plugin.

My error is the same described here: http://community.phonegap.com/nitobi/topics/error-on-cli-5-2-0-gradle-android-build-in-values-v23-values-xml

"That plugin requires Android SDK-23. I am not sure whether or not PGB already uses this SDK version."
"we are not on Android SDK-23 - yet!"

How can I bypass this?

Thanks!

**Comment by dpa99c** [comment]
Use the [api-22 branch](https://github.com/dpa99c/cordova-diagnostic-plugin/tree/api-22#important-android-note) as [instructed here](https://github.com/dpa99c/cordova-diagnostic-plugin#building-for-api-22-or-lower):

    <gap:plugin name="cordova.plugins.diagnostic.api-22" source="npm" />

**Comment by martin-eq** [comment]
Thank you very much! I didn't see that on the documentation, my bad. 
By the way, awesome plugin and documentation, great work!

**Comment by dpa99c** [comment]
No worries, I only added that branch very recently, so maybe it wasn't documented when you last looked. Glad the plugin is useful :-)
