### ISSUE TITLE
switchToLocationSettings() on iOS

### ISSUE THREAD

**Issue by malutanpetronel** [dpa99c/cordova-diagnostic-plugin#291]
switchToLocationSettings() is implemented for 
Platforms: Android and Windows 10 UWP

What can I use for a iPhone please to directly open the settings location or so ?

**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [x] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone 7, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic info`
- Installed Ionic Native modules and versions
    - `npm list | grep "@ionic-native"`

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
It's not possible to directly open the Location Settings page on IOS using the available public API methods.

Note: it is possible using private API functions (see #223) but this will lead to your app being rejected (see #262)
