### ISSUE TITLE
Got error when installing plugin.

### ISSUE THREAD

**Issue by sanjay63350** [dpa99c/cordova-diagnostic-plugin#293]
Hi ,

When installing plugin I am seeing this error.

Error: Failed to fetch plugin cordova.plugins.diagnostic via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.

I have a good working internet and can install other plugins. 

Thanks

**Comment by dpa99c** [comment]
The plugin installs fine in my environment:

	$ cordova plugin add cordova.plugins.diagnostic --verbose
	No scripts found for hook "before_plugin_add".
	No version specified for cordova.plugins.diagnostic, retrieving version from config.xml
	No version for cordova.plugins.diagnostic saved in config.xml or package.json
	Attempting to use npm info for cordova.plugins.diagnostic to choose a compatible release
	Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" view cordova.plugins.diagnostic --json""
	Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" view cordova.plugins.diagnostic --json"
	npm info for cordova.plugins.diagnostic did not contain any engine info. Fetching latest release
	Calling plugman.fetch on plugin "cordova.plugins.diagnostic"
	saving
	Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova.plugins.diagnostic --production --save""
	Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova.plugins.diagnostic --production --save"
	Copying plugin "D:\Temp\test\node_modules\cordova.plugins.diagnostic" => "D:\Temp\test\plugins\cordova.plugins.diagnostic"
	Calling plugman.install on plugin "D:\Temp\test\plugins\cordova.plugins.diagnostic" for platform "android
	Installing "cordova.plugins.diagnostic" for android
	Running command: cmd "/s /c "D:\Temp\test\platforms\android\cordova\version.bat""
	Command finished with error code 0: cmd /s /c "D:\Temp\test\platforms\android\cordova\version.bat"
	Finding scripts for "before_plugin_install" hook from plugin cordova.plugins.diagnostic on android platform only.
	No scripts found for hook "before_plugin_install".
	Install start for "cordova.plugins.diagnostic" on android.
	PlatformApi successfully found for platform android
	Beginning processing of action stack for android project...
	Installing Android library: com.android.support:support-v4:26.+
	Installing Android library: com.android.support:appcompat-v7:26.+
	Action stack processing complete.
	Updating build files since android plugin contained <framework>
	Subproject Path: CordovaLib
	Install complete for cordova.plugins.diagnostic on android.
	Finding scripts for "after_plugin_install" hook from plugin cordova.plugins.diagnostic on android platform only.
	No scripts found for hook "after_plugin_install".
	Adding cordova.plugins.diagnostic to package.json
	Saved plugin info for "cordova.plugins.diagnostic" to config.xml
	No scripts found for hook "after_plugin_add".

I suspect that if this were an actual problem with the plugin, it would have been reported by now given that the plugin gets [5000-6000 downloads per week](https://npm-stat.com/charts.html?package=cordova.plugins.diagnostic&from=2017-04-14&to=2018-04-14).

It's most likely an issue either with your connection or development environment. I suggest installing the with `--verbose` option to diagnose.

Given that you haven't filled out the issue template with your dev environment info, no futher investigation can be done so closing the issue.
