### ISSUE TITLE
WARN: Native: tried calling Diagnostic.switchToLocationSettings, but the Diagnostic plugin is not installed.

### ISSUE THREAD

**Issue by CodeMiser** [dpa99c/cordova-diagnostic-plugin#296]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

NOTE: Originally produced with "cordova.plugins.diagnostic": "^3.9.2"  Retested with 4.0.5.  No change.  this.diagnostic.isLocationEnabled() and this.diagnostic.getLocationAuthorizationStatus() produce the expected results.  this.diagnostic.switchToLocationSettings() is failing.

Ionic app built with Xcode 9.3, running with iOS 11.3, using the Ionic Native Diagnostic wrapper, calling this.diagnostic.switchToLocationSettings(); produces Xcode Debug Console log:

2018-04-18 10:07:50.404764-0400 Safety[8835:3792840] WARN: Native: tried calling Diagnostic.switchToLocationSettings, but the Diagnostic plugin is not installed.
2018-04-18 10:07:50.404873-0400 Safety[8835:3792840] WARN: Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic'

Exploring the Staging folder for the platforms/ios/MyApp.xcworkspace within Xcode, the subfolders www, plugins and cordova.plugins.diagnostic are visible.  However, where cordova-plugin-camera, cordova-plugin-device, etc. all show subfolders, within Xcode, cordova.plugins.diagnostic shows *NO* subfolder.  (Finder shows that the cordova.plugins.diagnostics folder *does* include the full contents www/ios/diagnostic*.js

**NOTE:** Within the Xcode project view of the Staging/www/plugins folders, changing the name of the folder cordova.plugins.diagnostic to cordova-plugins-diagnostic caused the subfolders to become visible within cordova-plugins-diagnostic.

**Expected behavior:**

Calling this.diagnostic.switchToLocationSettings(); causes the MyApp to switch to the Settings app.

**Steps to reproduce:**

1. Build with Xcode 9.3, run on iOS 11.3, using Ionic Native Diagnostic wrapper...
2. Invoke  this.diagnostic.switchToLocationSettings();

import { Injectable } from '@angular/core';
import { Diagnostic } from '@ionic-native/diagnostic';
@Injectable()
export class LocationService {
    constructor(private diagnostic: Diagnostic) {}
    public test(): void {
        this.diagnostic.switchToLocationSettings();
    }
}

**Environment information**

- Cordova CLI version 
8.0.0
- Cordova platform version
Installed platforms:
  android 7.0.0
  browser 5.0.3
  ios 4.5.4
- Plugins & versions installed in project (including this plugin)
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.5 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"

Xcode 9.3
Build version 9E145

- Ionic environment info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.12 
    Node       : v6.11.1
    npm        : 5.8.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

- Installed Ionic Native modules and versions
├── @ionic-native/camera@4.5.3
├── @ionic-native/core@4.5.3
├── @ionic-native/deeplinks@4.7.0
├── @ionic-native/device@4.5.3
├── @ionic-native/diagnostic@4.5.3
├── @ionic-native/geolocation@4.5.3
├── @ionic-native/native-storage@4.5.3
├── @ionic-native/network@4.5.3
├── @ionic-native/secure-storage@4.7.0
├── @ionic-native/splash-screen@4.5.3
├── @ionic-native/status-bar@4.5.3

**Related code:**

```
        this.diagnostic.switchToLocationSettings();
```

**Console output**

<details>
<summary>console output</summary>

```
2018-04-18 10:07:50.404764-0400 Safety[8835:3792840] WARN: Native: tried calling Diagnostic.switchToLocationSettings, but the Diagnostic plugin is not installed.
2018-04-18 10:07:50.404873-0400 Safety[8835:3792840] WARN: Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic'
```

</details><br/><br/>

**Comment by dpa99c** [comment]
[switchToLocationSettings()](https://github.com/dpa99c/cordova-diagnostic-plugin#switchtolocationsettings) is not supported on the iOS platform. See #291.
