### ISSUE TITLE
Repo documentation lists non-existent function

### ISSUE THREAD

**Issue by calummackervoy** [dpa99c/cordova-diagnostic-plugin#298]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ ] feature request
- [X ] documentation issue

https://github.com/dpa99c/cordova-diagnostic-plugin#requestremotenotificationsauthorization
Lists a function "requestRemoteNotificationsAuthorization()" which doesn't appear to exist in the codebase, and is not listed in ionic docs for the plugin: https://ionicframework.com/docs/native/diagnostic/

**Comment by dpa99c** [comment]
It exists [for iOS](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Notifications.m#L205).

If it's not documented in Ionic Native then [raise an issue against it](https://github.com/ionic-team/ionic-native/issues)

**Comment by fermedina** [comment]
Maybe you should change the signature of the method like [isCameraAvailable](https://github.com/dpa99c/cordova-diagnostic-plugin#iscameraavailable).

The current signature is not supported for ionic-native
