### ISSUE TITLE
Feature Request [Helping cordova-plugin-xapkreader move app/obb to external storage]

### ISSUE THREAD

**Issue by BobAchgill** [dpa99c/cordova-diagnostic-plugin#299]
I see that cordova-diagnostic-plugin has the ability to access the path to external (removable) storage.  Can a feature be added to cordova-diagnostic-plugin [to enable cordova-plugin-xapkkreader to support moving an Adroid app and obb expansion file to the external storage](https://github.com/agamemnus/cordova-plugin-xapkreader/issues/122)?

**Comment by dpa99c** [comment]
[getExternalSdCardDetails()](https://github.com/dpa99c/cordova-diagnostic-plugin#getexternalsdcarddetails) will provide the filepath(s) to external removable storage locations.

These filepaths can be used along with `cordova-plugin-file` to read/write files to this location. Or you could enhance `cordova-plugin-xapkreader` to do this. 

No changes are required to this plugin to make this happen hence closing this.

**Comment by BobAchgill** [comment]
Thanks Dave!


If all I need is the getExternalSdCardDetails()  functionality ...is it a problem to use cordova-diagnostic-plugin with cordova 6.5.0?


That is what cordova-plugin-xapkreader is written for... no higher.


Thanks!

Bob Achgill


________________________________

**Comment by dpa99c** [comment]
This plugin will work with both `cordova-android@6` and `cordova-android@7`

**Comment by dpa99c** [comment]
[cordova-android](https://github.com/apache/cordova-android) refers to the Cordova library used to build the native Android app. 

This differs from [cordova](https://github.com/apache/cordova-cli) which is the CLI tool used to run the build process.

The version of `cordova-android` bears no relation to the version of the Android operating system running on a target device; any version of `cordova-android` used to build an app will run on any **supported** version of Android.

Subsequent versions of `cordova-android` change both the minimum support Android version and the SDK version used to compile the app: see the [release notes](https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md) for details.

**Comment by BobAchgill** [comment]
Dave,


When you said...

"From Android 5.0 onwards, the location of the external (removable) SD is no longer a fixed path. <https://stackoverflow.com/questions/45770040/external-storage-path-sd-card-for-android-5-1-1-and-later-with-cordova?rq=1> "


You are referring to the user's device Android level?  Not Cordova Android level or Cordova CLI Android level?  Correct?

So compiling using Cordova Android level less than 5 will not get around my issue.  Your statement of from Android 5.0 onwards is a device issue.

Correct?

Thanks!
Bob

________________________________
