### ISSUE TITLE
isLocationEnabled needs GPS enabled for returning true on Android

### ISSUE THREAD

**Issue by iwan-uschka** [dpa99c/cordova-diagnostic-plugin#3]
Is there a reason for only checking GPS when calling `isLocationEnabled` on Android?

https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L89

Why not doing something like this?

`callbackContext.success((isGpsEnabled() || isNetworkEnabled()) ? 1 : 0);`

Just tested it on Android 4.4.4. It worked like a charm.

Because you write something about GPS has to be enabled to get true for `isLocationEnabled` in your readme explicitly, i think there must be a reason for this.

Thanks and greetings
wanja

**Comment by dpa99c** [comment]
Hi Wanja, 

I originally intended `isLocationEnabled()` on Android to be an equivalent of the iOS variant -  it was intended to mean "is the app good to go for high-accuracy location tracking", e.g. a navigation app. On iOS, `isLocationEnabled()` returns true if the app is authorized to use location AND location services are enabled. On iOS there's no way to tell if the device is using high-accuracy (GPS) or low-accuracy (network/WiFi) but on Android there is. 

I guess I could change the semantics of `isLocationEnabled()` for Android, but given that many people are using this plugin in their apps, it may cause them issues. So I think maybe it would be better if I explicitly exposed `isGpsEnabled()` and `isNetworkEnabled()` via the JS API as `isGpsEnabled()` and `isNetworkLocationEnabled()`

Then you could do something like this:

    cordova.plugins.diagnostic.isNetworkLocationEnabled(function(networkLocationEnabled){
        cordova.plugins.diagnostic.isGpsEnabled(function(gpsEnabled){
            if(gpsEnabled){
                console.log("High accuracy location enabled");
            }else if(networkLocationEnabled){
                console.log("Low accuracy location enabled");
            }else{
                console.log("No location enabled");
            }
        }, errorCallback);
    }, errorCallback);

What do you think?

**Comment by iwan-uschka** [comment]
Hey, thanks for answering.
You're totally right. You cannot change 'isLocationEnabled()' if so many people would be affected.
To provide `isGpsEnabled()` and `isNetworkLocationEnabled()` via JS API would be great.
Please add this feature.
Thank you for a great plugin anyway.

Cheers from berlin
wanja

**Comment by dpa99c** [comment]
OK, I decided to update `isLocationEnabled()` on Android to return true either if GPS or network location is enabled. This is consistent with the iOS implementation. I've also added functions to individually check GPS and Network location states on Android. This has been done as a major version increase to 2.0.0, so anyone relying on the old interface can use `cordova.plugins.diagnostic@1`

**Comment by iwan-uschka** [comment]
Just implemented.
Thank you very much!
