### ISSUE TITLE
requestLocationAuthorization no return value

### ISSUE THREAD

**Issue by jeffreyramia** [dpa99c/cordova-diagnostic-plugin#300]
Calling `diagnostic.requestLocationAuthorization` never returns any value.
It would be nice to know that the request failed even if the user previously chose not to allow access to location.

**Comment by dpa99c** [comment]
The function does not _return_ a value because the operation is asynchronous.
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization), the outcome of the user choice is passed to the `successCallback` function.
