### ISSUE TITLE
isGpsLocationEnabled triggering multiple times

### ISSUE THREAD

**Issue by jijishthomas** [dpa99c/cordova-diagnostic-plugin#302]
**I'm submitting a ...**  (check one with "x"):
- [ x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
I am using isGpsLocationEnabled() to check whether device's gps is enabled or not. The isGpsLocationEnabled is triggering two times!

**Expected behavior:**
isGpsLocationEnabled should trigger only one time and prompt user to enable it.

**Comment by dpa99c** [comment]
This is insufficient information to determine if an issue exists with the plugin. Please do the following:

- Complete the full issue template, including details of build and test environments
- If possible, give a code example of how the function in question is being called
- Build/run/test the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) 
  - to determine whether the issue can be reproduced in a known codebase 
  - to eliminate the possibility that the observed behaviour arises from a bug in your own code and not the plugin
  - post the results of testing in this issue

If the above information is not provided, the issue will be deemed invalid and closed.

**Comment by dpa99c** [comment]
Closed due to no response from OP
