### ISSUE TITLE
requestMicrophoneAuthorization callback procs at wrong time

### ISSUE THREAD

**Issue by jhiswin** [dpa99c/cordova-diagnostic-plugin#306]
I need to be able to react to when a user allows or denies authorization.  Callback function when a request is made is not useful.  Cannot find a way to do this without setting a background timer to continuously check permission status.

Added directly using `cordova plugin add cordova.diagnostic.plugin`

The callback is executing in parallel to the authorization request. Does not wait for user to "Allow" or "Deny" request.

cordova.plugins.diagnostic.requestMicrophoneAuthorization(function(status){
console.log(status);
});

status value is showing status before user presses a button

Also tried registerPermissionRequestCompleteHandler to no avail.

**Comment by jhiswin** [comment]
Found that you have to request the permission status again.  The parameter given to the callback represents the status before user interaction.

**Comment by dpa99c** [comment]
I've just investigated this and found that in the latest version of the plugin (v4.0.6), the success callback in being invoked correctly by `requestMicrophoneAuthorization()` only once the user has reponded to the runtime permissions dialog.

To reproduce my test case, please do the following:
- Build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for Android
- Use Chrome Developer Tools to inspect the app Webview and place a breakpoint on [line 84 of index.js](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L84)
- Scroll down and press the "Request Microphone Authorization" button
- Observe that the breakpoint in the success callback is not invoked until you respond to the native runtime permission dialog


FYI: while looking into this, I discovered [a typo in the JS layer of the microphone module for Android](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/4.0.6/www/android/diagnostic.microphone.js#L79):
it should define `Diagnostic_Microphone.requestMicrophoneAuthorization`, not `Diagnostic.requestMicrophoneAuthorization`.
This causes it to override the [definition in the core module](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L1078), but does not lead to the behaviour described in your issue.
I'll fix the typo in the next release of this plugin.

**Comment by dpa99c** [comment]
Closed due to no response
