### ISSUE TITLE
Does not detect "don't ask again" denied permissions

### ISSUE THREAD

**Issue by jhiswin** [dpa99c/cordova-diagnostic-plugin#307]
Does not detect "don't ask again" denied permissions.  Tested on Android 7.0

**Comment by dpa99c** [comment]
Testing using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example), I observe that in the latest version of the plugin (v4.0.6) the behaviour is correct with regard to detection of the `DENIED_ALWAYS` ("Don't ask again") runtime permission state on Android.

To reproduce my test case, please do the following:
- Build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for Android
- Scroll down and press the "Request Microphone Authorization" button
- Press "Deny" in the native permissions dialog
- Use Chrome Developer Tools to inspect the app Webview and place a breakpoint on [line 84 of index.js](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/www/js/index.js#L84)
- Press the "Request Microphone Authorization" button again
- Check the "Don't ask again" box and press "Deny" in the native permissions dialog
- Observe that when the breakpoint is hit, the value of `status` is `DENIED_ALWAYS`


Tested on Nexus 6P running Android 8.1.

**Comment by dpa99c** [comment]
Closed due to no response
