### ISSUE TITLE
Building using XCode 9 on IOs fails

### ISSUE THREAD

**Issue by vinceharmon** [dpa99c/cordova-diagnostic-plugin#308]
[X ] bug report
# Bug report

I'm trying to build the latest plugin on IOs.  

**After adding in the diagnostics plugin and compiling in XCode 9 I get a linker error:**

Showing Recent Errors Only
Ld DerivedData/Build/Intermediates.noindex/PinQuest\ Game\ DEV.build/Debug-iphoneos/PinQuest\ Game\ DEV.build/Objects-normal/arm64/PinQuest\ Game\ DEV normal arm64
    cd /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -L/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos -L/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos/GoogleToolboxForMac -L/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos/Protobuf -L/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos/nanopb -F/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos -F/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/Pods/FirebaseMessaging/Frameworks -FPinQuest\ Game\ DEV/Plugins/com.googlemaps.ios -FPinQuest\ Game\ DEV/Plugins/cordova-plugin-stripe -filelist /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest\ Game\ DEV.build/Debug-iphoneos/PinQuest\ Game\ DEV.build/Objects-normal/arm64/PinQuest\ Game\ DEV.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest\ Game\ DEV.build/Debug-iphoneos/PinQuest\ Game\ DEV.build/Objects-normal/arm64/PinQuest\ Game\ DEV_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Products/Debug-iphoneos/libCordova.a -lz -weak_framework SystemConfiguration -framework CoreTelephony -framework CoreLocation -weak_framework WebKit -weak_framework AudioToolbox -weak_framework ImageIO -framework AVFoundation -framework Accelerate -framework CoreData -framework CoreText -framework CoreImage -framework GLKit -lc++ -framework OpenGLES -framework QuartzCore -framework UIKit -framework GoogleMapsBase -framework GoogleMaps -framework GoogleMapsCore -weak_framework MessageUI -lPods-PinQuest\ Game\ DEV -framework Stripe -framework EventKit -framework EventKitUI -framework Photos -framework UserNotifications -framework Contacts -framework AddressBook -Xlinker -dependency_info -Xlinker /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest\ Game\ DEV.build/Debug-iphoneos/PinQuest\ Game\ DEV.build/Objects-normal/arm64/PinQuest\ Game\ DEV_dependency_info.dat -o /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest\ Game\ DEV.build/Debug-iphoneos/PinQuest\ Game\ DEV.build/Objects-normal/arm64/PinQuest\ Game\ DEV

duplicate symbol _diagnostic in:
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Location.o
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Wifi.o
duplicate symbol _diagnostic in:
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Location.o
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Camera.o
duplicate symbol _diagnostic in:
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Location.o
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Notifications.o
duplicate symbol _diagnostic in:
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Location.o
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Contacts.o
duplicate symbol _diagnostic in:
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Location.o
    /Users/administrator/Projects/App/com.pinquestgolf.game.dev/platforms/ios/DerivedData/Build/Intermediates.noindex/PinQuest Game DEV.build/Debug-iphoneos/PinQuest Game DEV.build/Objects-normal/arm64/Diagnostic_Calendar.o
ld: 5 duplicate symbols for architecture arm64
clang: 

**error: linker command failed with exit code 1 (use -v to see invocation)**

**I am able to build the plugin for Android and it's working fine.**

**Environment information**
Cordova version: 8.0.0
IOs cordova: 4.5.4

cordova-android-support-gradle-release 1.3.0 "cordova-android-support-gradle-release"
cordova-instagram-plugin 0.5.6 "Instagram"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-cocoapod-support 1.3.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase-analytics 0.13.0 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.0 "Cordova sqlite storage plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"
cordova-universal-clipboard 0.1.0 "Clipboard"
cordova.plugins.diagnostic 4.0.7 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"

Node: 8.4.0

Regards,
Vince

**Comment by dpa99c** [comment]
Fix published to npm in v4.0.8
