### ISSUE TITLE
NFC and Location receivers found in Android Manifest when not used

### ISSUE THREAD

**Issue by russcarver** [dpa99c/cordova-diagnostic-plugin#314]
**I'm submitting a ...**  (check one with "x"):
- [X ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

When not using Location or NFC for the plugin, the Android manifest file is still populated with related receivers.

I'm using the plugin with the following in config.xml:

<preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />

The following appears in the AndroidManifest.xml file:

        <receiver android:name="cordova.plugins.Diagnostic$LocationProviderChangedReceiver">
            <intent-filter>
                <action android:name="android.location.PROVIDERS_CHANGED" />
            </intent-filter>
        </receiver>
        <receiver android:name="cordova.plugins.Diagnostic$NFCStateChangedReceiver">
            <intent-filter>
                <action android:name="android.nfc.action.ADAPTER_STATE_CHANGED" />
            </intent-filter>
        </receiver>

During our security scan of the app, we get the following (which our company does not allow without justification).  And since we aren't using Location services or NFC, we need these to be removed.

Broadcast Receiver(cordova.plugins.Diagnostic$LocationProviderChangedReceiver) is not Protected.An intent-filter exists. | high | A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Broadcast Receiver is explicitly exported.

Broadcast Receiver(cordova.plugins.Diagnostic$NFCStateChangedReceiver) is not Protected.An intent-filter exists. | high | A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Broadcast Receiver is explicitly exported.

**Expected behavior:**

If the plugin configuration lists a set of modules to use and does not include LOCATION or NFC, then these should not appear in the Android manifest file.

**Environment information**

cli packages: (/Users/ruscarver/Documents/Code/transamerica-cx-ionic/node_modules)

    @ionic/cli-plugin-proxy : 1.5.6
    @ionic/cli-utils        : 1.19.1
    ionic (Ionic CLI)       : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.9.3
    npm               : 6.0.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145
    Gradle           : 4.1
    targetSdkVersion:  26

Plugins:
com.telerik.plugins.healthkit 0.5.5 "HealthKit"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-advanced-http 1.9.1 "Advanced HTTP plugin"
cordova-plugin-android-fingerprint-auth 1.4.3 "FingerprintAuth"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase-analytics 0.12.1 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-crashlytics 0.0.6 "Cordova Firebase Crashlytics Plugin"
cordova-plugin-health 1.0.2 "Cordova Health"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-iroot 0.7.0 "iRoot"
cordova-plugin-keyboard 1.1.5 "Keyboard"
cordova-plugin-krux 1.0.0 "Krux"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-privacyscreen 0.3.1 "PrivacyScreenPlugin"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-secure-key-store 1.5.4 "SecureKeyStore"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.1.1 "Cordova sqlite storage plugin"
cordova-support-google-services 1.0.0 "cordova-support-google-services"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
profile-image-crop 0.0.5 "Circular Image Cropper for Profile Image"
	
- Android SDK details
Installed packages:.
  build-tools;27.0.3                                  | 27.0.3  | Android SDK Build-Tools 27.0.3                  | build-tools/27.0.3/
  emulator                                            | 27.1.12 | Android Emulator                                | emulator/
  extras;android;m2repository                         | 47.0.0  | Android Support Repository                      | extras/android/m2repository/
  extras;google;google_play_services                  | 48      | Google Play services                            | extras/google/google_play_services/
  extras;google;m2repository                          | 58      | Google Repository                               | extras/google/m2repository/
  extras;intel;Hardware_Accelerated_Execution_Manager | 6.2.1   | Intel x86 Emulator Accelerator (HAXM installer) | extras/intel/Hardware_Accelerated_Execution_Manager/
  patcher;v4                                          | 1       | SDK Patch Applier v4                            | patcher/v4/
  platform-tools                                      | 27.0.1  | Android SDK Platform-Tools                      | platform-tools/
  platforms;android-21                                | 2       | Android SDK Platform 21                         | platforms/android-21/
  platforms;android-22                                | 2       | Android SDK Platform 22                         | platforms/android-22/
  platforms;android-23                                | 3       | Android SDK Platform 23                         | platforms/android-23/
  platforms;android-24                                | 2       | Android SDK Platform 24                         | platforms/android-24/
  platforms;android-25                                | 3       | Android SDK Platform 25                         | platforms/android-25/
  platforms;android-26                                | 2       | Android SDK Platform 26                         | platforms/android-26/
  platforms;android-27                                | 1       | Android SDK Platform 27                         | platforms/android-27/
  sources;android-21                                  | 1       | Sources for Android 21                          | sources/android-21/
  sources;android-22                                  | 1       | Sources for Android 22                          | sources/android-22/
  sources;android-23                                  | 1       | Sources for Android 23                          | sources/android-23/
  sources;android-24                                  | 1       | Sources for Android 24                          | sources/android-24/
  sources;android-25                                  | 1       | Sources for Android 25                          | sources/android-25/
  sources;android-26                                  | 1       | Sources for Android 26                          | sources/android-26/
  sources;android-27                                  | 1       | Sources for Android 27                          | sources/android-27/
  system-images;android-24;google_apis;x86            | 20      | Google APIs Intel x86 Atom System Image         | system-images/android-24/google_apis/x86/
  system-images;android-25;google_apis;x86            | 11      | Google APIs Intel x86 Atom System Image         | system-images/android-25/google_apis/x86/
  tools                                               | 26.1.1  | Android SDK Tools                               | tools/
	
Ionic Native Info:
├── @ionic-native/camera@4.5.2
├── @ionic-native/core@4.5.2
├── @ionic-native/date-picker@4.5.2
├── @ionic-native/device@4.5.2
├── @ionic-native/diagnostic@4.5.2
├── @ionic-native/file@4.5.2
├── @ionic-native/firebase-analytics@4.5.2
├── @ionic-native/health@4.5.2
├── @ionic-native/http@4.5.2
├── @ionic-native/in-app-browser@4.5.2
├── @ionic-native/keyboard@4.5.2
├── @ionic-native/network@4.5.2
├── @ionic-native/screen-orientation@4.5.2
├── @ionic-native/splash-screen@4.5.2
├── @ionic-native/status-bar@4.5.2
├── @ionic-native/touch-id@4.5.2

**Comment by dpa99c** [comment]
It appears from your list of plugins that you're using v3.9.2 of this plugin:

> cordova.plugins.diagnostic 3.9.2 "Diagnostic"

The rework of this plugin into modules wasn't carried out until v4 - the latest version is v4.0.8

Please check you are using the most recent version.

**Comment by dpa99c** [comment]
Closed due to no response from OP
