### ISSUE TITLE
Cannot read property 'switchToLocationSettings' of undefined

### ISSUE THREAD

**Issue by pradeepaanumalla** [dpa99c/cordova-diagnostic-plugin#315]
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { HomePage } from '../pages/home/home';
import { Diagnostic } from '@ionic-native/diagnostic';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;
  constructor(public platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen,
              public diagn: Diagnostic) {
    platform.ready().then(() => {
        // Okay, so the platform is ready and our plugins are available.
        // Here you can do any higher level native things you might need.
        this.diagn.registerLocationStateChangeHandler(function(state){
        console.log(state);
        if(state === 'location_off'){
             alert('location disabled');
             this.diagn.switchToLocationSettings();
             // this.test();        
        }else{
             alert('location enabled');
        }

        });
        statusBar.styleDefault();
        splashScreen.hide();
    });
  }
}

On executing this code i am getting an error like this.What I want to do is,if the location is disabled i want to navigate it to location settings page.

**Comment by dpa99c** [comment]
Since you didn't fill out the issue template, you haven't specified which platform you are testing on, so I'm going to guess you're testing this on iOS, but [as documented](https://github.com/dpa99c/cordova-diagnostic-plugin#switchtolocationsettings) `switchToLocationSettings()` is only supported on Android and Windows platforms.

**Comment by pradeepaanumalla** [comment]
No,Iam working on Android

**Comment by dpa99c** [comment]
That's why we have an issue template - so I don't have to play the "guess your test environment" game.

You are calling the plugin via the [Ionic Native Typescript wrapper](https://ionicframework.com/docs/native/diagnostic/).

Check if function can be called directly via the Javascript plugin API:

    cordova.plugins.diagnostic.switchToLocationSettings();

**Comment by dpa99c** [comment]
Closed due to no response from OP
