### ISSUE TITLE
locationavailable and locationenabled -ios

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-diagnostic-plugin#319]
I want to detect user's gps location not network location. So I let users use app only when they turn on location service (gps).
So I should detect whether they turn on location service(gps) or not.  So I must use these functions
. But I don't know whether locationavailable returns true although users turn off location service. Also I don't know whether locationenabled detect only gps location enabled or location (gps+network) enabled.

**Comment by dpa99c** [comment]
On iOS (unlike Android), there is no way to distinguish if the the device is using GPS vs network location - iOS does not give this information. The only way you can do this is to inspect the `accuracy` property of each position object that is returned - for example if the accuracy is > 20 metres, it's likely to be a network location or if < 20 metres, it's likely to be a GPS location.

Closing this issue as it's not related to the plugin itself but to native iOS behaviour.
