### ISSUE TITLE
Bluetooth permission getting added to AndroidManifest.xml regardless of config.xml settings

### ISSUE THREAD

**Issue by kevinswartz** [dpa99c/cordova-diagnostic-plugin#323]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Hi guys, thanks so much for your work on this plugin.  I'm having a hard time getting modules to work as documented.  Bluetooth permission seems to be getting added regardless of my settings.  Before I install, I'm looking in my platforms/android/AndroidManifest.xml file and do not see any entries for Bluetooth.  I add this to my config.xml file:
`<preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />`
...and then call `ionic cordova plugin add cordova.plugins.diagnostic`

The plugin installs successfully, and afterwards I look in my platforms/android/AndroidManifest.xml file, and I see this: `<uses-permission android:name="android.permission.BLUETOOTH" />`

I've tried clearing out my node_modules/ and reinstalling, I've also tried re-installing the android platform.  No luck, the bluetooth permission always gets added.  I have no reference to bluetooth in my code anywhere I can find.

**Expected behavior:**

I would expect `<uses-permission android:name="android.permission.BLUETOOTH" />` to not show up in my AndroidManifest.xml file

**Environment information**

- Cordova CLI version 
	- 6.5.0
- Cordova platform version
	Installed platforms:
          android 6.3.0
          browser 4.1.0
          ios 4.5.2
- Plugins & versions installed in project (including this plugin)
   com.megster.cordova.FileChooser 0.0.0 "File Chooser"
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-clipboard 1.1.1 "Clipboard"
cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-fingerprint-auth 1.4.4 "FingerprintAuth"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-background-fetch 4.0.4 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-photo-library 2.0.4 "Photo Library"
cordova-plugin-privacyscreen 0.3.1 "PrivacyScreenPlugin"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

- Dev machine OS and version, e.g.
   ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
	
- Node JS version
    v8.11.3

>ionic info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 6.5.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.3.0 browser 4.1.0 ios 4.5.2
    Ionic Framework   : ionic1 1.3.5

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.2 
    Node       : v8.11.3
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

**Comment by dpa99c** [comment]
Your problem is you're using Cordova CLI v6.5.0 which doesn't support plugin variables. Update to the latest (v8.0.0) and this issue will go away.

What I need to do is add an `<engine>` restriction to the plugin to prevent it being installed using outdated versions of the Cordova CLI.

**Comment by kevinswartz** [comment]
That totally makes sense.  I'll try updating and get back to you.  Thanks!

**Comment by AndreasGassmann** [comment]
I'm having the same issue. The bluetooth permission always gets added. I tried your suggestion @dpa99c and updated to cordova 8.1.2 (up from cordova 7.1 I think), but the permission still gets added.

Is there anything I can do to fix it besides writing a hook to delete the permission manually?

**Comment by dpa99c** [comment]
@AndreasGassmann ensure that you added the `<preference>` to your `config.xml` before you added the plugin and android platform to your project. If not, you'll need to remove the android platform and plugin then re-add both to make there preference take effect (see the [Specifying modules](https://github.com/dpa99c/cordova-diagnostic-plugin#specifying-modules) section).

Otherwise, I'd suggest creating an blank test project; add the preference to the `config.xml`, e.g. `<preference name="cordova.plugins.diagnostic.modules" value="" />`, before adding this plugin and the android platform.

You can check which modules are currently installed by looking inside `platforms/android/app/src/main/java/cordova/plugins`

**Comment by mirko77** [comment]
I have the preference in the `config.xml` as 

` <preference name="cordova.plugins.diagnostic.modules" value="LOCATION WIFI CAMERA NOTIFICATIONS MICROPHONE EXTERNAL_STORAGE" />`

still, I get the Bluetooth permission added.

Tried to remove the plugin and the platform but no luck

`cordova 8.1.2`, plugin version `5.0.1`

**Comment by rpragesh** [comment]
@mirko77 did you fixed it? i am also having the same problem

**Comment by mirko77** [comment]
> @mirko77 did you fixed it? i am also having the same problem

I had to write a hook to remove unwanted permissions, placed it in `after_prepare`

```

#!/usr/bin/env node
'use strict';
var permissionsToRemove = ['BLUETOOTH', 'WAKE_LOCK', 'FOREGROUND_SERVICE', 'BACKGROUND_SERVICE'];

var fs = require('fs');
var path = require('path');
var rootdir = '';
var manifestFile = path.join(rootdir, 'platforms/android/app/src/main/AndroidManifest.xml');

fs.readFile(manifestFile, 'utf8', function (err, data) {
    if (err) {
        return console.log(err);
    }

    var result = data;
    for (var i = 0; i < permissionsToRemove.length; i++) {

        console.log('Removing: <uses-permission android:name="android.permission.' + permissionsToRemove[i] + '" />');
        result = result.replace(
            '<uses-permission android:name="android.permission.' + permissionsToRemove[i] + '" />', '');
    }

    fs.writeFile(manifestFile, result, 'utf8', function (err) {
        if (err) {
            return console.log(err);
        }
    });
});


```

**Comment by rpragesh** [comment]
it worked...Thanks a ton for the reply
