### ISSUE TITLE
Android custom permission messages

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#325]
Can custom permission messages be made for Android similar to how iOS uses `NSLocationAlwaysAndWhenInUseUsageDescription` to create custom permission messages?

I can't find any variable or documentation referring to it.  Is it simply adding `<string>My custom permission message</string>` to each feature in the Android section?

**Comment by dpa99c** [comment]
Unfortunately on Android the permission messages are hard-coded into the OS. The most common workaround for this is to display a pre-emptive dialog in your app explaining why you are about to ask for a given permission before actually requesting it and displaying the system dialog.

**Comment by rolinger** [comment]
ugh, I feared that.  Either more popups which annoy users....or not being able to explain why causing users to say "no" to the permission.  Not good choices.
