### ISSUE TITLE
Proposition regarding change handlers in the ionic native wrapper to return an Observable instead of having a synced callback

### ISSUE THREAD

**Issue by somq** [dpa99c/cordova-diagnostic-plugin#329]
**I'm submitting a ...**
- Feature request / improvement proposition

# Feature request

**Current behavior:**

Currently the ionic native wrapper let us pass a function to be called back for any change handlers.

**Expected behavior:**

For convenient reasons I think it would be better to have these handlers return an observable instead.

**Steps to reproduce:**

Current usage makes impossible to **directly** add `registerBluetoothStateChangeHandler` to an rx stream.

```ts
this.BTStateChangeHandler = new Subject()

this.diagnosticPlugin.registerBluetoothStateChangeHandler(BTState => {
  this.BTStateChangeHandler.next(BTState)
})
...
```

Cordova implementation is simple ([source](https://github.com/ionic-team/ionic-native/blob/v5/src/%40ionic-native/plugins/diagnostic/index.ts#L461)):

```ts
  /**
   * Registers a function to be called when a change in Bluetooth state occurs.
   * @param {Function} handler
   */
  @Cordova({ platforms: ['Android', 'iOS'], sync: true })
registerBluetoothStateChangeHandler(handler: Function): void {}
```
would become
```ts
  /**
   * Registers a function to be called when a change in Bluetooth state occurs.
   * @returns {Observable<any>}
   */
  @Cordova({ "callbackOrder": "reverse", "observable": true, "platforms": ["Android", "iOS"] })
registerBluetoothStateChangeHandler(): Observable<any>;
```
I listed these methods:
 * registerBluetoothStateChangeHandler
 * registerLocationStateChangeHandler
 * registerPermissionRequestCompleteHandler
 * registerNFCStateChangeHandler

These handlers are exactly what Observables are meant for, a stream where it can be nexted a new value anytime.

Let me know what you think about this idea and if there is some things that has to be taken into consideration such as managing the breaking change, or maybe adding other methods aswell for instance. 

I can also prepare the pull request if needed.

**Comment by dpa99c** [comment]
This repo contains the Cordova plugin code consisting of the native code and pure Javascript plugin API.

The [Ionic Native typescript wrapper](https://github.com/ionic-team/ionic-native/blob/v5/src/%40ionic-native/plugins/diagnostic/index.ts) that wraps this plugin belongs to the [ionic-native](https://github.com/ionic-team/ionic-native/) repo and therefore any suggestions/improvements should be opened on its [issues page](https://github.com/ionic-team/ionic-native/issues), not this plugin's.

**Comment by somq** [comment]
Of course it belongs to ionic-native. In fact I could even had directly prepare a PR for ionic-native repo but I wanted to have your opinion before doing anything that would break the existing.
I'm forwarding this issue on the ionic-native repo. 
If you want to, let me know what you think of this idea [here](https://github.com/ionic-team/ionic-native/issues/2786) then please.

Thanks for your time.
