### ISSUE TITLE
Android check for internet access via mobile network (not via wifi)

### ISSUE THREAD

**Issue by JeremyColton** [dpa99c/cordova-diagnostic-plugin#331]
Great plugin! 

On Android, I read that the `isWifiAvailable()` method checks if there's a wifi connection. But wifi can be enabled and there is internet provided via the phone's "Mobile network > Mobile data" setting. Is there a method to check for this alternate internet connectivity?

Or should I simply use the browser's `navigator.connection.type` API which deteremines if there's an internet connection?

**Comment by dpa99c** [comment]
Use `cordova-plugin-network-information` to determine the connection type
