### ISSUE TITLE
[FEATURE] Destroy Location change Listener

### ISSUE THREAD

**Issue by Karanveer-logiciel** [dpa99c/cordova-diagnostic-plugin#334]
How its possible to destroy a location listener ?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#registerlocationstatechangehandler):

> Pass in a falsey value to de-register the currently registered function.

    cordova.plugins.diagnostic.registerLocationStateChangeHandler(false);
