### ISSUE TITLE
can't install plugin

### ISSUE THREAD

**Issue by kirilldonenko** [dpa99c/cordova-diagnostic-plugin#336]
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

cordova plugin add cordova.plugins.diagnostic --verbose
No scripts found for hook "before_plugin_add".
No version specified for cordova.plugins.diagnostic, retrieving version from config.xml
No version for cordova.plugins.diagnostic saved in config.xml or package.json
Attempting to use npm info for cordova.plugins.diagnostic to choose a compatible release
Running command: cmd "/s /c ""C:\Program Files\NodeJS\npm.cmd" view cordova.plugins.diagnostic --json""
Command finished with error code 0: cmd /s /c ""C:\Program Files\NodeJS\npm.cmd" view cordova.plugins.diagnostic --json"
Running command: cmd "/s /c "C:\users\master\PhpstormProjects\mobapp\platforms\browser\cordova\version.bat""
Command finished with error code 0: cmd /s /c "C:\users\master\PhpstormProjects\mobapp\platforms\browser\cordova\version.bat"
Calling plugman.fetch on plugin "cordova.plugins.diagnostic@4.0.10"
saving
Running command: cmd "/s /c ""C:\Program Files\NodeJS\npm.cmd" install cordova.plugins.diagnostic@4.0.10 --production --save""
Command finished with error code 1: cmd /s /c ""C:\Program Files\NodeJS\npm.cmd" install cordova.plugins.diagnostic@4.0.10 --production --save"
Failed to fetch plugin cordova.plugins.diagnostic@4.0.10 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN cordova-plugin-media@2.2.0 requires a peer of cordova-plugin-file@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for hook@0.0.5: wanted {"os":"linux,darwin,freebsd","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux,darwin,freebsd
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Master\AppData\Roaming\npm-cache\_logs\2019-01-13T18_31_37_822Z-debug.log
CordovaError: Failed to fetch plugin cordova.plugins.diagnostic@4.0.10 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN cordova-plugin-media@2.2.0 requires a peer of cordova-plugin-file@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for hook@0.0.5: wanted {"os":"linux,darwin,freebsd","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux,darwin,freebsd
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Master\AppData\Roaming\npm-cache\_logs\2019-01-13T18_31_37_822Z-debug.log
    at C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:161:37
    at _rejected (C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\Master\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
8.1.2 (cordova-lib@8.1.1)
- Cordova platform version
	- `cordova platform ls`
Installed platforms:
  browser 4.1.0
Available platforms:
  android ~7.1.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-device-orientation 1.0.7 "Device Orientation"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-websql 0.0.10 "Web SQL plugin"
phonegap-plugin-barcodescanner 4.1.0 "BarcodeScanner"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        Windows 10
_Runtime issue_
- Device details
    - _e.g. iPhone 7, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
v10.2.1
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic info`
- Installed Ionic Native modules and versions
    - `npm list | grep "@ionic-native"`

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
> npm ERR! notsup Unsupported platform for hook@0.0.5: wanted {"os":"linux,darwin,freebsd","arch":"any"} (current: {"os":"win32","arch":"x64"})

This plugin is not the cause of that error - it is caused because an npm module (`hook@0.0.5`) is attempted to be installed on an unsupported operating system (Windows). 
You should run `npm list` to list the dependency tree and find which plugin/module in your project is responsible for requesting that module.
