### ISSUE TITLE
Ionic 3 import: The diagnostic name can not be found

### ISSUE THREAD

**Issue by mrcristianciro** [dpa99c/cordova-diagnostic-plugin#337]
- [ x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

import { Diagnostic } from '@ionic-native/diagnostic';

In app.module.ts:
providers: [Diagnostic]
The type 'DiagnosticOriginal' can not be assigned to the 'Provider' type. Type 'DiagnosticOriginal' is missing the following properties from type 'FactoryProvider': provide, useFactory [2322]

In a page:
 The diagnostic name can not be found
constructor( private diagnostic: Diagnostic){}

**Environment information**

- Cordova CLI version 
	- 8.1.2 (cordova-lib@8.1.1)
- Cordova platform version
	Installed platforms:
         android 7.1.4
- Plugins & versions installed in project (including this plugin)
    cordova-plugin-device 2.0.2 "Device"
    cordova-plugin-fingerprint-aio 1.5.0 "FingerprintAllInOne"
    cordova-plugin-geolocation 4.0.1 "Geolocation"
    cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
   cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
   cordova-plugin-network-information 2.0.1 "Network Information"
   cordova-plugin-splashscreen 5.0.2 "Splashscreen"
   cordova-plugin-statusbar 2.4.2 "StatusBar"
   cordova-plugin-whitelist 1.3.3 "Whitelist"
   cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
   cordova.plugins.diagnostic 4.0.10 "Diagnostic"
- Dev machine OS and version, e.g.
    - Windows 10
        - Versión 1803
        
_Runtime issue_
- Device details
    Moto G4
- OS details
     Android 7.0	
	
_Android build issue:_	
- Node JS version
    v11.6.0

**Comment by dpa99c** [comment]
The [Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/diagnostic/index.ts) is provided and contained by [Ionic Native](https://github.com/ionic-team/ionic-native/) so please open this issue against it.

This repo contains only the plugin code itself which is the pure JS plugin API and native code components.
