### ISSUE TITLE
[Feature] Parameterize android support library to avoid conflicts with other plugins

### ISSUE THREAD

**Issue by CSobol** [dpa99c/cordova-diagnostic-plugin#338]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ x ] feature request
- [ ] documentation issue

# Feature request

- Similar to #212, this plugin will conflict with other plugins which have hard coded the version of com.android.support they require.

- Since `android >= 7.1.0` and `cordova-android >= 6.3.0`, cordova has provided a way to parameterize these requirements, allowing them to be specified with a switch at install, or a tag in the root project's config.xml

- This will set this plugin up to play nicely with other plugins which use the new/modern method of specifying a library, it will also allow it to play nicely with plugins which don't, by allowing the user to specify their version number. In addition, unlike the resolution to #212, this does not require yet another cordova plugin to address the issue.

- Install instructions will need updating to reflect the available switch.

- Relevant links
    -  https://blog.phonegap.com/the-play-services-problem-with-cordova-applications-489c9aeb2e89

I will be doing this work anyway to resolve an issue. Are you accepting PRs?

**Comment by Mapiac** [comment]
How is this going? Can I be of help @CSobol ?

**Comment by dpa99c** [comment]
Above commit published to npm in v4.0.12
