### ISSUE TITLE
isCameraPresent() return true when no camera is present

### ISSUE THREAD

**Issue by LavinNode** [dpa99c/cordova-diagnostic-plugin#339]
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

isCameraPresent() return true when no camera is present physically at all. I tried testing the method call on another handphone with camera also return true though.

The isCameraPresent() should return false when testing on handphone with no camera installed.

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- 8.1.2
- Cordova platform version
	- 7.1.4
- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.0.3 "cordova-custom-config"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.4.2 "cordova-plugin-filepath"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.3 "cordova-plugin-ionic-webview"
cordova-plugin-secure-storage 3.0.1 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"

- Dev machine OS and version, e.g.
    - Windows 10 Enterprise 2016
        
_Runtime issue_
- Device details
    - Asus Zenfone Max Pro M1 
- OS details
    - Android 8.1.0
	
_Android build issue:_	
- Node JS version
    - v10.13.0
- Gradle version
	- 4.1
- Target Android SDK version
	- 27
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
Ionic:
   ionic (Ionic CLI)  : 4.5.0 (C:\Users\limmw\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 12 other plugins)

System:
   NodeJS : v10.13.0 (D:\DevTools\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows Server 2016

- Installed Ionic Native modules and versions
+-- @ionic-native/diagnostic@4.20.0
+-- @ionic-native/file@4.20.0
+-- @ionic-native/file-path@4.20.0
+-- @ionic-native/file-transfer@4.20.0
+-- @ionic-native/secure-storage@4.20.0
+-- @ionic-native/splash-screen@4.15.0
+-- @ionic-native/sqlite@4.20.0
+-- @ionic-native/status-bar@4.15.0
+-- @ionic-native/transfer@3.14.0

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
I can reproduce this on an Android emulator with no cameras configured. It seems on some devices, Android returns true for `FEATURE_CAMERA` even if no camera is present.

According to [this SO post](https://stackoverflow.com/a/25439559/777265) the solution is to actually count the number of available cameras.
