### ISSUE TITLE
App not pausing on permission request

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#340]
During my app initialization and depending on the platform I am asking for a series of permissions, I want the app to pause on each one.  It is asking for the permission but the app is flowing to the next sequence, in one case its flowing all the way to the registration screen even though the permission request is still showing on the users phone.  I would actually like to keep the app in the init state (with a spinner icon in the background).   

This is permission request is working, its poping up the request, but its not pausing the app waiting for a response:
```
    getLocationAuth()
    .then(function(status) {    // process Android Permission ==> pause here until user responds
      errMgmt("ctrl/init",31.1,'Permission - Location services: '+status) ;
      return getReadPhoneAuth() ; 
    }).then(function(status){ 
        ....do stuff...
       ...and then go to app registration page...
    })

  function getLocationAuth() {
    var q = $q.defer() ;
    cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
      if (status === cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED) {
        cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
          q.resolve(status) ;
        },function(err) {errMgmt("ctrl/init",30.1,"GPS/Location ask Permission error: "+err) }) ;
      } else {
        q.resolve(status) ;
      }
    },function(err) {errMgmt("ctrl/init",30,"GPS/Location check Permission error: "+err) });
    return q.promise ;
  }
```

**Comment by dpa99c** [comment]
If you place a debug breakpoint here:

        cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
            q.resolve(status) ; <= HERE
        },function(err) {errMgmt("ctrl/init",30.1,"GPS/Location ask Permission error: "+err) }) ;


You should see at runtime that this breakpoint is not hit until the user has responded to the dialog since the plugin result is not sent on Android until the [permission result is received in response to the user choice](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java#L825).

**Comment by rolinger** [comment]
hmmm, if i understand you correctly, you're staying the break point is hit in the q.resolve and not happening upon request (`cordova.plugins.diagnostic.requestLocationAuthorization(function(status){`) ?

I thought I had all this working before but when I changed my permission flow due to Androids recent update for sms permissions it broke my sequencing and now the app just flows right to registration.

What can I do in the above to pause it before the q.resolve(status) since its already in the callback?

**Comment by dpa99c** [comment]
The breakpoint `<= HERE` will only be hit upon the user choosing to Accept/Deny permission in the dialog: it's invoked via the native permission result handler callback. Therefore the promise shouldn't be resolved at that breakpoint until the user has dismissed the dialog.

Add breakpoints and use step-through debugging and you should be able to see exactly what's happening.

But I don't believe this is caused by an issue with this plugin.

**Comment by rolinger** [comment]
I tested over on iPhone and the same function works properly pausing at the right moment for Location Services...but on Android it pops the permission request but the app continues on in the background

For iOS:
```
  if (isRegistered == 0 && device.platform == "iOS") {
    iosPush().then(function(status) {  <=== properly pauses here
      errMgmt("ctrl/init",30.1,'iOS Push Notification Permission: '+status) ;
      return getLocationAuth()  //  <=== properly pauses here.
    }).then(function(status) {
   ... other stuff... 
    }) ;
  }
```

For Android:
```
  if (isRegistered == 0 && device.platform == "Android") {
    getLocationAuth().then(function(status) {  // <=== permission screen appears, but app continues in background
      errMgmt("ctrl/init",31.1,'Permission - Location services: '+status) ;
      return getReadPhoneAuth() ;  // process Android Permission
    }).then(function(status){
      readPhoneState = status ;
      // BOTH plugins: DeviceInformation and SIM use READ_PHONE_STATE
      errMgmt("ctrl/init",31.2,'Permission - READ_PHONE_STATE DeviceInfo: '+status) ;
     ... other stuff ..
   }) ;
}
```

I am using plugin version 4.0.10

**Comment by dpa99c** [comment]
You haven't put the breakpoint on the plugin callback, you've put it on the promises which are outside of the logic of the plugin.

See [this screen capture](http://ge.tt/2tFYySu2) of the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) running on the Android 9 emulator and illustrating that the plugin callback is not called until the user dismisses the dialog.

**Comment by dpa99c** [comment]
Closed due to no response
