### ISSUE TITLE
phonegap Android compilation crash with v4.0.12

### ISSUE THREAD

**Issue by stsier** [dpa99c/cordova-diagnostic-plugin#341]
**I'm submitting a ...**  (check one with "x"):
- [X] bug report
- [ ] feature request
- [ ] documentation issue

v4.0.12

# Bug report

**Current behavior:**

phonegap Android compilation crash with v4.0.12 if targetSDK is set to 26
 ok for 28
 ok with v4.0.11 and targetSDK=26

You'll tell me: well, set targetSDK to 28. I'll tell you, the whitelist pluggin doesn't work with 28. Of course that's not your problem. But the whitelist pluggin is much more critical than diagnostic or other plugins. 

I think diagnistic plugin should continue working with targetSDK 26. 

Or is it a compatibility problem with other plugins ? 

**Expected behavior:**

no crash

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
 
	- `cordova -v 8.1.1`

```
<plugin name="cordova-plugin-background-mode" spec="0.7.2" />
<plugin name="cordova-plugin-customurlscheme" spec="4.3.0" />
<plugin name="cordova-plugin-device" spec="2.0.2" />
<plugin name="cordova-plugin-geolocation" spec="4.0.1" />
<plugin name="cordova-plugin-music-controls" spec="2.2.0" />
<plugin name="cordova-plugin-network-information" spec="2.0.1" />
<plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
<plugin name="cordova-plugin-whitelist" spec="1.3.3" />
<plugin name="cordova-plugin-x-socialsharing" spec="5.4.4" />
<plugin name="cordova.plugins.diagnostic" spec="4.0.11" />
```

**Comment by dpa99c** [comment]
As documented in the [changelog](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/CHANGELOG.md), v4.0.12:

- Enables default version of Android Support Library to be overridden at plugin installation via ANDROID_SUPPORT_VERSION plugin variable.
- Bumps default Android Support Library version to 28.+ to match `cordova-android@8.0.0.`

Therefore if you are targeting SDK 26, install the plugin with that support library version:

    cordova plugin add cordova.plugins.diagnostic --variable ANDROID_SUPPORT_VERSION=26.+

**Comment by stsier** [comment]
is it possible to indicate it in the config.xml file ? I build with phonegap

**Comment by dpa99c** [comment]
See this SO post: https://stackoverflow.com/a/48174073/777265

**Comment by dpa99c** [comment]
I've updated the docs to illustrate this: https://github.com/dpa99c/cordova-diagnostic-plugin#phonegap-build

**Comment by stsier** [comment]
thanks! seems to be working
