### ISSUE TITLE
cordova android app crash after permisssion asked

### ISSUE THREAD

**Issue by arvindroot** [dpa99c/cordova-diagnostic-plugin#343]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone 7, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 11.2, Android 8.1_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic info`
- Installed Ionic Native modules and versions
    - `npm list | grep "@ionic-native"`

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
This is not enough information. 

Please complete the issue template properly and in full or the issue will be closed.

**Comment by arvindroot** [comment]
cordova info
Node version: v11.10.1

Cordova version: 8.1.1
Plugins list
 <plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-camera" spec="~2.2.0" />
    <plugin name="cordova-plugin-device" spec="~1.1.2" />
    <plugin name="cordova-plugin-network-information" spec="~1.2.1" />
    <plugin name="cordova-plugin-file" spec="~4.2.0" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0" />
    <plugin name="cordova-plugin-dialogs" spec="~1.2.1" />
    <plugin name="cordova-plugin-media" spec="~2.3.0" />
    <plugin name="cordova-plugin-media-capture" spec="~1.3.0" />
    <plugin name="com.phonegap.plugins.PushPlugin" spec="https://github.com/phonegap-build/PushPlugin" />
    <plugin name="cordova-plugin-app-version" spec="https://github.com/whiteoctober/cordova-plugin-app-version" />
    <plugin name="nl.x-services.plugins.videocaptureplus" spec="https://github.com/EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin" />
    <plugin name="cordova-plugin-x-socialsharing" spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin" />
    <plugin name="cordova-plugin-insomnia" spec="https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin" />
    <plugin name="ionic-plugin-keyboard" spec="https://github.com/driftyco/ionic-plugin-keyboard" />
    <plugin name="com.telerik.plugins.nativepagetransitions" spec="https://github.com/Telerik-Verified-Plugins/NativePageTransitions" />
    <plugin name="ch.ti8m.documenthandler" spec="https://github.com/ti8m/DocumentHandler" />
    <plugin name="com.appache.videoplayer" spec="/Users/arvind/Downloads/VideoPlayer/com.appache.videoplayer" />
    <plugin name="cordova-plugin-geolocation" spec="~2.2.0" />
    <plugin name="com.hutchind.cordova.plugins.streamingmedia" spec="https://github.com/nchutchind/cordova-plugin-streaming-media" />
    <plugin name="cordova-plugin-openfilenative" spec="https://github.com/andischerer/cordova-plugin-openfilenative" />
    <plugin name="cordova-plugin-image-picker" spec="~1.1.1" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.1" />
    <plugin name="cordova-plugin-firebase" spec="0.1.20" />
    <plugin name="cordova.plugins.diagnostic" spec="^3.0.0" />
    <engine name="ios" spec="4.5.4" />
<engine name="android" spec="5.2.2"/>


Can any one help me ?

**Comment by arvindroot** [comment]
<plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-camera" spec="~2.2.0" />
    <plugin name="cordova-plugin-device" spec="~1.1.2" />
    <plugin name="cordova-plugin-network-information" spec="~1.2.1" />
    <plugin name="cordova-plugin-file" spec="~4.2.0" />
    <plugin name="cordova-plugin-file-transfer" spec="~1.5.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0" />
    <plugin name="cordova-plugin-dialogs" spec="~1.2.1" />
    <plugin name="cordova-plugin-media" spec="~2.3.0" />
    <plugin name="cordova-plugin-media-capture" spec="~1.3.0" />
    <plugin name="com.phonegap.plugins.PushPlugin" spec="https://github.com/phonegap-build/PushPlugin" />
    <plugin name="cordova-plugin-app-version" spec="https://github.com/whiteoctober/cordova-plugin-app-version" />
    <plugin name="nl.x-services.plugins.videocaptureplus" spec="https://github.com/EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin" />
    <plugin name="cordova-plugin-x-socialsharing" spec="https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin" />
    <plugin name="cordova-plugin-insomnia" spec="https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin" />
    <plugin name="ionic-plugin-keyboard" spec="https://github.com/driftyco/ionic-plugin-keyboard" />
    <plugin name="com.telerik.plugins.nativepagetransitions" spec="https://github.com/Telerik-Verified-Plugins/NativePageTransitions" />
    <plugin name="ch.ti8m.documenthandler" spec="https://github.com/ti8m/DocumentHandler" />
    <plugin name="com.appache.videoplayer" spec="/Users/arvind/Downloads/VideoPlayer/com.appache.videoplayer" />
    <plugin name="cordova-plugin-geolocation" spec="~2.2.0" />
    <plugin name="com.hutchind.cordova.plugins.streamingmedia" spec="https://github.com/nchutchind/cordova-plugin-streaming-media" />
    <plugin name="cordova-plugin-openfilenative" spec="https://github.com/andischerer/cordova-plugin-openfilenative" />
    <plugin name="cordova-plugin-image-picker" spec="~1.1.1" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.1" />
    <plugin name="cordova-plugin-firebase" spec="0.1.20" />
    <plugin name="cordova.plugins.diagnostic" spec="^3.0.0" />
    <engine name="ios" spec="4.5.4" />

**Comment by dpa99c** [comment]
- You say the Android app crashed so please provide the native crash message from the Android logcat.
- You say it crashed on asking permission; which permission?
- Note that [as documented](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions) this plugin does not add permission entries to the AndroidManifest, so you need to do this manually in the `config.xml`.

**Comment by dpa99c** [comment]
> file:///storage/emulated/0/Android/data/cache/.Pic.jpg exposed beyond app through ClipData.Item.getUri() 

This is totally unrelated to this plugin

**Comment by arvindroot** [comment]
permission lists
 <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="com.root.JSS.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.root.JSS.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

**Comment by arvindroot** [comment]
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="com.root.JSS.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.root.JSS.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECORD_VIDEO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

**Comment by dpa99c** [comment]
Listing all the permissions in the AndroidManifest does not help.

Please be specific about which permission is being requested to cause the crash and post the exact error message from the Android logcat which caused the crash. 

If this relates to a call to a function in this plugin, please specify which function and give a code example of how the function is being called.

**Comment by dpa99c** [comment]
Closed due to no response from OP
