### ISSUE TITLE
Please help me m stuck in this issue since 3 days now. Plugin is shown in console. But when i add any functionality it say plugin not installed.

### ISSUE THREAD

**Issue by satyam41295** [dpa99c/cordova-diagnostic-plugin#345]
### See the error log:

[Log] using this (4) (main.js, line 1)
e {REQUEST_PRIORITY_NO_POWER: 0, REQUEST_PRIORITY_LOW_POWER: 1, REQUEST_PRIORITY_BALANCED_POWER_ACCURACY: 2, REQUEST_PRIORITY_HIGH_ACCURACY: 3, SUCCESS_SETTINGS_SATISFIED: 0, …}
e {reverseGeocode: function, forwardGeocode: function}
e {permission: Object, locationAuthorizationMode: {ALWAYS: "always", WHEN_IN_USE: "when_in_use"}, permissionGroups: Object, locationMode: Object, bluetoothState: Object, …}
e {watchPosition: function, getCurrentPosition: function}
[Warning] Native: tried calling Diagnostic.isLocationEnabled, but the Diagnostic plugin is not installed. (vendor.js, line 1)
[Warning] Install the Diagnostic plugin: 'ionic cordova plugin add cordova.plugins.diagnostic' (vendor.js, line 1)

### Here is My Code :

 if(this.platform.is('ios')){
     
      console.log('using this',this.locationAccuracy,this.nativeGeocoder,this.diagnostic,this.geolocation);
      this.diagnostic.isLocationEnabled().then((isAvailable:boolean)=>{
        console.log(isAvailable);

      })
    
    }

### Here is my Plugins List:

> cordova plugin ls
com-darryncampbell-cordova-plugin-intent 1.1.5 "Intent Shim"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-appsflyer-sdk 4.4.15 "AppsFlyer"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 3.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.2.1 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-networkinterface 2.0.0 "NetworkInterface"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-telerik-imagepicker 2.2.4 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

**Comment by satyam41295** [comment]
@dpa99c

**Comment by dpa99c** [comment]
> [Warning] Native: tried calling Diagnostic.isLocationEnabled, but the Diagnostic plugin is not installed. 
Same problem: Ionic
Raise issue with Ionic Native
