### ISSUE TITLE
Limiting permission requests using preferences

### ISSUE THREAD

**Issue by NXTAdmin** [dpa99c/cordova-diagnostic-plugin#347]
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

I am trying to use the "Specify Modules" feature to limit the modules however it appears that the permission request texts are still added to the IOS plist.

My question is: can I specify modules using Phonegap Build?

**snippet from my config.xml file:**
    
```
<preference name="cordova.plugins.diagnostic.modules" value="LOCATION BLUETOOTH WIFI NOTIFICATIONS" /> 
<gap:plugin name="cordova.plugins.diagnostic"     source="npm" version="4.0.12" />
```

**snippet from resulting plist showing camera which was not included:**
<key>NSCameraUsageDescription</key>
<string>This app requires camera access to function properly.</string>

**snippet from the Phonegap build log showing inclusion from npm:**
Fetching plugin "cordova.plugins.diagnostic@4.0.12" via npm
Installing "cordova.plugins.diagnostic" at "4.0.12" for ios
5dca859ee01d3e97f4797c0ded29de2820a47670

**Environment information**
Using cloud based Phonegap Build

**Comment by dpa99c** [comment]
This plugin uses [a nodejs script](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/scripts/apply-modules.js) executed via the [npm-scripts postinstall hook](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/package.json#L43) to comment out modules not specified by the preference in `config.xml`, including iOS plist entries.

I have tried a test build on Phonegap Build and can confirm I'm able reproduce the same outcome: despite the preference in the `config.xml` specifying none but the default module, I still see the plist entries for all modules appear in the compiled IPA. 

So my conclusion is that Phonegap Build doesn't support [npm-scripts hooks](https://docs.npmjs.com/misc/scripts) and therefore the postinstall script on which this plugin relies to comment out unwanted modules is not being executed in the Phonegap Build environment.

Therefore without completely reworking the module selection functionality in this plugin, it will not be possible to support module selection in the Phonegap Build environment.
I will update the documentation to make this explicitly clear.

If you'd like to request that they add support for npm-scripts hooks, I would suggest [opening a new issue against Phonegap Build](https://github.com/phonegap/build/issues/new).

Note that Phonegap Build also [doesn't support Cordova hooks](https://github.com/phonegap/build/issues/425#issuecomment-93126212), so any plugins which rely on these will also not function correctly.

**Comment by NXTAdmin** [comment]
A follow up question:  I am using 2 features of this plugin:
1) isLocationAvailable()
2) isLocationEnabled()
Can you recommend another plugin that supports these 2 features?
Thanks
