### ISSUE TITLE
[FEATURE] Open App Notification Settings

### ISSUE THREAD

**Issue by geoffreyteng** [dpa99c/cordova-diagnostic-plugin#351]
I'm submitting a ... (check one with "x"):

  bug report
[X ] feature request
  documentation issue

Would be useful to have a switchToNotifications() kind of function, so that the user can directly be brought into the Notifications settings page to modify their settings.

**Comment by adamduren** [comment]
I was looking for this as well. As far as iOS goes it looks like there isn't a sanctioned way of doing it. All I could find was [UIApplicationOpenExternalURLOptionsKey](https://developer.apple.com/documentation/uikit/uiapplicationopenexternalurloptionskey?language=objc) from reading the `UIApplication` doc. 

There is the plugin [Cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings) which says it can do it but reading the source code it looks like it's using an unsanctioned API so might not be reliable. 

https://stackoverflow.com/questions/47127450/app-prefsroot-notifications-id-not-working-on-ios-11-swift-4

**Comment by dpa99c** [comment]
@adamduren This would be an Android-only feature. 

Using unsanctioned APIs on iOS will lead rejection of apps containing the offending code from the App Store during Apple's app review process, so it's not worth considering.

**Comment by w4ugit** [comment]
how soon is this function planned?

**Comment by sebaferreras** [comment]
I was looking for this as well, and found that (as far as I understand) this is now possible in iOS 15.4+: 
[UIApplicationOpenNotificationSettingsURLString](https://developer.apple.com/documentation/uikit/uiapplicationopennotificationsettingsurlstring?language=objc)

Do you think this is something that could be added or would be useful to add to the plugin? Thanks :)
