### ISSUE TITLE
phonegap permission for bluetooth without bluetooth

### ISSUE THREAD

**Issue by aoreinoso** [dpa99c/cordova-diagnostic-plugin#353]
I wrote in https://stackoverflow.com/questions/51230731/phonegap-permission-for-bluetooth-without-bluetooth

Phonegap
---------
**config.xml**
<pre>
...
&lt;preference name="android-build-tool" value="gradle" />
...
&lt;preference name="phonegap-version" value="cli-8.0.0" />
...
&lt;preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />
....
&lt;plugin name="cordova.plugins.diagnostic"/>
</pre>

My app does not work with bluetooth however when installing it requires permission to link with bluetooth devices

**phonegap log**
<pre>
...
...
Fetching plugin "cordova.plugins.diagnostic" via npm
...
...
</pre>

If I erase &lt;preference name="cordova.plugins.diagnostic.modules" value="CAMERA" /> 
or I write &lt;preference name="cordova.plugins.diagnostic.modules" value="" />
everything remains the same

**I work with phonegap...<preference name="phonegap-version" value="cli-8.0.0" /> ... I dont install or re-install the plugins..**

thanks in advance

**Comment by dpa99c** [comment]
Duplicate #347 

As outlined in the [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#phonegap-build):

> **IMPORTANT:** Because Phonegap Build does not support npm-scripts hooks ([see here](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/347) for details) the module selection mechanism of this plugin will not work on Phonegap Build. I.e. all modules will be included in the build.

This means all modules (including Bluetooth module) will be installed when using Phonegap Build.

It is a flaw of Phonegap Build that it supports neither npm or Cordova hook scripts so many plugins do not function correctly with it.

**Comment by aoreinoso** [comment]
Then
Why only ask for permission to use bluetooth and not other features?
Thanks in advance

**Comment by dpa99c** [comment]
=

> Then
> Why only ask for permission to use bluetooth and not other features?
> Thanks in advance

Because the Bluetooth module [registers a state change receiver on app startup](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic_Bluetooth.java#L124) and this implicitly requests runtime permission to use Bluetooth hence presents the permission dialog.

All other modules are included in the app build when using Phonegap Build but their permissions must be explicitly requested using API methods.

**Comment by aoreinoso** [comment]
Thank you very much
