### ISSUE TITLE
[FEATURE] Move support libraries to androidX

### ISSUE THREAD

**Issue by RTK** [dpa99c/cordova-diagnostic-plugin#354]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [x] feature request
- [ ] documentation issue

# Feature request

The current version of this plugin relies on the com.android.support package. Unfortunately this collides with my usage of a plugin which makes use of the new androidx package for support utilities. 

For example: Diagnostic.java

```import android.support.v4.app.ActivityCompat;```
would turn to
```import androidx.core.app.ActivityCompat;```

Reference: https://developer.android.com/reference/androidx/core/app/ActivityCompat

**Comment by dpa99c** [comment]
#350 gives an explanation of why migrating the plugin to AndroidX at this time will cause issues and gives an interim solution until such time as `cordova-android` enables AndroidX by default. 
Also see https://github.com/apache/cordova/issues/69.

**Comment by RTK** [comment]
Ok thanks for your response.
