### ISSUE TITLE
[BUG] isRemoteNotificationsEnabled always returning false iOS 10.2

### ISSUE THREAD

**Issue by eduardoewgo** [dpa99c/cordova-diagnostic-plugin#355]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report
isRemoteNotificationsEnabled always return true on iOS 10+.

> app is registered for remote notifications AND "Allow Notifications" switch is ON AND alert style is not set to "None" (i.e. "Banners" or "Alerts")

Even though I'm setting all those requirements on my emulator, I still get false.

**Expected behaviour:**

Should return true if all requirements are met.

**Environment information**

- Cordova CLI version 
	- 8.1.2 (cordova-lib@8.1.1)
- Cordova platform version
	- ios 4.5.5
- Plugins & versions installed in project (including this plugin)
cordova-admobsdk 7.37.0 "Google Mobile Ads SDK for Cordova"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-admobpro 2.37.2 "AdMob Plugin Pro"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-audio 1.0.0 "background-audio"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-disable-ios11-statusbar 1.0.0 "cordova-plugin-disable-ios11-statusbar"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-multidex-enable 1.0.0 "Cordova Multi Dex"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-purchases 0.0.3 "Purchases"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"

- Dev machine
    - OSX
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
        
- Device details
    - iPhone X Simulator
- OS details
    - iOS 10.2

**Comment by dpa99c** [comment]
The reason (as outlined in [this SO post](https://stackoverflow.com/q/28242332/777265)) is that the native iOS function this plugin uses to determine if the device is registered for remote notifications always returns `false` on iOS Simulators however it works fine on real devices.

My advice is to always test any functionality related to this plugin on a real iOS device.
