### ISSUE TITLE
requestLocationAuthorization() does not open popup

### ISSUE THREAD

**Issue by MickyFln** [dpa99c/cordova-diagnostic-plugin#357]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
The function call `requestLocationAuthorization()` should on Android at least open the popup that asks me if I can use the location. However it does not open and the AuthorizationStatus is set to Denied_Always.
There is no way to access the location.

**Expected behavior:**
The software asks me for permission to use the device's location.

**Environment information**

- Cordova CLI version 
	- `8.1.1 (cordova-lib@8.1.0)`
- Cordova platform version
	- `android 8.0.0`
- Plugins & versions installed in project (including this plugin)
    - cordova-clipboard 1.2.1 "Clipboard"
    - cordova-open-native-settings 1.5.2 "Native settings"
    - cordova-plugin-app-version 0.1.9 "AppVersion"
    - cordova-plugin-apprate 1.4.0 "AppRate"
    - cordova-plugin-brightness 0.1.5 "Brightness"
    - cordova-plugin-buildinfo 2.0.2 "BuildInfo"
    - cordova-plugin-calendar 5.1.4 "Calendar"
    - cordova-plugin-camera 4.0.3 "Camera"
    - cordova-plugin-console 1.1.0 "Console"
    - cordova-plugin-crop 0.3.1 "CropPlugin"
    - cordova-plugin-datepicker 0.9.3 "DatePicker"
    - cordova-plugin-device 2.0.2 "Device"
    - cordova-plugin-dialogs 2.0.1 "Notification"
    - cordova-plugin-file 6.0.1 "File"
    - cordova-plugin-geolocation 4.0.1 "Geolocation"
    - cordova-plugin-globalization 1.11.0 "Globalization"
    - cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
    - cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
    - cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
    - cordova-plugin-nativestorage 2.3.2 "NativeStorage"
    - cordova-plugin-network-information 2.0.1 "Network Information"
    - cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    - cordova-plugin-statusbar 2.4.2 "StatusBar"
    - cordova-plugin-whitelist 1.3.3 "Whitelist"
    - cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
    - cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
    - cordova-support-google-services 1.1.0 "cordova-support-google-services"
    - cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
    - cordova.plugins.diagnostic 4.0.12 "Diagnostic"
    - es6-promise-plugin 4.2.2 "Promise"
    - ionic-plugin-keyboard 2.2.1 "Keyboard"
    - phonegap-plugin-multidex 1.0.0 "Multidex"
    - phonegap-plugin-push 2.2.3 "PushPlugin"`

- Dev machine OS and version, e.g.
    - Windows 10
        
_Runtime issue_
- Device details
    - OnePlus 5, Moto G 6 Play
- OS details
    - Android 9, 8.0	
	
_Android build issue:_	
- Node JS version
    - `v8.9.4`
- Gradle version
	- `4.10.3, 5.1.1`
- Target Android SDK version
	- `28`
- Android SDK details
	- id: 1 or "android-25"
     Name: Android API 25
     Type: Platform
     API level: 25
     Revision: 3
	- id: 2 or "android-26"
     Name: Android API 26
     Type: Platform
     API level: 26
     Revision: 2
	- id: 3 or "android-27"
     Name: Android API 27
     Type: Platform
     API level: 27
     Revision: 3
	- id: 4 or "android-28"
     Name: Android API 28
     Type: Platform
     API level: 28
     Revision: 6`
	

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    - `ionic (Ionic CLI) : 4.12.0`
- Installed Ionic Native modules and versions
    - +-- @ionic-native/app-rate@4.20.0
    - +-- @ionic-native/app-version@4.20.0
    - +-- @ionic-native/brightness@4.20.0
    - +-- @ionic-native/calendar@4.20.0
    - +-- @ionic-native/camera@4.20.0
    - +-- @ionic-native/clipboard@4.20.0
    - +-- @ionic-native/core@4.20.0
    - +-- @ionic-native/crop@4.20.0
    - +-- @ionic-native/date-picker@4.20.0
    - +-- @ionic-native/diagnostic@4.20.0
    - +-- @ionic-native/dialogs@4.20.0
    - +-- @ionic-native/file@4.20.0
    - +-- @ionic-native/geolocation@4.20.0
    - +-- @ionic-native/in-app-browser@4.20.0
    - +-- @ionic-native/keyboard@4.20.0
    - +-- @ionic-native/native-audio@4.20.0
    - +-- @ionic-native/network@4.20.0
    - +-- @ionic-native/open-native-settings@4.20.0
    - +-- @ionic-native/social-sharing@4.20.0
    - +-- @ionic-native/splash-screen@4.20.0
    - +-- @ionic-native/status-bar@4.20.0

**Related code:**

```
doTest() {
  this.diagnostic.isLocationAuthorized().then(val => {
    console.log('is Location Authorized: ', val)
  })
  this.diagnostic.getLocationAuthorizationStatus().then(val => {
    console.log('is Location Authorization Status: ', val)
  })
  this.diagnostic.getLocationMode().then(val => {
    console.log('is Location Mode: ', val)
  })
  this.diagnostic.requestLocationAuthorization().then(val => {
    console.log('request Location Authorization: ', val)
  })
}
```

**Console output**

<details>
<summary>Two consecutive calls of the above mentioned function:</summary>

```
is Location Authorized:  false
is Location Authorization Status:  NOT_REQUESTED
is Location Mode:  high_accuracy
request Location Authorization:  DENIED_ALWAYS

is Location Authorized:  false
is Location Authorization Status:  DENIED_ALWAYS
is Location Mode:  high_accuracy
request Location Authorization:  DENIED_ALWAYS
```

</details><br/><br/>

**Notes:**

I have not yet had the time to setup a completely new project to test this specific issue. It started occuring I think when I upgraded to `cordova-android@8.0`. Before it was working fine.

**Comment by dpa99c** [comment]
The `requestLocationAuthorization()` has been tested and works fine on Android 8 (and 9 and Q beta) - please build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to confirm this for yourself and as a known working reference project.

A common cause on Android of permissions being `DENIED_ALWAYS` is forgetting to include the relevant `<uses-permission>` elements in `AndroidManifest.xml` - see the [Android permissions](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions) section in the documentation.
