### ISSUE TITLE
Bluetooth warning on iOS 13

### ISSUE THREAD

**Issue by daviesdoclc** [dpa99c/cordova-diagnostic-plugin#359]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

Starting with iOS 13 I am getting a BlueTooth permissions dialog popping up.  I tried adding JUST the modules I need

`<preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />`

But in the platforms/iOS/appName/Plugins/cordova.plugins.diagnostic directory I still see ALL the modules being added and the warning persists.

I see this in the appName-info.plist file

`	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>This app requires bluetooth access to function properly.</string>`

I'm using cordova 9.0.0 and cordova-ios 5.0.1.

**Comment by dpa99c** [comment]
The Bluetooth warning is something that has been added in iOS 13 and so can't be avoided - if you include the Bluetooth module, you will get the warning on iOS 13.

If you don't want the Bluetooth module, use the `cordova.plugins.diagnostic.modules` preference to omit it.
Note that this is applied at plugin installation time via an npm install hookscript so if you change the specified modules, you'll need to fully uninstall/reinstall the plugin to apply the changes as [outlined in the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#specifying-modules)

**Comment by daviesdoclc** [comment]
Sorry... you may have caught my message mid-stream (when I was figuring out how to get code lines to appear).  Yes... I added the cordova.plugins.diagnostic.modules preference for JUST "CAMERA" and it still warns.   And the plist file still shows the requirement.

**Comment by dpa99c** [comment]
> Our build process completely starts from scratch and readds platforms and plugins.

Does it wipe down `node_modules` as well? 
Because that's where the npm postinstall script operates...

When you run `cordova plugin add cordova.plugins.diagnostic` it first runs `npm install cordova.plugins.diagnostic` which installs it to the `node_modules` directory. The postinstall script then applies the module settings. And then Cordova finally copies (the modified) plugin to `plugins/`.

**Comment by daviesdoclc** [comment]
Ok... turns out the 

`<preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />`

Needs to be at the root level (not under the platform).  I have os specific ones listed under the platform.  I guess in this case I also want Android to do the same thing, so this is OK.

**Comment by nocodedweb** [comment]
I had to also remove any occurrences of bluetooth from ios.json and frameworks.json to get this to work.

**Comment by BKHines** [comment]
@nocodedweb Was that a manual post-build process or can you configure those files via config.xml so they are updated during the build process?

**Comment by nocodedweb** [comment]
@BKHines Had to remove them manually from those files then re-build.

**Comment by BKHines** [comment]
@nocodedweb okay, that's what I did as well. Thanks for the extra tip!

**Comment by nocodedweb** [comment]
It may also be good to note that many other apps, including social media apps, had this same Bluetooth message appear on app launch after upgrading to iOS 13 beta so it doesn't seem specific to the plugin.

**Comment by dpa99c** [comment]
I've just created #365 to capture this as something that needs addressing in the next version of the plugin.

**Comment by BKHines** [comment]
@nocodedweb very true. I was reading that as well but I don't have many of those apps so I wasn't sure if they have Bluetooth capabilities or not. It was not something I expected because my app doesn't use Bluetooth at all.

**Comment by mnenchev** [comment]
Hi @dpa99c,

My is rejected few times and i'm trying to figure out how to disable the bluetooth popup. I added the preference, then removed and re-added the plugin, then removed and re-added the ios platform and did the build, but it is still appearing.

I read that it can be outdated in [CORDOVA]/node_modules. Where exactly in this folder is the code related to your plugin?

Once i re-add the plugin, how can i verify i got the right modules only for use?

Is there a programmatic way to disable to bluetooth popup?
 
Thanks

**Comment by daviesdoclc** [comment]
@mnenchev See my message above.  Put

    <preference name="cordova.plugins.diagnostic.modules" value="CAMERA" />

at the root level in your config.xml and only list the modules you need.

**Comment by ankitjainOfficial** [comment]
Can anyone comment, how will the preference look like, if I needed multiple modules. And, also, how can I get exact module names?

Or, can be there an ignore module preference somehow. So, if I don't need Bluetooth, but everything else. How do I go about it?

**Comment by dpa99c** [comment]
@ankitjainOfficial Read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#specifying-modules)
