### ISSUE TITLE
PhoneGap: diagnostic plugin is not working in iphone

### ISSUE THREAD

**Issue by ayyazzafar** [dpa99c/cordova-diagnostic-plugin#36]
I am trying to use diagnostic plugin in my ios app built by phonegap Build. It's working fine for android but it's not working in ios.

It is not showing any error in remote debug (console).

I am using following two files to build this app:

index.html and config.xml 
(Code is provided: http://stackoverflow.com/questions/35373948/phonegap-diagnostic-plugin-is-not-working-in-iphone)

I am not getting any error. I reasearched alot about this issue but no vain. I'll really appreciate any response.

**Comment by dpa99c** [comment]
See [my answer on stackoverflow](http://stackoverflow.com/a/35378315/777265)

**Comment by ayyazzafar** [comment]
Thanks a lot. It really helped me a lot. 
May you get more success and more knowledge.
God Bless you forever.
