### ISSUE TITLE
Again and Again asking for installing the plugin in Logcat

### ISSUE THREAD

**Issue by ajoykarmakar** [dpa99c/cordova-diagnostic-plugin#360]
I have installed Diagnosis plugin but getting an error in android 7. When I tried to open the app, the app is stuck at the splash screen and when I tried to open the logcat I found this log.

[https://i.ibb.co/jDzcjKx/Capture.png](url)

 So I have installed again dependency but the error remain same and the error I got only in 7 (Nougat). Can anyone help me, please?

**Comment by dpa99c** [comment]
The log messages in your screenshot originate from [Ionic Native](https://ionicframework.com/docs/native) and indicate this underlying Cordova plugin has not been installed into the project.

Please see [the Ionic Native documentation](https://ionicframework.com/docs/native/diagnostic) for this plugin's Typescript wrapper and if still having issues, [raise an issue against Ionic Native](https://github.com/ionic-team/ionic-native/issues)
