### ISSUE TITLE
External Storage not granted after request permission

### ISSUE THREAD

**Issue by adriansaenz** [dpa99c/cordova-diagnostic-plugin#362]
**I'm submitting a ...**  (check one with "x"):
- [x ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

When I write a file in external storage after request and grant permission, it is failed because a permission deniend error. This only occurs in Android 8.1, in previous version (Android 6 and android 7) this problem does not exist.

I have to save an image in device gallery so after i check permission status in order to grant permission if it is necessary. At first time the permission is not granted so I request to grant the permission. When user accepts I proceed to write the image but i get the permission denied error. 

This problem only appears in my Android 8.1 device as in other devices that i tested the image is write after user grants permission. This other devices have Android 7 and Android 6 version.

**Expected behavior:**

The behavior expected is after request permission and user grants it, the image is saved without any permission denied error.

**Steps to reproduce:**

- Request permission
- Grant permission
- Write image in gallery

**Environment information**

- Cordova 8.0.0
- Cordova Android 7.1.4
- Ionic CLI 4.5.0
- Ionic Framewrok 3.9.2
- Windows 10
- Android 8.1, Android 7, Android 6
- Target Android SDK 27
- Minimum Android SDK 19

**Related code:**

FileOutputStream out = new FileOutputStream(imageFile);
This line returns exception

**Console output**

Exception message:
java.io.FileNotFoundException: /storage/emulated/0/Pictures/img_201969173118.png (Permission denied)

**Comment by dpa99c** [comment]
This is due to [changes to external storage permissions in Android 8](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#rmp).

You must explicitly request both `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`
