### ISSUE TITLE
Not working in latest Ionic4

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [dpa99c/cordova-diagnostic-plugin#364]
# Bug Report

### What is expected to happen?

Import Device in Ionic4 according to documentation import https://ionicframework.com/docs/native/diagnostic

### What does actually happen?

Unresolved import, no module found for import { Device } from '@ionic-native/diagnostic/ngx';

### Environment, Platform, Device

Ionic 4, Angular 7

**Comment by dpa99c** [comment]
The Ionic Native wrapper for this plugin is created/maintained by Ionic Native. 
So please [open this issue against Ionic Native](https://github.com/ionic-team/ionic-native/issues/new)
