### ISSUE TITLE
Question: microphone permission on Android

### ISSUE THREAD

**Issue by mirko77** [dpa99c/cordova-diagnostic-plugin#37]
Hi there, I have a question

I am recording audio on  Android, and I noticed the `requestMicrophoneAuthorization()` is iOS only

What happens if I need this permission on Android Marshmallow?

`<uses-permission android:name="android.permission.RECORD_AUDIO" />`

Your plugin does not provide any method to check if that permission is granted on Android or am I missing something?

**Comment by dpa99c** [comment]
It's in the [documented list of "dangerous" runtime permissions](https://github.com/dpa99c/cordova-diagnostic-plugin#dangerous-runtime-permissions), so:

    cordova.plugins.diagnostic.requestRuntimePermission(function(status){
        switch(status){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied - guess we won't be using it then");
                break;
        }
    }, function(error){
        console.error("The following error occurred: "+error);
    }, cordova.plugins.diagnostic.runtimePermission.RECORD_AUDIO);

**Comment by mirko77** [comment]
Brilliant thanks, I overlooked that !
