### ISSUE TITLE
[Feature]: MODIFY_AUDIO_SETTINGS

### ISSUE THREAD

**Issue by crapthings** [dpa99c/cordova-diagnostic-plugin#370]
Invalid permissions specified: MODIFY_AUDIO_SETTINGS

**Comment by dpa99c** [comment]
This plugin handles the programmatic requesting of [dangerous permissions](https://developer.android.com/guide/topics/permissions/overview.html#dangerous_permissions) at runtime for explicit authorisation by the user.

[`MODIFY_AUDIO_SETTINGS`](https://developer.android.com/reference/android/Manifest.permission.html#MODIFY_AUDIO_SETTINGS) is a [normal permission](https://developer.android.com/guide/topics/permissions/overview.html#normal_permissions) which means it doesn't require runtime authorisation by the user, it only needs to be declared in the manifest at build time.
