### ISSUE TITLE
Question: track which plugin has added a specific permission to app?

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#374]
My app somehow has BLUETOOTH permission added to it, on both iOS and Android.  However both config.xml files have the `<preference ... value="LOCATION NOTIFICATIONS" /> set.  Since the diagnostic plugin has a specific value for BLUETOOTH I don't believe it was added as a sub-permission of LOCATION or NOTIFICATIONS.  Is there any way to determine which plugin has requested/add BLUETOOTH permissions?

**Comment by dpa99c** [comment]
If you make changes to the modules preference in `config.xml`, you'll need to uninstall/reinstall the plugin to make those changes take effect. If you look at `plugins/cordova.plugins.diagnostic/plugin.xml`, you should see the plugins not specified in your preference have been commented out by the plugin's [postinstall hook script](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/scripts/apply-modules.js).

Apple determines which APIs are being accessed by scanning the code at upload time.
In the case of Bluetooth, that's references to classes in the CoreBluetooth framework such as [CBCentralManager](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager?language=objc). 
In the case of this plugin, that class is now only referenced in the Bluetooth module in [Diagnostic_Bluetooth.m](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Bluetooth.m) when [it's instantiated on demand at runtime](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Bluetooth.m#L171) when the first plugin API function is called.

So from the perspective of this plugin, if `Diagnostic_Bluetooth.m` is not present in your iOS Xcode project, this plugin is not responsible for the Bluetooth references detected.

Hope that clarifies things.
