### ISSUE TITLE
Is this possible to turn location services OFF?

### ISSUE THREAD

**Issue by Taxi4you** [dpa99c/cordova-diagnostic-plugin#376]
When I try to locate user's position when his location services are already on - it doesn't track him. Only if his location services are OFF and I request to open them via the app using the **cordova-plugin-request-location-accuracy** plugin it actually tracks the user's position.

So maybe is there a way to forcely shut his location services down so it will be allowed to re-open via the app directly?

**Comment by dpa99c** [comment]
It's not possible to programmatically disable location services on either Android or iOS
