### ISSUE TITLE
THREAD WARNING: ['Diagnostic'] took 'x' ms. Plugin should use a background thread

### ISSUE THREAD

**Issue by irstavr** [dpa99c/cordova-diagnostic-plugin#378]
Hi @dpa99c ,
Thanks for your amazing work on cordova stuff once more!
 
I'm submitting a ...
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

I am using the plugin on an iphone device, but when executing the `diagnostic` API calls, the UI totally blocks. I see the following warning on iOS logs:

`THREAD WARNING: ['Diagnostic'] took '27.634766' ms. Plugin should use a background thread.
`
Here's a post related to this issue about running in a background thread: http://stackoverflow.com/questions/22382260/how-to-run-cordova-plugins-in-the-background

Trying to load only the needed modules, didn't solve the issue.
`    <preference name="cordova.plugins.diagnostic.modules" value="LOCATION" />
`

I was wondering if there's a workaround solution for this already, or if it's planned to be handled in the near future.

Kind regards

**Comment by dpa99c** [comment]
You haven't specified which exact API functions you are calling, but it you [look at the source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/ios/Diagnostic_Location.m#L24) you'll see that all plugin API functions are executed on a background thread.
The warning is irrelevant - 27ms is a very short period of time and not observable - especially not to observe the UI locking up. Most likely something else is blocking your UI thread such as JS code in the plugin callback function.
