### ISSUE TITLE
Android 9 - cannot get `getLocationAuthorizationStatus` to return `GRANTED`

### ISSUE THREAD

**Issue by ZaLiTHkA** [dpa99c/cordova-diagnostic-plugin#382]
#Bug report

>**Please note**: I'm not entirely sure if this is a bug report or a support request.. I *believe* I have my project configured correctly, I *have* read through 4 other issue reports in this repo where someone else has had the same or a similar issue, but I still cannot get it to work.

My Ionic 4 Angular 8 app has a dedicated `PermissionsPage` component, accessing this plugin through the Ionic Native wrapper (using `5.16.0` at the time of writing this).

My component `constructor` initiates a first permissions check, calling `getLocationAuthorizationStatus()` first in order to determine whether or not I need to ask the user for permission. Then I have a method attached to a button that calls `requestLocationAuthorization()`.

My project's `config.xml` contains both the `android.permission.ACCESS_COARSE_LOCATION` and `android.permission.ACCESS_FINE_LOCATION` strings, as well as the `LOCATION` string value in the `cordova.plugins.diagnostic.modules` preference.

For what it's worth, I'm running the app from command line in debug mode, I haven't tried this yet with creating an APK file, not sure if that will makes a difference here.

**Current behavior:**

When I clear app data and run my app (aka: emulating a fresh install), my initial `getLocationAuthorizationStatus()` call returns `NOT_REQUESTED`, exactly as expected. Then I press the button to trigger my call to `requestLocationAuthorization()` and select "Allow" from the permission prompt that pops up, at which point the method returns `DENIED_ALWAYS`.

Checking the app settings, the "Location" permission is indeed allowed to my app.

**Expected behavior:**

Naturally, I would expect tapping "Allow" on the permission prompt to make the method return `GRANTED`...

**Environment information**

- Cordova CLI version: `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version: `android 8.1.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova-android-support-gradle-release` `3.0.1` "cordova-android-support-gradle-release"
    - `cordova-plugin-ble-central` `1.2.4` "BLE"
    - `cordova-plugin-camera` `4.1.0` "Camera"
    - `cordova-plugin-device` `2.0.3` "Device"
    - `cordova-plugin-ionic` `5.4.5` "cordova-plugin-ionic"
    - `cordova-plugin-ionic-keyboard` `2.2.0` "cordova-plugin-ionic-keyboard"
    - `cordova-plugin-ionic-webview` `4.1.2` "cordova-plugin-ionic-webview"
    - `cordova-plugin-market` `1.2.0` "Market"
    - `cordova-plugin-splashscreen` `5.0.3` "Splashscreen"
    - `cordova-plugin-sqlite-2` `1.0.6` "SQLitePlugin"
    - `cordova-plugin-statusbar` `2.4.3` "StatusBar"
    - `cordova-plugin-whitelist` `1.3.4` "Whitelist"
    - `cordova.plugins.diagnostic` `5.0.1` "Diagnostic"
- Dev machine OS and version, e.g.
    - Windows 10: `1903 (OS Buid 18362.295)`
        
_Runtime issue_
- Device details: Xiaomi MiMIX 2
- OS details: LineageOS `16.0-20191104`, Android 9
	
_Android build issue:_	
- Node JS version: `10.15.1`
- Gradle version: `5.6.3`, but there also seems to be a `4.10.3` folder as well
- Target Android SDK version: not specified, but `minSdkVersion` is set to `19` and my `cordova-android-support-gradle-release` config sets `ANDROID_SUPPORT_VERSION` to `27.+`
- Android SDK details: SDK and source files for API levels `21` through `29`, managed through Android Studio's SDK Manager window.

**Comment by ZaLiTHkA** [comment]
I've just noticed that I get the exact same behaviour with the `requestCameraAuthorization()` method: after allowing the permission prompt, I get `DENIED_ALWAYS` back.

I also got my hands on a completely stock Huawei MediaPad T5 running Android 8.0, which gives me the exact same behaviour for both the location and camera authorisation prompts.

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for comparison as a working reference.

**Comment by ZaLiTHkA** [comment]
The example project runs fine, and requesting location and camera authorisation responds correctly.

I just tried changing the method calls in my app to use the plugin directly instead of going through the Ionic Native plugin wrapper, but that didn't seem to make any difference.

If you have any suggestions on things to check/try, I'm all ears.. In the meantime, I'll compare the example app's configuration to mine and see if anything jumps out at me.

**Comment by ZaLiTHkA** [comment]
figured it out... my `config.xml` file had the `uses-permission` entries as direct children of a `platform` element.

I noticed these were inside `<config-file parent="/*" target="AndroidManifest.xml">` in the example project, so I adjusted my config file to match and now it's working.
