### ISSUE TITLE
Force Access permission to Bluetooth in IPAD ios 13.2

### ISSUE THREAD

**Issue by knikolou** [dpa99c/cordova-diagnostic-plugin#383]
# Bug report

**Current behavior:**
i am using this plugin for find location only and i am not trigger bluetooth
inside the app.I am using phonegap to compile 

**Expected behavior:**
I am trying to publish my app to Appstore but the reviewers check the app with ipad (ios13.2)
and when run for first time it asks permission to bluetooth which i dont use .So they reject my app
Upon further review, we found that your app does not comply with the following guidelines:
Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app when reviewed on iPad running iOS 13.2.3 on Wi-Fi.
- Specifically, your app requests permission to use Bluetooth without any Bluetooth functionality within the app.
When i check my app in actual device (iphone 6) with ios 12xx i doesnt ask for bluetooth permission
How can i disable the use of bluetooth only in this plugin?
so i can publish to app store
**Steps to reproduce:**

**Screenshots**

**Environment information**

phonegap cli 8.1.0
        
_Runtime issue_
- Device details
    ipad wifi 6th  
- OS details
ios 13.2
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
See #375
