### ISSUE TITLE
How to ask for Location Always Permission in iOS 

### ISSUE THREAD

**Issue by Taxi4you** [dpa99c/cordova-diagnostic-plugin#386]
This is the code I am using right now for asking about location permissions:

```
cordova.plugins.diagnostic.requestLocationAuthorization(function (status) {
      switch (status) {
        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
          break
        case cordova.plugins.diagnostic.permissionStatus.DENIED:
          RootScope.f7.emit("isLocationAuthorizationDenied", true)
          break
        case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
          RootScope.f7.emit("isLocationAuthorizationDenied", true)
          break
        case cordova.plugins.diagnostic.permissionStatus.GRANTED:
          RootScope.f7.emit("isLocationAuthorizationDenied", false)
          self.setState({ isLocationAuthorized: true })
          break
        case cordova.plugins.diagnostic.permissionStatus.GRANTED_WHEN_IN_USE:
          RootScope.f7.emit("isLocationAuthorizationDenied", false)
          self.setState({ isLocationAuthorized: true })
          break
      }
    }, function (err) {
      if (err) {
        return Cast.error(err)
      }
    }, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS)
```

However, instead of prompting a simple Yes no dialog, the next dialog pops:

1. Only when in use
2. Allow once
3. Deny

What are these mean?
If user presses 1, only foreground, will not be asked again?
if user presses 2, includes also the background, but will be asked again?

How can I prompt an always permission dialog at the "first shot"?

**Comment by dpa99c** [comment]
iOS 13 changed the behaviour of location permission requests such that you can no longer directly request permanent background location permission (ALWAYS). Please [see here](https://gimbal.com/ios-13-location-permissions/) for an explanation.

This plugin can do nothing to override these changes as it is limited by the APIs provided by iOS. Therefore you will need to handle these changes in the messaging and logic of your app code.
