### ISSUE TITLE
getBackgroundRefreshStatus missing return statement?

### ISSUE THREAD

**Issue by scyclops** [dpa99c/cordova-diagnostic-plugin#389]
It looks like there might need to be a return statement after line 84 in getBackgroundRefreshStatus in Diagnostic.m in order to prevent the error callback from being triggered along with another error or success callback immediately after.

https://github.com/dpa99c/cordova-diagnostic-plugin/blob/a55fb69218f8b7556cb739a3266d9352af535eaf/src/ios/Diagnostic.m#L84

**Comment by dpa99c** [comment]
Thanks, you are right.
