### ISSUE TITLE
Camera permission denied despite being 'GRANTED' 

### ISSUE THREAD

**Issue by mirko77** [dpa99c/cordova-diagnostic-plugin#39]
I am using the following code to check for permissions on Marshmallow before taking a picture:

```
//check permission
window.cordova.plugins.diagnostic.isCameraAuthorized(function(response) {
  if (response) {
    $rootScope.permissions.camera = true;
    _openCamera();
  } else {
    // request permission
    cordova.plugins.diagnostic.requestCameraAuthorization(function(permission) {  
      if (permission === 'GRANTED') {
        $rootScope.permissions.camera = true;
        _openCamera();
      }
    }, function(error) {
      console.error(error);
    });
  }
}, function(error) {
  console.log(error);
});
```

` _openCamera();` will run the code to open the camera, but the app crashes with:

`Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:file:///storage/emulated/0/Android/data/uk.ac.imperial.epicollect5.ionic/cache/.Pic.jpg} (has extras) } from ProcessRecord{99d2ee 7527:uk.ac.imperial.epicollect5.ionic/u0a79} (pid=7527, uid=10079) with revoked permission android.permission.CAMERA`

I get the popup, I tap allow, the permission is GRANTED but still the camera crashes. If I look at the app permission settings, camera is still off after granting permission.

Any suggestions?

**Comment by dpa99c** [comment]
This may be related to pull request #33 which removes `android.permission.CAMERA` from being requested on calling `cordova.plugins.diagnostic.requestCameraAuthorization()` on the basis that [cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera) doesn't use it, but instead requires only `android.permission.READ_EXTERNAL_STORAGE` [(see here)](https://github.com/apache/cordova-plugin-camera/blob/master/src/android/CameraLauncher.java#L108).

If you explicitly need `android.permission.CAMERA`, try:

    cordova.plugins.diagnostic.requestRuntimePermission(successFn, 
        errorFn, 
        cordova.plugins.diagnostic.runtimePermission.CAMERA
    );

**Comment by mirko77** [comment]
Thanks, that's about it. It is a known bug on Android/ Cordova [https://issues.apache.org/jira/browse/CB-10120](here)
