### ISSUE TITLE
cordova.plugins.diagnostic.getRemoteNotificationTypes is not a function

### ISSUE THREAD

**Issue by w4ugit** [dpa99c/cordova-diagnostic-plugin#391]
I want to make sure the user has turned on the desired notification settings. for this I want to use cordova.plugins.diagnostic.getRemoteNotificationTypes. but I get the error

Android 9
Cordova 9.0.0
cordova.plugins.diagnostic 5.0.1 "Diagnostic"

**Comment by dpa99c** [comment]
[getRemoteNotificationTypes()](https://github.com/dpa99c/cordova-diagnostic-plugin#getremotenotificationtypes) is platform-specific to iOS. 
Android does not have an equivalent.

**Comment by w4ugit** [comment]
I have a default on android muted, popup popup, and lock screen notifications. is it possible to turn it on or at least check that it is turned off? I use firebasex for notifications

**Comment by dpa99c** [comment]
If you believe this is possible please show me the Android API documentation to access these settings programmatically
