### ISSUE TITLE
requestCameraAuthorization returns DENIED_ALWYAS

### ISSUE THREAD

**Issue by askona** [dpa99c/cordova-diagnostic-plugin#393]
I'm using Ionic4, and latest 5.0.1 version of plugin. 

In case of any answer for permission.

Android 10.

**Comment by dpa99c** [comment]
Check you have added the necessary permissions to the manifest as outlined in [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions).

Also try building & running the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-example) to validate the plugin functionality in a known codebase.

**Comment by dpa99c** [comment]
Closed due to no response
