### ISSUE TITLE
TypeError: undefined is not a function (near '...cordova.plugins.diagnostic.isGpsLocationEnabled...')

### ISSUE THREAD

**Issue by Mehditeranee** [dpa99c/cordova-diagnostic-plugin#395]
I am experiencing a similar issue that this one: https://github.com/dpa99c/cordova-diagnostic-plugin/issues/68

The error is : `TypeError: undefined is not a function (near '...cordova.plugins.diagnostic.isGpsLocationEnabled...')`

<img width="1184" alt="Capture d’écran 2020-04-06 à 15 26 59" src="https://user-images.githubusercontent.com/38721898/78563318-103b6700-781b-11ea-9cc6-4bc0c1333de0.png">

Indeed, when i run my app, i called cordova-diagnostic-plugin to check if GPS location is enabled or not. 

```
cordova.plugins.diagnostic.isGpsLocationEnabled(
function(enabled)
{
        console.log("GPS location is " + (enabled ? "enabled" : "disabled"));

        if(enabled)
        {
       ... My code here ...
        }
        else
        {
      ...My code here...
        }
}, 
function(error
{
        console.error("The following error occurred: "+error);
 }
);  
```

Note **this code is run in onDeviceReady() function itself called by** : `document.addEventListener("deviceready", onDeviceReady, false);`

So, I cannot understand how `diagnostic` can be undefined whereas the code is running by the deviceready event.

Moreover, this error appears **only on iOS device**, on Android everything work properly.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-diagnostic-plugin#isgpslocationenabled):
> Platforms: Android

i.e it is Android only and does not apply to iOS. Therefore you need to add some platform-specific conditionality if using this, e.g.:

	if(platform === "android") {
		cordova.plugins.diagnostic.isGpsLocationEnabled();
	}

**Comment by Mehditeranee** [comment]
Indeed, sorry.
