### ISSUE TITLE
Privacy/Security Notification Setting on Android

### ISSUE THREAD

**Issue by jringbox** [dpa99c/cordova-diagnostic-plugin#397]
# Feature request

I need a "Privacy/Security Notification Setting on Android".
On Android, there's a notification setting in the privacy/security section to indicate whether notifications are hidden or not.  From what I noticd on this module, there doesn't appear to be a way to get to this setting.

The need this setting for a security sensitivity requirement.  Sensitive information should not be displayed on the lock screen if sensitive notification alert is sent.  If the device setting is sent to hidden then sensitive information can be sent and when the user unlocks their phone they can see the notification alert.  If the setting is not sent, then the application will sent a non-sensitive type of notification alert.

**Comment by dpa99c** [comment]
AFAIK there is no Android API that enables you to access this setting.

However, if I am wrong and you are aware of one, please post a link to the relevant documentation and I'll reopen this issue.

**Comment by jringbox** [comment]
Well, I haven't found it, so maybe you're right.
