### ISSUE TITLE
FEATURE Add support for Android 10 background geolocation

### ISSUE THREAD

**Issue by dzziwny** [dpa99c/cordova-diagnostic-plugin#398]
On Android 10, API 29, to share location in the background, the user has to choose `Always` authorization status, while currently plugin returns status `Granted` for both: `Always` and `Always While-in-us`.

https://developer.android.com/training/location/request-updates#request-background-location

**Comment by danfleck** [comment]
On iOS I saw this also, but it's not a problem. It's Apple's "provisional always authorization". See https://developer.apple.com/documentation/corelocation/cllocationmanager/1620551-requestalwaysauthorization

**Comment by dpa99c** [comment]
I have updated this issue because the plugin requires changes only for Android 10.

The iOS 13 API has not changed although the behaviour of iOS 13 has changed with its temporary authorization of background location.

**Comment by dpa99c** [comment]
This has been published in v5.0.2
