### ISSUE TITLE
[iOS Simulator] XCODE 11.4 Contacts Module is not working

### ISSUE THREAD

**Issue by gaurav-chandra** [dpa99c/cordova-diagnostic-plugin#399]
# Bug report

**Current behavior:** [iOS Simulator] XCODE 11.4 Contacts Module is not working.

On iOS calling any code related to contacts module does not execute:
```
cordova.plugins.diagnostic.getContactsAuthorizationStatus(function(status){
    if(status === cordova.plugins.diagnostic.permissionStatus.GRANTED){
        console.log("Contacts use is authorized");
    }
}, function(error){
    console.error("The following error occurred: "+error);
});
```
The above code does not execute with no logs. Request permission code also does not execute. On Android it works perfectly.

**Expected behavior:**
Contacts module should work on iOS.

**Steps to reproduce:**
1) Create any cordova app
2) Add ```<preference name="cordova.plugins.diagnostic.modules" value="LOCATION WIFI CAMERA NOTIFICATIONS EXTERNAL_STORAGE CONTACTS" />``` before installing the plugin
3) install plugin
4) add ios platform

**Screenshots**

**Environment information**

- Cordova CLI version 
	9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    call-number 0.0.2 "Cordova Call Number Plugin"
com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-android-firebase-gradle-release 4.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-clipboard 1.3.0 "Clipboard"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.3.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-background-geolocation 3.1.0 "CDVBackgroundGeolocation"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-battery-status 2.0.3 "Battery"
cordova-plugin-bring-to-front 0.0.3 "Bring to Front"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-contacts 3.2.0 "Contacts"
cordova-plugin-customurlscheme 5.0.0 "Custom URL scheme"
cordova-plugin-deeplinks 1.1.1 "Cordova Deeplinks Plugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-fcm-with-dependecy-updated 6.3.1 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-firebase-analytics 4.3.0 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-ios-framework-adsupport 1.0.0 "iOS AdSupport Framework"
cordova-plugin-local-notification 0.9.3 "LocalNotification"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-qrcodejs 1.0.0 "cordova-plugin-qrcodejs"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-simple-image-resizer 0.1.1 "Image Resizer"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-theme-detection 1.1.3 "ThemeDetection"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
cordova-sqlite-storage 3.4.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
- Dev machine OS and version, e.g.
    - OSX
        - 10.15.4
        
_Runtime issue_
- Device details
    iPhone SE Simulator
- OS details
    iOS 13	
	
_iOS build issue:_
- Node JS version
    12.16.2
- XCode version
   11.4

**Related code:**
N/A

**Console output**
NONE

**Other information:**

N/A

**Comment by dpa99c** [comment]
It works fine for me using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example):

<img width="300" src="https://user-images.githubusercontent.com/2345062/82566181-71bd5800-9b73-11ea-9e7d-0ce89de09f56.png"/>
<img width="300" src="https://user-images.githubusercontent.com/2345062/82566184-72ee8500-9b73-11ea-8d7b-b9d608369520.png"/>

Please build & run the example project to eliminate possible causes within your own project.

**Comment by gaurav-chandra** [comment]
Ah thanks. Did not think about example project. I will update you. Sorry for wasting your time.

**Comment by gaurav-chandra** [comment]
I just saw devtools and found that diagnostic.contacts.js file was not added as a script. I overlooked your note that the config.xml needs to have the modules listed **before** adding the plugin. All I did was re-install the platform. Thanks for a great plugin.
