### ISSUE TITLE
Wifi error reported, but device is using it.

### ISSUE THREAD

**Issue by jessemonroy650** [dpa99c/cordova-diagnostic-plugin#40]
Device Model: SproutChannelCubby
Android version: 4.4.2
Processor: QuadCore-A31
Phonegap Build verison: cli-5.2.0
**ERROR** *Exception occured: WifiService: Neither user 10137 nor current process has android.permission.ACCESS*

To be clear, the device only has wifi and the wifi is on. 
I made this call:
    cordova.plugins.diagnostic.isWifiEnabled()

[Source code](https://github.com/jessemonroy650/PGBP-DiagnosticApi22)
Downloadable [Build](https://build.phonegap.com/apps/1933230/share)

[Screenshot of error](http://codesnippets.altervista.org/examples/phonegap/diagnostic-error.png)

**Comment by dpa99c** [comment]
[`cordova.plugins.diagnostic.isWifiEnabled()`](https://github.com/dpa99c/cordova-diagnostic-plugin#iswifienabled) requires that the `android.permission.ACCESS_WIFI_STATE` be added to the AndroidManifest.xml. As [stated in the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions):

>These permissions will not be set by this plugin, to avoid asking for unnecessary permissions in your app, in the case that you do not use a particular part of the plugin. Instead, you can add these permissions as necessary, depending what functions in the plugin you decide to use.

>You can add these permissions either by manually editing the AndroidManifest.xml in /platforms/android/, or define them in the config.xml and apply them using the [cordova-custom-config plugin](https://github.com/dpa99c/cordova-custom-config)

Since you're using Phonegap Build, I would suggest using cordova-custom-config to add the permission request to your AndroidManifest.xml:

    <plugin name="cordova-custom-config" source="npm" spec="*" />
    <platform name="android">
        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
        </config-file>
    </platform>

**Comment by jessemonroy650** [comment]
Hmm... I'm testing this plugin as part of a blog post. I would rather not add that, if possible. Is there another function call _OR_ earlier version i could use that would get me
1) a successful Build
2) a successful function Call
To be clear, I'm not testing for functionality - just something to say I got it working. The article will, of course, add your suggested fix.
FWIW: here is a previous Blog post on this subject:
[http://codesnippets.altervista.org/blog/2015/BLOG.2015-07-08.codesnippets.html](http://codesnippets.altervista.org/blog/2015/BLOG.2015-07-08.codesnippets.html)
Thanks
Jesse

**Comment by dpa99c** [comment]
There's no way you can check the state of Wifi on Android without requesting the permission  `android.permission.ACCESS_WIFI_STATE` (as the name suggests).

And this plugin does not request that permission for the reason that it's designed to be Swiss army knife - i.e. use the bits you need. If the plugin added permission requests for all the device functionality it supports, you'd end up with an AndroidManifest like this:

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />

And this would lead to lots of issues being opened saying "why does your plugin request permission for X when my app doesn't even need it?"

Hence you have 2 choices:

a) Manually modify the AndroidManifest.xml - this is only possible if your build platform is local (i.e. not Phonegap Build)
b) Use cordova-custom-config to set the permission requests

**Comment by jessemonroy650** [comment]
Hmm... Okay. I will pass on your plugin for now. I will come back to it in the future.
FWIW: I prefer this design. I write my modules that way. But article is for "quick and easy".
Thanks for taking time to make this note. When I have time, I might write an article on this plugin. 

Thanks again.
Jesse

**Comment by dpa99c** [comment]
This plugin is definitely for advanced usage in Cordova projects (as is cordova-custom-config). Not one for quick and easy projects.

Btw, my [cordova-check-plugins](https://github.com/dpa99c/cordova-check-plugins) tool _is_ quick and easy, and related to plugin usage, so you may want to take a look at that.

I'll close this so it doesn't confuse people that checking Wifi won't work.

**Comment by jessemonroy650** [comment]
Yes. That might be good I'll have a look at it.
