### ISSUE TITLE
plugin has old android support dependencies instead of using the new AndroidX equivalent

### ISSUE THREAD

**Issue by losciur** [dpa99c/cordova-diagnostic-plugin#400]
Hi,
I'm trying to use this plugin with ionic capacitor and in Android Studio I get this error 'Cannot Resolve symbol ActivityCompat' at line:
import android.support.v4.app.ActivityCompat;

In the capactior Troubleshooting Android Issues I found:
This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent. You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.

I don't know if it's the same think but... 
do you think to use the new AndroidX equivalent dependencies in the plugin?

Thanks

**Comment by dpa99c** [comment]
In a Cordova environment you can add [cordova-plugin-androidx](https://github.com/dpa99c/cordova-plugin-androidx) and [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) which add AndroidX support to Cordova projects and dynamically patch any source code (including this plugin) from the legacy Android Support Library to AndroidX.

This works fine in a Cordova environment (you can test this yourself with [the example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example)) however it may not work in a Capacitor project. 
This is a Cordova plugin and Capacitor is not officially supported, however see https://github.com/dpa99c/cordova-plugin-firebasex/issues/412 for a potential solution for Capacitor.
