### ISSUE TITLE
Is this plugin usable on production environment ?

### ISSUE THREAD

**Issue by sboudouk** [dpa99c/cordova-diagnostic-plugin#401]
# Documentation issue

Diagnostic make it sound like it's for debug and diagnostic issues only. I want to use this plugin on my app on production to check for iOS Camera permissions, for example. And as a begginner, I don't know if I should do this.

Thanks for this awesome plugin.

**Comment by dpa99c** [comment]
Yes, it exposes various native APIs for use in production apps
