### ISSUE TITLE
Add support for iOS 14 Location Accuracy

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-diagnostic-plugin#402]
On iOS 14 when a user grants location authorization to an app, the app is by default only given access to "reduced accuracy" location data.
If your app requires "full accuracy" (high-accuracy GPS) location data, you need to request temporary access (you can't request it permanently) via the new [`requestTemporaryFullAccuracyAuthorization()`](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600217-requesttemporaryfullaccuracyauth) method.
This requires the user to authorise full accuracy each time you need it via a new authorisation prompt which displays the new `NSLocationTemporaryUsageDescriptionDictionary` plist key.
The current accuracy level is indicated by the [`accuracyAuthorization` property of `CLLocationManager`](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600215-accuracyauthorization) as [`CLAccuracyAuthorization` constants](https://developer.apple.com/documentation/corelocation/claccuracyauthorization).

We need to extend this plugin to expose these new methods and constants.
This should be done conditionally in a backwardly-compatible way so as not to break builds which use an SDK version lower than iOS 14.

Note: iOS 14 public release date is due ~14 September

**Comment by dpa99c** [comment]
This is now implemented on the [dev branch](https://github.com/dpa99c/cordova-diagnostic-plugin/tree/dev) of this plugin. 

To test it, you can clone the [dev branch](https://github.com/dpa99c/cordova-diagnostic-plugin-example/tree/dev) of the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) and build and run the example app:

	git clone https://github.com/dpa99c/cordova-diagnostic-plugin-example
	cd cordova-diagnostic-plugin-example
	git checkout dev
	cordova platform add ios
	cordova run ios 
	# or run via Xcode

On testing in the Simulator using Xcode 12 Beta 2, by default the newly installed app is granted access to your precise location:

<img width="300" src="https://user-images.githubusercontent.com/2345062/87035144-cfb80480-c1e0-11ea-8c4a-fbb8b064e0f2.png" />
<img width="300" src="https://user-images.githubusercontent.com/2345062/87035229-efe7c380-c1e0-11ea-846e-a2dd5b4b51e6.png" />


So to test the plugin implementation, you first need to switch off the Precise Location switch in the app settings.
Then the example app should show the current accuracy authorization as reduced:

<img width="300" src="https://user-images.githubusercontent.com/2345062/87035354-202f6200-c1e1-11ea-8ef9-57f5ca2812e8.png" />

If you then press the "Request Full Location Accuracy Authorization" button:

<img width="300" src="https://user-images.githubusercontent.com/2345062/87035393-2f161480-c1e1-11ea-9dbe-f6ab5da3becf.png" />

You should be prompted to allow it:

<img width="300" src="https://user-images.githubusercontent.com/2345062/87035492-51a82d80-c1e1-11ea-90f7-40663742d5ec.png" />


And if you press "Allow Once" you should see the accuracy authorization change back to full:

<img width="300" src="https://user-images.githubusercontent.com/2345062/87035229-efe7c380-c1e0-11ea-846e-a2dd5b4b51e6.png" />

**Comment by angelofan** [comment]
@dpa99c It looks great, and I did some tests on iOS 13 and iOS 14.

If no change the `Bundle ldentifier`, after uninstalling the App and reinstalling the App, the authorized permissions will still retain the original settings. If the `Bundle ldentifier` is changed, the authorization list is like this:

![image](https://user-images.githubusercontent.com/20255750/87105007-4231ee80-c28c-11ea-9987-ea4f475f5ee8.png)
it is a new installation, there is no "location" permission option in the permission list.

When installing an app signed by Debug, you need to uninstall the app with the old `Bundle ldentifier` and install the app with the changed `Bundle ldentifier` again. If you did not uninstall but changed the `Bundle ldentifier` in Xcode and then directly compiled and replaced again, the original settings will still be used.

## Tested on iOS 13.5

If it is a new installation, the authorization list is like this:
![image](https://user-images.githubusercontent.com/20255750/87105007-4231ee80-c28c-11ea-9987-ea4f475f5ee8.png)

![image](https://user-images.githubusercontent.com/20255750/87105027-5970dc00-c28c-11ea-89d5-95589e5d93c5.png)

After clicking OK, the interface has changed
![image](https://user-images.githubusercontent.com/20255750/87105087-8d4c0180-c28c-11ea-8404-5182b8c10909.png)

I clicked the "Recheck Status" button and the warning reappeared.


## Tested on iOS 14.0

### First test

After the first installation, the authorization list looks like this：
![image](https://user-images.githubusercontent.com/20255750/87105890-bbcadc00-c28e-11ea-85b2-f74799002037.png)

![image](https://user-images.githubusercontent.com/20255750/87105912-c5ecda80-c28e-11ea-8e5b-ec82bf9e36df.png)

Then after I press the "Request Full Location Accuracy Authorization" button:
![image](https://user-images.githubusercontent.com/20255750/87106154-5aefd380-c28f-11ea-8433-6037715fa9c8.png)

After pressing the "Request Full Location Accuracy Authorization" button again:
![image](https://user-images.githubusercontent.com/20255750/87106245-92f71680-c28f-11ea-8c19-527805a030a8.png)

### Test multiple times

I uninstalled the App again, then changed the `Bundle ldentifier` in Xcode, and then install it. The permission list looks like this:
![image](https://user-images.githubusercontent.com/20255750/87109196-99d55780-c296-11ea-8e1f-2bd6ecea027c.png)

Then I clicked the "re-check status" button:
![image](https://user-images.githubusercontent.com/20255750/87109273-cab58c80-c296-11ea-83d5-671febc15178.png)

Then I checked the permission list in the settings:
![image](https://user-images.githubusercontent.com/20255750/87109287-d2753100-c296-11ea-8b01-0a79e69751d5.png)

**Comment by dpa99c** [comment]
@angelofan thanks for testing - that's all really useful info to know.

From your screenshots, I think the behaviour of the plugin looks correct, but the example app should do a better job of showing when the accuracy authorization status has not been determined (it should show NOT_DETERMINED instead of a blank line).
So I'll update the example project on the dev branch so it better handles this scenario.

With regard to when the Location permission is displayed in Settings, it's my understanding that it's not shown until a location-related permission has been requested - so on iOS 14 that means either (use) location permission or location accuracy permission. Regardless of whether the user accepts or denies permission, the Location entry is then show in the list of permissions for the app in Settings

**Comment by angelofan** [comment]
@dpa99c Thank you very much for making iOS 14 compatible immediately.

`cordova-plugin-wifiwizard2` needs to get the user’s location permission to continue working. Is anyone willing to help include `cordova-diagnostic-plugin` in `cordova-plugin-wifiwizard2`? It would be very useful if possible, Many developers who currently use `cordova-plugin-wifiwizard2` are reinventing the wheel.

https://github.com/tripflex/WifiWizard2/issues/95

**Comment by dpa99c** [comment]
This has been released in `cordova.plugins.diagnostic@6.0.0`

**Comment by KevinKelchen** [comment]
Hi there, 👋

We use version `5.0.2` of `cordova.plugins.diagnostic` and requesting location permission seems to be _working as expected_ when building with Xcode 12 and running on iOS 14.

The dialog is different than on iOS 13 in that you can now choose between precise and coarse location, but selecting either works as I'd expect it to--including with `Allow While Using App`.

![IMG_0006](https://user-images.githubusercontent.com/8027502/94974054-0301eb00-04d3-11eb-8981-16f75dd96bf2.jpg)

Is there a problem I'm not seeing? I happened across this issue and it gave me pause that something might not work as expected even though things appear to be fine. 🙂

Thanks for all of your contributions in maintaining this plugin! 😀

**Comment by dpa99c** [comment]
If the user chooses coarse location accuracy (precise is currently the default but this could change in a future iOS update), the app is given only low accuracy location data (~100m). This is no good for apps which require high accuracy such as satnav apps. So v6 of this plugin exposes the iOS 14 APIs which enable the app to determine the current location accuracy level and if it's currently coarse, to request high accuracy permission which triggers a permission dialog.

**Comment by KevinKelchen** [comment]
Thank you for your response! 😀

That makes sense. 🙂 So the user's selection of precise vs. coarse location should work as expected with v5 of the plugin, but v6 adds the ability to detect which of those two accuracy types is currently enabled and allows for prompting the user if needed to specifically request precise location permission.

Thanks so much, Dave!

**Comment by rolinger** [comment]
After going through a massive amount of updates for Mac OS, Xcode, Cordova and Cordova iOS I ran into this issue.  My app definitely needs precise location accuracy.  Coarse, as I understand it, is within ~100m...100 meters is over 300 hundred feet...that is the length of a football field.  That's insane and will cause a lot of apps to break or be inaccurate - in my case it will cause massive headaches.  But having to ask the user EVERY time they start your app is also going to be problematic in of itself dramatically impacting user perception of app functionality.

Why is Apple constantly doing this?  What app wants to be forced to ask users the same question every time they start your app?  Apple changes constantly make us app developers jump through hoops and most of these changes the user will think is the "apps" fault or design issue, and not with Apple itself.
