### ISSUE TITLE
 cordova.plugins.diagnostic.remoteNotificationType missing from node module

### ISSUE THREAD

**Issue by jwburnside** [dpa99c/cordova-diagnostic-plugin#403]
I'm not certain whether this is a documentation issue or an issue on my end. 

I'm running diagnostic plugin version: 5.0.2.

And node module: "@ionic-native/diagnostic": "^5.27.0".

I'm attempting to implement the requestRemoteNotificationsAuthorization() example as described in the documentation: https://github.com/dpa99c/cordova-diagnostic-plugin#example-usage-50

I noticed however, though I seem to be on the latest Ionic Native version, that the cordova.plugins.diagnostic.remoteNotificationType constants are missing from the node module:
https://github.com/ionic-team/ionic-native/blob/master/src/@ionic-native/plugins/diagnostic/index.ts

There was a documentation commit a few days ago that addressed this specific method, but the docs and the code don't seem to line up. 

Please let me know if you can guide me in the right direction.

**Comment by dpa99c** [comment]
The Typescript wrapper for this plugin is maintained by Ionic - please raise this issue against [Ionic Native](https://github.com/ionic-team/ionic-native/)
