### ISSUE TITLE
androidx version problem

### ISSUE THREAD

**Issue by merihs** [dpa99c/cordova-diagnostic-plugin#404]
Hi,
I get the following error during compile. Does anyone know the solution?

Java 9.0.4
Cordova 9.0.0 (cordova-lib@9.0.1)
Ionic 6.10.1
Gradle 6.5.1
cordova.plugins.diagnostic: "^6.0.0"

`
> cordova.cmd build android --device
[ng] Date: 2020-07-16T21:42:54.312Z - Hash: 136f3afb9f7ff781b7d6
[ng] 128 unchanged chunks
[ng] Time: 9440ms
[ng] : Compiled successfully.
[cordova]
[cordova] FAILURE: Build failed with an exception.
[cordova]
[cordova] * What went wrong:
[cordova] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[cordova] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[cordova]    > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
[cordova]      Required by:
[cordova]          project :app
[cordova]       > Cannot find a version of 'androidx.versionedparcelable:versionedparcelable' that satisfies the version constraints:
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.versionedparcelable:versionedparcelable:1.0.0'
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]
[cordova]    > Could not resolve androidx.versionedparcelable:versionedparcelable:1.1.0.
[cordova]      Required by:
[cordova]          project :app > androidx.core:core:1.4.0-alpha01
[cordova]       > Cannot find a version of 'androidx.versionedparcelable:versionedparcelable' that satisfies the version constraints:
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.versionedparcelable:versionedparcelable:1.0.0'
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]
[cordova]    > Could not resolve androidx.versionedparcelable:versionedparcelable:1.0.0.
[cordova]      Required by:
[cordova]          project :app > androidx.media:media:1.0.0
[cordova]       > Cannot find a version of 'androidx.versionedparcelable:versionedparcelable' that satisfies the version constraints:
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.4.0-alpha01' --> 'androidx.versionedparcelable:versionedparcelable:1.1.0'
[cordova]            Dependency path 'android:app:unspecified' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.versionedparcelable:versionedparcelable:1.0.0'
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]            Constraint path 'android:app:unspecified' --> 'androidx.versionedparcelable:versionedparcelable' strictly '1.0.0' because of the following reason: debugRuntimeClasspath uses version 1.0.0
[cordova]
`

Thanks

**Comment by dpa99c** [comment]
There are various possible causes including AndroidX version conflict with another plugin or Gradle version incompatibility.

`cordova.plugins.diagnostic@6` contains breaking changes including migration to AndroidX from the deprecated Android Support Library.

Try building the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which is a known working codebase to validate your build environment.

**Comment by angelofan** [comment]
https://github.com/dpa99c/cordova-plugin-androidx-adapter:
> If your Cordova project contains plugins/libraries which reference both the Android Support Library and AndroidX, your Android build will fail because the two cannot live side-by-side in an Android build.

You may need to cooperate with the following two plugins. After I upgraded the version to cordova-diagnostic-plugin@6.0.0, I installed these two plugins to make my project compile:

[cordova-plugin-androidx](https://github.com/dpa99c/cordova-plugin-androidx): This plugin is useful if your project contains plugins which have migrated to AndroidX or if you otherwise want to enable AndroidX in your Cordova Android platform project.

[cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter): This plugin provides a shim to migrate references to the legacy Android Support Library to the new AndroidX mappings in a Cordova Android platform project.

**Comment by dpa99c** [comment]
@angelofan you are correct - v6.0.0 contains a breaking change (hence the major version increase) which moves from Android Support Library to AndroidX as outlined in [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#androidx-library).

This is why pinning `@*` or `@latest` on any dependency is a bad idea as major version increments likely contain breaking changes that require you to take action - much better to pin `@^x.y.z` so you get the minor and patch version increments but not major versions.

Closing this since no response from @merihs

**Comment by merihs** [comment]
Thanks all, I downgraded to version 5.0.2 and It works now.
