### ISSUE TITLE
feat: Capacitor Support

### ISSUE THREAD

**Issue by EinfachHans** [dpa99c/cordova-diagnostic-plugin#407]
# Feature request

I want to switch to Capacitor with my Apps and in nearly every App i used this Plugin. What would be needed to add official  Support for Capacitor? I think the main Problem is that the Hooks don't work in Capacitor why the **enabling/disabling** of Modules doesn't work?

Maybe create a Support Plan to finance your work on this like [the official Cordova Google Maps Plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)?

**Comment by KiranUppunda** [comment]
@EinfachHans , were you able to add this with capacitor ?  I am trying to integrate diagnostic with capacitor, but app is getting crashed. 
 
This is the error, 

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null `

**Comment by sertal70** [comment]
Hi all,
I've been able to install and run the plugin in a Ionic+Capacitor project, simply following these steps:

1) create the config.xml file on the root of the Ionic project containing your needed permissions:
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="my.beautiful.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <preference name="cordova.plugins.diagnostic.modules" value="LOCATION NOTIFICATIONS <etc>" />
</widget>
```

2) install the plugin:
`npm i cordova.plugins.diagnostic --save`

3) sync platform projects
`npx cap sync`

That's all. As for now I've tested it on Android, soon I'll check on iOS and update this issue.

**Comment by raykin** [comment]
I try several different ways to apply the plugin with Capacitor.  I got several conclusions. 
1. Can't use it with @ionic-native/diagnostic. It just has compile error even function doesn't called at all. I doesn't inject service into root, so compile error only happened when related service is loaded.
Here is the code snippet 
``` typescript
import { Diagnostic } from '@ionic-native/diagnostic/ngx';
@Injectable()
export class QueryLocationService {
```
I have such error in Xcode console.
```
⚡️  [error] - resolvePromise@capacitor://localhost/polyfills.js:3425:48 [angular]
resolvePromise@capacitor://localhost/polyfills.js:3377:35 [angular]
capacitor://localhost/polyfills.js:3487:35 [angular]
onInvokeTask@capacitor://localhost/vendor.js:86707:43 [angular]
drainMicroTaskQueue@capacitor://localhost/polyfills.js:3196:46 [<root>]
invokeTask@capacitor://localhost/polyfills.js:3111:44 [<root>]
invokeTask@capacitor://localhost/polyfills.js:4248:24 [<root>]
globalZoneAwareCallback@capacitor://localhost/polyfills.js:4274:31 [<root>]
```
2. Can work with Capacitor. I only test one function.
```typescript
  requestPermission() {
    return new Promise((resolve, reject) => {
      (<any>window).cordova.plugins.diagnostic.isLocationAuthorized((res) => {
        console.debug("cordova.plugins.diagnostic.isLocationAuthorized ==>")
        console.debug(res);
        resolve(res);
      }, (err) => {
        reject(err);
      })
    })
  }
```
3. Capacitor doesn't read config.xml at all. So I don't know where to config single module.
