### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by indraraj26** [dpa99c/cordova-diagnostic-plugin#410]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
I have checked your ionic example and took config.xml permission from there.
Application is not able to compile if i add this lines in config.xml
```
 <config-file parent="/*" target="AndroidManifest.xml">
        <uses-permission android:name="android.permission.RECORD_AUDIO" />
        <uses-permission android:name="android.permission.CAMERA" />
    </config-file>
```
error
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     D:\ionic\my-project\platforms\android\app\src\main\res\xml\config.xml:91: AAPT: error: unbound prefix.
         
     D:\ionic\my-project\platforms\android\app\src\main\res\xml\config.xml: AAPT: error: file failed to compile.
```
**Expected behavior:**

It should compile successfully.

**Steps to reproduce:**

**Screenshots**

**Environment information**
```
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.8.0 (update available: 0.15.1)
   native-run  : 0.2.9 (update available: 1.0.0)

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

https://github.com/dpa99c/cordova-diagnostic-plugin/issues/411

**Comment by dpa99c** [comment]
You need to add the android XML namespace to your `config.xml`:

    xmlns:android="http://schemas.android.com/apk/res/android"

See [the example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example/blob/master/config.xml#L2) for reference.
