### ISSUE TITLE
getting denied always for microphone permission

### ISSUE THREAD

**Issue by indraraj26** [dpa99c/cordova-diagnostic-plugin#411]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Below code does not invoke popup permission for microphone, With requestRunTimePermission it is crashing the application at startup.

```
async getPermissionMicrophone() {
        try {
            const microPhoneAuthorized = await this._diagnostic.isMicrophoneAuthorized();
            console.log(microPhoneAuthorized, 'authorized');
            if (!microPhoneAuthorized) {
                // It is not requesting to get Microphone permission
                const requestMicroPhonePermission = await this._diagnostic.requestMicrophoneAuthorization();
                console.log(requestMicroPhonePermission);
                // here i always getting DENIED_ALWAYS
                return requestMicroPhonePermission;
            }
        } catch (e) {
            console.log(e, 'error in get permission microphone');
        }
    }
```
```
async getRequestRunTimePermission() {
        try {
            const request = await this._diagnostic.requestRuntimePermission(
                cordova.plugins.diagnostic.permission.RECORD_AUDIO,
            );
            console.log(request);
        } catch (e) {
            console.log(e, 'error in get runtime permssion');
        }
    }
```
**Expected behavior:**
It should invoke microphone permission and should not crash.

**Steps to reproduce:**

**Screenshots**

**Environment information**
```
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 9 other plugins)

Utility:

   cordova-res : 0.8.0 (update available: 0.15.1)
   native-run  : 0.2.9 (update available: 1.0.0)

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

```

**Related code:**

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

https://github.com/dpa99c/cordova-diagnostic-plugin/issues/410

**Comment by dpa99c** [comment]
You haven't fully completed the issue template to supply the exception details that caused the crash or specified what platform/version you are testing on, but given the other issue you opened, the crash is almost certainly because the `RECORD_AUDIO` permission is not present in your `AndroidManifest.xml`.

Please see the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for reference and you can build & run it to validate that the plugin functions correctly when the necessary build-time permissions are added.
