### ISSUE TITLE
[FEATURE] iOS 14 Local Network permission

### ISSUE THREAD

**Issue by kumibrr** [dpa99c/cordova-diagnostic-plugin#415]
# Feature request: Local network permission

In iOS 14 this new privacy feature was introduced, and it is requested whenever the app uses a protocol like smb or just connecting to a http server under the "**NSLocalNetworkUsageDescription**" key.

![](https://lostmoa.com/static/blog/GettingReadyForNewiOS14LocalNetworkPrivacyRestrictions/PrivacyWarning@2x.64kObWhFEOqZtkWBF8_ZYq9MUGHRAcjzejEWFIkmVF8.png)

 It would be nice to be implemented in the plugin as iOS 14 official launch approaches and would make it difficult for some apps to work without asking for it at an adequate time.

Here's a relevant WWDC video tutorial:
[https://developer.apple.com/videos/play/wwdc2020/10110/](url)

And here's a relevant article that summarises what's in the video:
[https://lostmoa.com/blog/GettingReadyForNewiOS14LocalNetworkPrivacyRestrictions/](url)

**Comment by dpa99c** [comment]
Looking at the documentation, there is no corresponding native request method for this permission (unlike the other iOS permissions supported by this plugin) - it is implicitly requested when making a URL request.

Therefore only the `NSLocalNetworkUsageDescription` message key is required to be added to the `*-Info.plist` for iOS 14, which does not require this plugin; you can simply add it via a `<config-file>` block in your `config.xml`:

        <config-file platform="ios" target="*-Info.plist" parent="NSLocalNetworkUsageDescription">
            <string>This app requires access to local network devices because...</string>
        </config-file>

So I'm closing this on the basis that there is nothing that this plugin needs to implement for this new permission.
