### ISSUE TITLE
requestLocationAuthorization is GRANTED but GPS not actually getting enabled

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-diagnostic-plugin#418]
# Bug report

**CHECKLIST**
- [x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x ] I confirm this is a suspected bug or issue that will affect other users

- [x ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x ] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

_This is happening on Android:_

```
      cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
        if (status == cordova.plugins.diagnostic.permissionStatus.GRANTED || status == cordova.plugins.diagnostic.permissionStatus.GRANTED_WHEN_IN_USE) {
          errMgmt("index/gpsPermission",112.7,"gpsPermission: GPS GRANTED") ;  
          gpsSuccess() ;
        } else {
          errMgmt("index/gpsPermission",112.8,"gpsPermission: GPS Not Granted") ;  
          gpsTrackState() ;
        }
      }, function(error){
        errMgmt("index/gpsPermission",112.11,"gpsPermission: error = "+error) ;  
      }, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS);

```
No window prompt is presented to the user yet in the console, the `GPS GRANTED` is displayed and the GPS is still off on the phone.  I use virtually the same code during app initialization and it prompts the user, but the above code does not....but acts like it does.

**Expected behavior:**

User should be presented a prompt to allow or not allow gps to be turned on.  But its not happening.  I verified the app had already previously accepted permissions to use location services, so its not a DENIED_ALWAYS issue.

My app checks for this permission in two places.  Once upon app initialization to ask for GPS permission (works fine)....and later in main app (after install) that checks for GPS status everytime the app is run - if its not enabled it then asks user to enable it.   Both calls are the same, the first one during app init works fine and shows the prompt, the second one does not - the second one though seems to treat `requestLocationAuthorization` like its `getAuthorizationStatus` as it displays the `GPS GRANTED` message but never prompts the user.

** Additional **

_WORKS_ This app init function works, but it only executes once during app initialization, it uses $q.defer to ensure permissions are stepped through in order and don't over lap each other.
```
  function getLocationAuth() {
    var q = $q.defer() ;
    cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
      if (status === cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED) {
        cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
          q.resolve(status) ;
        },function(err) {errMgmt("ctrl/init",1000.1,"GPS/Location ask Permission error: "+err) }) ;
      } else {
        q.resolve(status) ;
      }
    },function(err) {
      errMgmt("ctrl/init",1000.2,"GPS/Location check Permission error: "+err) ;
      q.resolve(err) ;
    });
    return q.promise ;
  }
```

_DOESN'T WORK_   This is the in-app function that checks gps status everytime app is run, this is the one that isn't working, with GPS turned off on phone, start app - app checks status, see's its disabled and calls `gpsPermission()`, but the app permission never gets prompted, yet `gpsPermission: GPS GRANTED` does get printed to console and yet the GPS is still disabled on the phone.  On a side note, I was using another plugin here `cordova-plugin-dialoggps` to prompt the user (and enable gps) - it was working but I am replacing older plugins to eliminate future deprecation issues.  The `dialoggps` was in the `gpsPermission` and is now replaced with the diagnostics code.

In fact, the below code is to replace older code that used plugins `CheckGPS.check`, `cordova.dialogGPS` and `cordova.plugins.locationAccuracy.request` to ask for permission if GPS was turned off (after app init). 

```
function globalGPS() {
  cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
    if (enabled == "enabled") {
      errMgmt("index/globalGPS",112.1,"GPS is already enabled") ;
      gpsSuccess() ;
    } else {
      errMgmt("index/globalGPS",112.2,"GPS is not enabled, asking user") ;
      gpsPermission() ;  <----- this executes
    }
  }, function(error){
      gpsFailure()  ;  
  });  
}  

function gpsPermission() {
      cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
        if (status == cordova.plugins.diagnostic.permissionStatus.GRANTED || status == cordova.plugins.diagnostic.permissionStatus.GRANTED_WHEN_IN_USE) {
          errMgmt("index/gpsPermission",112.7,"gpsPermission: GPS GRANTED") ;  
          gpsSuccess() ;
        } else {
          errMgmt("index/gpsPermission",112.8,"gpsPermission: GPS Not Granted") ;  
          gpsTrackState() ;
        }
      }, function(error){
        errMgmt("index/gpsPermission",112.11,"gpsPermission: error = "+error) ;  
      }, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS);
    } 
  }
}  

```

**Environment information**

Ionic:
   Ionic CLI         : 6.10.1 (C:\Users\RPO\AppData\Roaming\nvm\v10.21.0\node_modules\@ionic\cli)
   Ionic Framework   : ionic1 1.0.0
   @ionic/v1-toolkit : 1.0.22

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 29 other plugins)

Utility:
   cordova-res : 0.15.1
   native-run  : 1.0.0

System:
   NodeJS : v10.21.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.4
   OS     : Windows 7
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by rolinger** [comment]
For now I had to roll back to request-location-accuracy....I modified the above to the following now, I did eliminate two legacy plugins, but would love to get `requestLocationAuthorization` to work properly here so I could get rid of one more plugin.  I didn't realize you wrote that one too, but its a bit bloated in size and in theory I should only have to use `diagnostics` to do everything.  Just can't figure out why its not prompt the user (but this one does).

function globalGPS() {
  cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
    if (enabled == "enabled") {
      console.log("GPS location is " + (enabled ? "enabled" : "disabled"));
      errMgmt("index/globalGPS",112.1,"GPS is already enabled") ;
      gpsSuccess() ;
    } else {
      // not enabled, need to ask user
      errMgmt("index/globalGPS",112.2,"GPS is not enabled, asking user") ;
      var gpsTitle = "Please Turn on GPS" ;
      var gpsMsg = "Searches will be inaccurate AND  most event check-ins require GPS Proximity checks." ;
      cordova.plugins.diagnostic.getLocationAuthorizationStatus(function(status){
        if (status == cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS || status == cordova.plugins.diagnostic.permissionStatus.DENIED_ONCE) {        
          navigator.notification.confirm(gpsMsg, gpsSettings, gpsTitle, ["Turn On","Cancel"]) ;
        } else {
          cordova.plugins.locationAccuracy.request(gpsSuccess, gpsFailure, cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY);
        }
      }) ;
    }
  }, function(error){
      errMgmt("index/globalGPS",112.3,"GPS: something went wrong, not enabled") ;  
      gpsFailure()        
  });  
}

**Comment by dpa99c** [comment]
When the user grants permission via `requestLocationAuthorization()` on Android, this grants the app permission to access the device location, however it **does not** cause the device Location (GPS) setting to be enabled if the user has disabled it.
That can only be achieved via the Play Services API which is what the `request()` method of `cordova-plugin-request-location-accuracy` invokes.
So it is possible for the user to grant the app access to device location but for the device location setting to be turned off.
Therefore the behaviour of this plugin on Android is correct with respect to location permission.

**Comment by rolinger** [comment]
@dpa99c - heh.  I read through all the docs and did not catch that at all.  I guess maybe thats why I originally implemented `request-location-accuracy` way back in the beginning and just forgot that was why.  Sorry for taking up your time.  Quick question - all this rework stuff is a result of migrating from UIWebView to WKWebView and my app getting rejected multiple times by Apple - certain plugins still have references to UIWebView and I am having a devil of a time finding the culprit so I am removing legacy/older plugins that don't seem to be maintained anymore.  Even if not the culprit, its just prudent I do it anyway.  The upside its easier code to maintain while also giving my app a smaller footprint.  Do any of your following plugins have references to UIWebView that would cause app rejection (man, I didn't realize how many of these are yours until I tallied them below - sending my annual $$$ your way shortly):

cordova-custom-config v5.1.0 
cordova-launch-review v4.0.0
cordova-plugin-androidx v2.0.0
cordova-plugin-androidx-support v1.1.1
cordova-plugin-firebasex v10.1.2-cli
cordova-plugin-request-location-accuracy v2.3.0
cordova.plugins.diagnostic v6.0.2

...am I missing anything?  I am about to force my legacy app up to cordova-ios 6.1.1 because I think its the easier route of trying to purge my app of UIWebView which should make it easier to identify legacy/culprit plugins, but still - this is a royal pain in the a$$.

**Comment by dpa99c** [comment]
the only possible one that contains a UIWebView reference is cordova-plugin-firebasex because older versions of the Firebase SDK for iOS referenced UIWebView. I can't remember exactly which version of the plugin updates the Firebase SDK to a version which switches to UIWebView but if you use the latest version then it's definitely free of UIWebView.

There are ways to identify any 3rd party frameworks in your app which reference UIWebView - [see here](https://levelup.gitconnected.com/how-to-find-and-remove-uiwebview-uses-in-your-ios-app-d9395f7baacc)

**Comment by rolinger** [comment]
@dpa99c - I did a scan of firebasex 10.1.2 plugin and it did not return any UIWebView references.  And I finally found the culprit plugin - it was `twitter-connect-plugin`.  Finally got this last version of app submitted to store....now for the next herculean task - finally upgrading everything.  Gonna need a vaca and lots of alcohol before I start down that rabbit hole though.  :-(
