### ISSUE TITLE
requestRuntimePermissions: 'result' undefined

### ISSUE THREAD

**Issue by michael-aisys** [dpa99c/cordova-diagnostic-plugin#42]
It seems checkForInvalidPermissions is getting called and "result" is undefined:

> var valid = true, invalidPermissions = [];
> ...
> if(invalidPermissions.length > 0) {
> 	errorCallback("Invalid permissions specified: "+**result**.invalidPermissions.join(", "));
> }

Does the variable "result" need to be there?

**Comment by dpa99c** [comment]
Looks like an erroneous reference in the code - will push out a fix. Thanks for reporting.
