### ISSUE TITLE
window.cordova.plugins.diagnostic.registerBluetoothStateChangeHandler doesn't work on Android 5.1.1

### ISSUE THREAD

**Issue by vincenzobologna** [dpa99c/cordova-diagnostic-plugin#421]
Hello, I have a cordova application with vuejs. It works pretty fine, but a specific method of your plugin doesn't works on Android version 5.1.1.

Some packages versions in my project:
"cordova": "9.0.0"
"cordova-android": "^9.0.0"
"cordova-plugin-androidx": "^3.0.0"
"cordova-plugin-androidx-adapter": "^1.1.1"
"cordova.plugins.diagnostic": "^6.0.2"

First of all i can run window.cordova.plugins.diagnostic.isBluetoothAvailable fine, but the function that i can run is:

_window.cordova.plugins.diagnostic.registerBluetoothStateChangeHandler((state) => {
   // it never enter here executing with Android 5.1.*
});_

some suggestions?

thanks in advance

**Comment by dpa99c** [comment]
Please build and run the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) app as a known working reference to eliminate possible causes within your own codebase.

**Comment by vincenzobologna** [comment]
Ok i tried example project and i compare my code. The problem is when i try to unregister the bluetoothstatechangehandler, using this:

_window.cordova.plugins.diagnostic.registerBluetoothStateChangeHandler(false)_

in this case the method stop to works. i need to unregister in order to use it only in certain cases.

**Comment by dpa99c** [comment]
`registerBluetoothStateChangeHandler` enables you to register a singleton handler. Passing `false` will replace that handler with an empty function. If you require more complex behaviour, I suggest you add that logic in your handler function and leave it registered.
Closing as I don't believe there is any issue with the current plugin implementation.
