### ISSUE TITLE
iOS - If an app would like to connect to devices on your local network

### ISSUE THREAD

**Issue by 1x2x3x4x** [dpa99c/cordova-diagnostic-plugin#426]
With iOS 14 some changes have been implemented (of course) when tying to call an IP on the user's network. 

Let's say you're trying to configure a device and need to connect to its SSID or by calling the IP directly - IoT devices for example, iOS now gives us an alert about what's going to happen. 

Is it possible to check beforehand if the app already gave that permission? 

Here's a link to the official documentation, where there's details and images with the alert I'm talking about:

https://support.apple.com/en-mk/HT211870

# Feature request

**Comment by igorsantos07** [comment]
For anyone subscribed and still marginally interested, I reopened this at #524
