### ISSUE TITLE
Low vulnerability due to minimist < 1.2.3

### ISSUE THREAD

**Issue by arjel** [dpa99c/cordova-diagnostic-plugin#431]
Hi, is it possible to bump the version of minimist used in this plugin?
https://npmjs.com/advisories/1179

**Comment by mread1208** [comment]
I opened #416 to address issue #394 months ago, but still haven't heard anything on it.

**Comment by arjel** [comment]
Hi @mread1208 thank you.
Didn't see #394 as it's already closed.

@dpa99c I get your reasoning on #394 but I would really appreciate if you could update minimist.

Thank you for the good work!
