### ISSUE TITLE
Please PLease bump minimist in package.json

### ISSUE THREAD

**Issue by iva2k** [dpa99c/cordova-diagnostic-plugin#432]
I can't feed your explanations why it is not a security issue to our strict security team which sees report in `npm audit`.

Please bump minimist to 1.2.5 in package.json.

You probably already spent way more time typing why not and closing all these previously opened issues. They will keep coming.

**Comment by dpa99c** [comment]
This is why I'm giving up on open source.
99% of the issues opened are a waste of time and I have better things to do with my life.
Expect no new releases or one when I actually need something for my own project.
