### ISSUE TITLE
This project uses AndroidX dependencies

### ISSUE THREAD

**Issue by 18825607789** [dpa99c/cordova-diagnostic-plugin#438]
cordova-android@9.1.0 build android error ： This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.lifecycle:lifecycle-runtime:2.3.1, androidx.fragment:fragment:1.3.4, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.annotation:annotation:1.3.0-alpha01, androidx.versionedparcelable:versionedparcelable:1.1.1, androidx.appcompat:appcompat:1.4.0-alpha02, androidx.annotation:annotation-experimental:1.0.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1, androidx.interpolator:interpolator:1.0.0, androidx.emoji2:emoji2-views-helper:1.0.0-alpha02, androidx.core:core:1.6.0-beta02, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.activity:activity:1.2.3, androidx.appcompat:appcompat-resources:1.4.0-alpha02, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.arch.core:core-common:2.1.0, androidx.savedstate:savedstate:1.1.0, androidx.startup:startup-runtime:1.0.0, androidx.lifecycle:lifecycle-common:2.3.1, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.tracing:tracing:1.0.0, androidx.emoji2:emoji2:1.0.0-alpha02, androidx.lifecycle:lifecycle-viewmodel:2.3.1, androidx.resourceinspection:resourceinspection-annotation:1.0.0-alpha02, androidx.legacy:legacy-support-v4:1.0.0, androidx.media:media:1.0.0, androidx.lifecycle:lifecycle-livedata-core:2.3.1, androidx.arch.core:core-runtime:2.1.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.1.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.vectordrawable:vectordrawable:1.1.0, androidx.print:print:1.0.0

**Comment by mhdshuhaib1704** [comment]
Have you solved this issue ? im also facing same error...

**Comment by ljnMeow** [comment]
I did not solved this problem, so i chose to reduce the plugin version

**Comment by dpa99c** [comment]
This plugin depends on the AndroidX library. 

If you're using `cordova-android@9`, then set the preference in `config.xml` to enable AndroidX [as documented in the release notes](http://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html):

    <preference name="AndroidXEnabled" value="true" />

Or update to the newly-released `cordova-android@10` which enables AndroidX by default.

You can verify your build environment against a known, working codebase by building the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example).
