### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found

### ISSUE THREAD

**Issue by swadeshkamlesh** [dpa99c/cordova-diagnostic-plugin#440]
While building apk  we are facing this issue --  AAPT: error: resource android:attr/lStar not found
All new project and old project

Execution failed for task ':app:processDebugResources'.
 FAILED
> Android resource linking failed
  C:\Users\kamlesh\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0-beta01.aar\97b333eeae39b4b443d1c2079f33a72e\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
23 actionable tasks: 21 executed, 2 up-to-date
D:\ionic\carworld\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\kamlesh\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0-beta01.aar\97b333eeae39b4b443d1c2079f33a72e\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by ucsbricks** [comment]
This issue is related to `androidx.appcompat:appcompat` 1.4.0-beta01 released on September 29, 2021. 

As `plugin.xml` defines `ANDROIDX_VERSION` as major version 1 (`1.+`), 1.4.0-beta01 was used instead of 1.3.0. Unfortunately you cannot simply use `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION=1.3.+` to overwrite the value, as the same version would be used for `androidx.legacy:legacy-support-v4` which exists as version 1.0.0 only.

I successfully used `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION="[1.0, 1.4["` to get my builds fixed.

**Comment by ucsbricks** [comment]
I created a PR which to fix plugin.xml https://github.com/dpa99c/cordova-diagnostic-plugin/pull/441

**Comment by Doomkyn** [comment]
> This issue is related to `androidx.appcompat:appcompat` 1.4.0-beta01 released on September 29, 2021.
> 
> As `plugin.xml` defines `ANDROIDX_VERSION` as major version 1 (`1.+`), 1.4.0-beta01 was used instead of 1.3.0. Unfortunately you cannot simply use `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION=1.3.+` to overwrite the value, as the same version would be used for `androidx.legacy:legacy-support-v4` which exists as version 1.0.0 only.
> 
> I successfully used `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION="[1.0, 1.4["` to get my builds fixed.

This did not work for me. Still got the same error:

`
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0-beta01.aar\44d19d1897a0637d7141365a653800f4\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.   

  error: failed linking references.
`

**Comment by phal0r** [comment]
I think PR #441 would also solve the problem for Capacitor. We cannot use install variables in Capacitor, so for us also 1.4.0-beta01 is installed, which breaks, because compileSdk is currently 30, but the plugin has a minium of 31 set.

**Comment by dpa99c** [comment]
The fix for this has been published to npm in v6.0.4
Note you may need to update the value for the `ANDROIDX_VERSION` plugin variable in your project's `package.json` and `plugins/fetch.json` to align with the new default set in this plugin's `plugin.xml`

**Comment by Harsh8796** [comment]
Try to install again cordova.plugins.diagnostic. using 
if you are capacitor user 
**npm install cordova.plugins.diagnostic
npm install @ionic-native/diagnostic
ionic cap sync**
and if you are 
**ionic cordova plugin add cordova.plugins.diagnostic
npm install @ionic-native/diagnostic**

**Comment by ProximaHaiz** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440#issuecomment-932734553
It have worked for me, thank you

**Comment by Techpro-naitik** [comment]
can you explain this  issue in case of capacitor .& how to resolve this issue .

**Comment by damsorian** [comment]
> [#440 (comment)](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440#issuecomment-932734553) It have worked for me, thank you

@ProximaHaiz it's worked for you, with capacitor or cordova?

**Comment by tameemkazia35** [comment]
> Try to install again cordova.plugins.diagnostic. using if you are capacitor user **npm install cordova.plugins.diagnostic npm install @ionic-native/diagnostic ionic cap sync** and if you are cordova user **ionic cordova plugin add cordova.plugins.diagnostic npm install @ionic-native/diagnostic**

Thanks it worked for me

**Comment by Harsh8796** [comment]
> can you explain this issue in case of capacitor .& how to resolve this issue .



> can you explain this issue in case of capacitor .& how to resolve this issue .

Just re-run this command

npm install cordova.plugins.diagnostic
npm install @ionic-native/diagnostic
ionic cap sync

**Comment by jlmosconi** [comment]
> This issue is related to `androidx.appcompat:appcompat` 1.4.0-beta01 released on September 29, 2021.
> 
> As `plugin.xml` defines `ANDROIDX_VERSION` as major version 1 (`1.+`), 1.4.0-beta01 was used instead of 1.3.0. Unfortunately you cannot simply use `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION=1.3.+` to overwrite the value, as the same version would be used for `androidx.legacy:legacy-support-v4` which exists as version 1.0.0 only.
> 
> I successfully used `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION="[1.0, 1.4["` to get my builds fixed.

Thanks! it worked for me. (Cordova)

and upgrade targetSdkVersion to 31
`<preference name="android-targetSdkVersion" value="31" />`

**Comment by GianLucaFinelli** [comment]
> > This issue is related to `androidx.appcompat:appcompat` 1.4.0-beta01 released on September 29, 2021.
> > As `plugin.xml` defines `ANDROIDX_VERSION` as major version 1 (`1.+`), 1.4.0-beta01 was used instead of 1.3.0. Unfortunately you cannot simply use `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION=1.3.+` to overwrite the value, as the same version would be used for `androidx.legacy:legacy-support-v4` which exists as version 1.0.0 only.
> > I successfully used `cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION="[1.0, 1.4["` to get my builds fixed.
> 
> This did not work for me. Still got the same error:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-1.4.0-beta01.aar\44d19d1897a0637d7141365a653800f4\res\values\values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.   
> 
>   error: failed linking references.
> ```

I get the same result, it didn't work for me
