### ISSUE TITLE
Expand Diagnostic.permissionStatus to feature more permission statuses

### ISSUE THREAD

**Issue by matt-auckland** [dpa99c/cordova-diagnostic-plugin#443]
So in #437 I added in the `AUTHORIZATION_PROVISIONAL` and `AUTHORIZATION_EPHEMERAL` consts into the iOS side of the plugin, and I wonder if I should update the `Diagnostic.permissionStatus` object in the JS side of the plugin to include these?

I imagine there may be some other forms of status that could also be included, e.g. Precise Location and Approximate Location.

I'm happy to do the work and add all of these @dpa99c, just wondering if you had suggestions as to what other statuses are missing or if you think some shouldn't be added for whatever reason.

**Comment by michael-roewin** [comment]
HI, I've encountered an issue in building my IOS app when using the 6.0.4 version of the cordova-diagnostic-plugin.

`/Users/runner/work/1/s/ios/capacitor-cordova-ios-plugins/sources/Cordova.plugins.diagnostic/Diagnostic_Notifications.m:130:38: error: use of undeclared identifier 'UNAuthorizationStatusEphemeral'; did you mean 'UNAuthorizationStatusDenied'?
                    if(authStatus == UNAuthorizationStatusEphemeral) {
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     UNAuthorizationStatusDenied`

Is this somehow related to this issue?

**Comment by matt-auckland** [comment]
Which version of XCode are you using? I wonder if older versions don't support this (https://developer.apple.com/documentation/usernotifications/unauthorizationstatus/ephemeral)

I had no issues building with XCode 12 or 13.

**Comment by netenDeveloper** [comment]
@matt-auckland 
perhaps this log will be help,,,
Xcode 11.3

[build_log_6163a26be78885744fa7c698_2021-10-16 11_55_57.log](https://github.com/dpa99c/cordova-diagnostic-plugin/files/7356917/build_log_6163a26be78885744fa7c698_2021-10-16.11_55_57.log)

**Comment by matt-auckland** [comment]
If possible I would try building with a newer version of XCode, I think that support for the "Emphermeral Status" was added in XCode 12.
