### ISSUE TITLE
Request bluetooth permissions on Android

### ISSUE THREAD

**Issue by chladnefazole** [dpa99c/cordova-diagnostic-plugin#448]
Hello, how do we request BT permissions on Android?

When using function `requestRuntimePermission`, we have to pass in a permission defined on the `cordova.plugins.diagnostic.runtimePermission` object.

However, BLUETOOTH, BLUETOOTH_SCAN, BLUETOOTH_CONNECT, etc. do not exist on the `cordova.plugins.diagnostic.runtimePermission` object, [as listed here](https://github.com/dpa99c/cordova-diagnostic-plugin#dangerous-runtime-permissions). Therefore it's not possible to request these permissions directly.

And function `requestBluetoothAuthorization` only works on iOS platform.

How should we request the BT permissions on Android?

**Comment by zmoshansky** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin/pull/465
