### ISSUE TITLE
Android getLocationMode() always return 3

### ISSUE THREAD

**Issue by hiraringo** [dpa99c/cordova-diagnostic-plugin#449]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Android getLocationMode() always return 3
Method can provide a wrong value.
It behaves as if the Location Mode is always "HIGH_ACCURACY".

****

**Expected behavior:**

Android getLocationMode() return a value of divice settings.

**Steps to reproduce:**

call getLocationMode()

**Screenshots**

None

**Environment information**

- Cordova CLI version 
	- 10.0.0
- Cordova platform version
	- android 9.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova.plugins.diagnostic 6.1.0 "Diagnostic"
- Dev machine OS and version, e.g.
    - Android

_Runtime issue_
- Device details
    - Pixel XL Emulator
- OS details
    - API Level 29

**Other information:**

- API Changes
  - Settings.Secure.LOCATION_MODE
    - This constant was deprecated in API level 28. 
  - Settings.Secure.LOCATION_MODE_HIGH_ACCURACY
    - This mode no longer has any distinct meaning, but is interpreted as the location mode is on.
[https://developer.android.com/reference/android/provider/Settings.Secure](https://developer.android.com/reference/android/provider/Settings.Secure)

- **Solution**
  - Now we can use the same way as before API level 18.
  - Need a little code fix as follows

```
src/android/Diagnostic_Location.java
L274
- if (Build.VERSION.SDK_INT >= 19){ // Kitkat and above
+ if (Build.VERSION.SDK_INT >= 19 && Build.VERSION.SDK_INT < 28){ // Kitkat to Oreo

L276
- }else{ // Pre-Kitkat
+ }else{
```

**Comment by dpa99c** [comment]
This has been fixed in the major version `cordova.plugins.diagnostic@7.0.0` which has just been released to npm.
Please re-test with this new version and feedback any issues.
