### ISSUE TITLE
Uncaught ReferenceError: module is not defined in Worklight 7.1

### ISSUE THREAD

**Issue by sunilmhetre** [dpa99c/cordova-diagnostic-plugin#45]
Hi,
I have used plugin in worklight 7.1 hybrid project, when I run the project following error has occured
     On browser- Uncaught ReferenceError: module is not defined
     on android device - undefined is not a function
When I made following changes in diagnostic.js it worked fine
window.Diagnostic = window.Diagnostic || {};
window.Diagnostic = new Diagnostic();

**Comment by dpa99c** [comment]
As [stated in the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#usage): The plugin is exposed via the `cordova.plugins.diagnostic` object

> On browser- Uncaught ReferenceError: module is not defined

The plugin is intended to provide diagnostic utilities in **native** mobile environments, so will not work in the browser
