### ISSUE TITLE
No Callback

### ISSUE THREAD

**Issue by unclespode** [dpa99c/cordova-diagnostic-plugin#46]
I'm requesting a permission, and a couple of other things (isCameraAuthorized etc.) all at the same time, and sometimes I don't get a callback (not even a failure) - almost always on my requestRuntimePermission.

Is this an issue, or is it considered best practice to chain these requests rather than async?

**Comment by dpa99c** [comment]
The plugin is invoking the underlying native Android permissions API to carry out these requests, so I would assume that multiple async calls to the permissions API may result in Android ignoring/mishandling some. I would recommend chaining the requests so only a single one is made concurrently; this will hopefully resolve your issue.
