### ISSUE TITLE
Support new Android 12 Bluetooth runtime permissions

### ISSUE THREAD

**Issue by andreyluiz** [dpa99c/cordova-diagnostic-plugin#460]
# Feature request
According to the [Android Developer documentation](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions), new Bluetooth runtime permissions have been implemented and will be supported from Android 12 and above.

This plugin still doesn't support it. 

I have a fork with a basic and working implementation. Check [here](https://github.com/equipapp/cordova-diagnostic-plugin/commit/f2fbdedd10a13d9038bd245c9d1f844f7024ab62). I won't create a PR right now because this commit lacks documentation and supports only the permissions I need in my project. But I have the intention to do so in the future if nobody does it first.

**Comment by zmoshansky** [comment]
Should be resolved when https://github.com/dpa99c/cordova-diagnostic-plugin/pull/465 lands

**Comment by dpa99c** [comment]
This has been fixed in the major version `cordova.plugins.diagnostic@7.0.0` which has just been released to npm.
Please re-test with this new version and feedback any issues.
