### ISSUE TITLE
the minimist v1.2.5 package has critical dependency issue. This needs to be updated to 1.2.6

### ISSUE THREAD

**Issue by michael-roewin** [dpa99c/cordova-diagnostic-plugin#467]
**Findings**
- When doing npm audit, a critical vulnerability issue that's related to the cordova diagnostic plugin appears.

**Screenshots**

![image](https://user-images.githubusercontent.com/8053494/169173724-6b976509-b3f4-4769-b52f-e8296d043389.png)

**Comment by dvag-lukas-rybacki** [comment]
@michael-roewin already fixed in #464

**Comment by dvag-lukas-rybacki** [comment]
@michael-roewin i am also waiting for a new release @dpa99c

**Comment by peitschie** [comment]
As an interim fix, you can install the dependency directly from github instead (there appears to be no compile steps needed here):

```
npm install --save https://github.com/dpa99c/cordova-diagnostic-plugin.git
```

But definitely looking forward to a new release 😸

**Comment by dvag-lukas-rybacki** [comment]
Thats true @peitschie . Thanks for the alternative idea and also looking forward to new release though 😄

**Comment by dpa99c** [comment]
This has been fixed in the major version `cordova.plugins.diagnostic@7.0.0` which has just been released to npm.
Please re-test with this new version and feedback any issues.
