### ISSUE TITLE
build error while changing config.xml file

### ISSUE THREAD

**Issue by krishna-agarwal** [dpa99c/cordova-diagnostic-plugin#47]
adding  \<gap:plugin name="cordova.plugins.diagnostic.api-22" source="npm" /> in config.xml is giving build error.

**Comment by dpa99c** [comment]
Phonegap Build now supports API 23, so instead use:

    <plugin name="cordova.plugins.diagnostic.api" source="npm" />
    <preference name="android-build-tool" value="gradle" />
