### ISSUE TITLE
CameraRollAuthorizationStatus not including limited (iOS 14.0+)

### ISSUE THREAD

**Issue by sebastian-student** [dpa99c/cordova-diagnostic-plugin#473]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)
- [x] I confirm this is a suspected bug or issue that will affect other users
- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.
- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.
- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
If user selects to only expose selected photos to the app 'authorized' is returned as status.

**Expected behavior:**
If user selects to only expose selected photos to the app 'limited' should be returned as status.

**Steps to reproduce:**
Request authorization status on a device running iOS 14.0 or higher and choose to select images.

**Other information:**
Similar issue exited with #425 but got no response. Information about limited photos access is requiered because some functionality that is cut requires adapting the ui (e.g.: https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app#3695524 or access to metadata).

**Environment information**

- Cordova CLI version: 
10.0.0

- Cordova platform version
Installed platforms:
  ios 6.2.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

- Plugins & versions installed in project (including this plugin)
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 6.0.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 7.0.0 "File"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova.plugins.diagnostic 6.1.1 "Diagnostic"

**Comment by dcxn** [comment]
Hey @dpa99c 👋 , I updated to the most recent version 7.1.0, but when choosing running `requestCameraRollAuthorization()` and choosing the select photos option, it returns `denied_always`. Shouldn't it be the the limited value? 

```js
// example code
diagnostic.getCameraRollAuthorizationStatus(function (authorizationStatus) {
    switch (authorizationStatus) {
        case diagnostic.permissionStatus.NOT_REQUESTED:
            console.log("Permission not requested");
            diagnostic.requestCameraRollAuthorization(function (status) { // select photos option
                console.log("status", status) // Output: "status denied_always"
(...)
```
