### ISSUE TITLE
Plugin returns `denied_always` at first, when choosing `Select photos` permission on iOS 14+

### ISSUE THREAD

**Issue by dcxn** [dpa99c/cordova-diagnostic-plugin#476]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

As mentioned in [this closed issue](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/473#issuecomment-1218249358), on a fresh install of the app on iOS, when the user gets prompted to give access to camera roll and chooses `Select photos...` option and once you close the native popup where you select the photos, the plugin returns `denied_always` as permission status. Only on the second time of trying to select a photo, it will return the proper permission `limited`.

```js
// example code inspired by the plugin doc snippets
cordova.plugins.diagnostic.getCameraRollAuthorizationStatus(function (authorizationStatus) {
    switch (authorizationStatus) {
        case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
            console.log("Permission not requested");
            cordova.plugins.diagnostic.requestCameraRollAuthorization(function(status){
                console.log("status", status) // Output: "status denied_always"
                switch(status){
                    case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                        console.log("Permission denied");
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                        console.log("Permission granted to access all photos");
                        break;
                    case cordova.plugins.diagnostic.permissionStatus.LIMITED: // iOS 14+
                        console.log("Permission granted to access limited set of photos");
                        break;
                }
            }, function(error){
                console.error(error);
            }, cordova.plugins.diagnostic.photoLibraryAccessLevel.READ_WRITE);
            break;
        default:
            break;
    }
});
```

**Expected behavior:**

Plugin returns `limited` status when the user chooses to give `Select photos` permission on clean install.

**Steps to reproduce:**

Use the short code snippet, choose `Select photos` as permission.

**Environment information**

- Cordova CLI version 
	- `cordova -v` = `v11.0.0`
- Cordova platform version
	- `"cordova-android": "^11.0.0",`
	- `"cordova-ios": "^6.2.0",`
- Plugins & versions installed in project (including this plugin)
	- `"cordova.plugins.diagnostic": "^7.1.0",`
	- `"cordova-plugin-camera": "^6.0.0",`
- Dev machine OS and version, e.g.
    - macOS Monterey (latest)
        
_Runtime issue_
- OS details
    - iOS 15.6.1

Thank you

**Comment by expcapitaldev** [comment]
he all, for requestCameraRollAuthorization with limited will be return denied_always, https://github.com/dpa99c/cordova-diagnostic-plugin/blob/7.1.0/www/ios/diagnostic.camera.js#L226 but in documentation is limited , see https://github.com/dpa99c/cordova-diagnostic-plugin#example-usage-54

**Comment by expcapitaldev** [comment]
olso accessLevel as string is required on iOS

**Comment by dpa99c** [comment]
Fix released in `cordova.plugins.diagnostic@7.1.1`
