### ISSUE TITLE
Build error on cordova IOS

### ISSUE THREAD

**Issue by bonjourjoel** [dpa99c/cordova-diagnostic-plugin#479]
# Bug report

**CHECKLIST**
- [x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [ x] I confirm this is a suspected bug or issue that will affect other users

- [ x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [ x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Hi,

When releasing the cordova app for ios, i get the following xcode compiler error:

> ** ARCHIVE FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Users/joel/Library/Developer/Xcode/DerivedData/player22-evzhtkeezoazkeelkwcstskvxrdz/Build/Intermediates.noindex/ArchiveIntermediates/player22/IntermediateBuildFilesPath/player22.build/Release-iphoneos/player22.build/Objects-normal/arm64/Diagnostic_Camera.o /Volumes/dev/player22/platforms/ios/player22/Plugins/cordova.plugins.diagnostic/Diagnostic_Camera.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> xcodebuild: Command failed with exit code 65

This is a link to the full build log with the option --verbose: [full build log with error](https://sharetext.me/bk2ktb8obs)
And this is the build log if i remove the diagnostic plugin: [full build log with success](https://sharetext.me/yak34iqa3q)

If I remove the plugin cordova.plugins.diagnostic to test the compiling again, then it compiles successfully. If i add the plugin again, i get the compiler error again.

But i remove it only to test, because i need it in my app to detect permission errors and propose fixes to users who deny permissions by accident. Does anyone have this error too? Is it related to a recent version of cordova or cordova ios? Would downgrading something fix this? Thanks if anyone has a clue about this because i'm stuck.

**Environment information**

- Cordova CLI version 
	- `cordova -v11.0.0`
- Cordova platform version
	- `android 11.0.0`
	- `browser 6.0.0`
	- `ios 6.2.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova.plugins.diagnostic 7.1.0`
    - `cordova-launch-review 4.0.1 "Launch Review"`
    - `cordova-plugin-calendar 5.1.6 "Calendar"`
    - `cordova-plugin-camera 6.0.1-dev "Camera"`
    - `cordova-plugin-device 2.0.3 "Device"`
    - `cordova-plugin-geolocation 4.1.0 "Geolocation"`
    - `cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"`
    - `cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"`
    - `cordova-plugin-iosrtc 8.0.1 "iosrtc"`
    - `cordova-plugin-iroot 3.1.0 "iRoot"`
    - `cordova-plugin-media 6.0.0 "Media"`
    - `cordova-plugin-wkkeyboardfix 1.1.0 "cordova-plugin-wkkeyboardfix"`
    - `cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"`
    - `es6-promise-plugin 4.2.2 "Promise"`
- Dev machine OS and version, e.g.
    - OSX v11.2.3
        - `sw_vers v5.3.2`
        
	
_iOS build issue:_
- Node JS version
    - `node -v16.14.2`
- XCode version v12.4

**Comment by dpa99c** [comment]
This could be due to a conflict with another plugin.
Please try building the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) which is a known codebase, to validate your build environment.

**Comment by durasj** [comment]
@bonjourjoel

The actual error is:

```
/Volumes/dev/player22/platforms/ios/player22/Plugins/cordova.plugins.diagnostic/Diagnostic_Camera.m:168:54: error: no visible @interface for 'PHPhotoLibrary'
      declares the selector 'presentLimitedLibraryPickerFromViewController:completionHandler:'
                [[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:self.viewController completionHandler:^(NSArray<NSString *...
```

You have to update your XCode so that it supports building for iOS 15. The question is should this be captured in the README - requirements - @dpa99c.

**Comment by bonjourjoel** [comment]
@durasj

Thanks for your help. It was the correct explanation, and the correct fix.
