### ISSUE TITLE
iOS: isMobileDataEnabled() not as documented/uses implementation for differend functionality

### ISSUE THREAD

**Issue by sebastian-student** [dpa99c/cordova-diagnostic-plugin#482]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)
- [x] I confirm this is a suspected bug or issue that will affect other users
- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.
- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.
- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

The example project always returns TRUE for isMobileDataEnabled on iOS. 

The implementation of isMobileDataEnabled for iOS requests if the user has explicetly forbidden this specific app from using mobile data. This permission is independent of the global toggle in settings->Mobile Data/control center.

**Expected behavior:**

Per documentation isMobileDataEnabled() should return the state of settings->Mobile Data toggle. An additional function isMobileDataAuthorized() should return if the app can use mobile data in case it is enabled.

**Steps to reproduce:**

Run example project on iOS and toggle mobile data while rechecking state.

**Other information:**

- toggle to change the per app mobile data permission only appears in per app settings and mobile data settings after the first http request
- default value appears to be kCTCellularDataNotRestricted
- I'm not aware of an equivalent native Android functionality to block specific apps from using mobile data (The closest I have found is blocking data usage from background.)
- intention for #478 was to be able to display a hint to the user should mobile data be enabled but the specific app not authorized to use it

**Comment by DavidWiesner** [comment]
@dpa99c Are there any chances to fix this issue and merging this PR?

**Comment by dAISY-GroupMember** [comment]
@dpa99c Dear Dave, are there any chance for reviewing the pull request and getting an update on this in an upcoming release? Thanks a lot and best wishes P-
