### ISSUE TITLE
 Support Android 13/API 33 media storage permissions

### ISSUE THREAD

**Issue by epetre** [dpa99c/cordova-diagnostic-plugin#488]
Hey guys, do you plan on supporting Android 13 soon?
Other plugins are also trying to and having issues with the WRITE_EXTERNAL_STORAGE permission.

https://github.com/apache/cordova-plugin-camera/pull/814

Are there any plans on supporting it or will this plugin be incompatible with Android 13 / API 33 ?

**Comment by gmbad** [comment]
Hello Dave! 

Can you publish a new release with these changes?

I updated my app to API 33 and I'm having this problem.

Thank you very much,

Gab

**Comment by gmbad** [comment]
Hi Dave!

I got the development version.

In config.xml, should I add READ_MEDIA_IMAGES and READ_MEDIA_VIDEO?

        <custom-config-file parent="/*" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.RECORD_AUDIO" />
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            **<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
            <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />**
        </custom-config-file>  

Thanks!

**Comment by bonjourjoel** [comment]
Hi, this fix looks good. How to install it please?
