### ISSUE TITLE
Permission error  

### ISSUE THREAD

**Issue by fabienwnklr** [dpa99c/cordova-diagnostic-plugin#489]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When i try to connect to my device Bluetooth, error returning this :
```
Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10466, packageName = com.geomatika.isigeoapps, attributionTag = null, token = android.os.BinderProxy@d3d6038, next = null }: AdapterService getBondedDevices
```

But i add manualy this permission into `platform/android/app/src/main/AndroidManifest.xml` and this error laways appear...
Maybe miss something ? But i don't know what ..

**Expected behavior:**
Request Bluetooth access ?

**Steps to reproduce:**
Nothing, just try to connect to bluetooth device..

**Screenshots**
![image](https://user-images.githubusercontent.com/49644785/216370202-acd75631-a0d1-4c3f-8e43-a17e96f580a1.png)

**Environment information**

- Cordova CLI version 
	- `11.0.0`
- Cordova platform version
	- `android 11.0.0`
- Plugins & versions installed in project (including this plugin)
    - cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
    - cordova-plugin-advanced-http 3.3.1 "Advanced HTTP plugin"
    - cordova-plugin-android-permissions 1.1.5 "Permissions"
    - cordova-plugin-app-launcher 0.4.0 "Launcher"
    - cordova-plugin-app-version 0.1.14 "AppVersion"
    - cordova-plugin-badge-fix 0.8.10 "Badge"
    - cordova-plugin-bluetooth-serial 0.4.7 "Bluetooth Serial"
    - cordova-plugin-camera 6.0.1-dev "Camera"
    - cordova-plugin-device 2.1.0 "Device"
    - cordova-plugin-file-opener2 2.2.1 "File Opener2"
    - cordova-plugin-file-transfer 1.7.1 "File Transfer"
    - cordova-plugin-file 6.0.1 "File"
    - cordova-plugin-filepath 1.6.0 "cordova-plugin-filepath"
    - cordova-plugin-geolocation 4.1.0 "Geolocation"
    - cordova-plugin-globalization 1.11.0 "Globalization"
    - cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
    - cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
    - cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-local-notification 0.10.0 "LocalNotification"
    - cordova-plugin-network-information 3.0.0 "Network Information"
    - cordova-plugin-networkinterface 1.2.0 "NetworkInterface"
    - cordova-plugin-photo-library-wkwebview-ionic 3.0.3 "Photo Library"
    - cordova-plugin-qr-barcode-scanner 8.0.3 "BarcodeScanner"
    - cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
    - cordova-plugin-save-image 0.3.0 "SaveImage"
    - cordova-plugin-splashscreen 4.1.0 "Splashscreen"
    - cordova-plugin-statusbar 2.4.3 "StatusBar"
    - cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
    - cordova-sqlite-ext 6.0.0 "Cordova sqlite storage plugin - (...) with extra features"
    - cordova-sqlite-storage 6.1.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
    - cordova.plugins.diagnostic 7.1.1 "Diagnostic"
    - scandit-cordova-datacapture-barcode 6.15.1 "ScanditBarcodeCapture"
    - scandit-cordova-datacapture-core 6.15.1 "ScanditCaptureCore"
- Dev machine OS and version, e.g.
    - windows
        - `11`
        
_Runtime issue_
- Device details
    -Samsung Galaxy A21S
- OS details
    - Android 12	
	
_Android build issue:_	
- Node JS version
    - `16.15.0`
- Gradle version
	- `7.5.1`
- Target Android SDK version
	- `32`
- Android SDK details
	- `No info ?`

![image](https://user-images.githubusercontent.com/49644785/216374760-2a5d1e36-4ed2-466c-8b7f-79bcc86a2e7a.png)

**Comment by dpa99c** [comment]
> But i add manualy this permission into platform/android/app/src/main/AndroidManifest.xml and this error laways appear...

In a Cordova project, the Android manifest is volatile and rebuilt each time `cordova prepare` is run.
You need to add this permission to the `config.xml` to make it permanent, e.g.

```
<platform name="android">
	<config-file parent="/*" target="AndroidManifest.xml">
    	<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
	</config>
</platform>
```
