### ISSUE TITLE
getLocationAuthorizationStatus not working on android 13 with ionic cordova production builds

### ISSUE THREAD

**Issue by willemjanvankranenburg** [dpa99c/cordova-diagnostic-plugin#494]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**
When creating an ionic cordova app for android, **without** signing the APK with apksigner, the plugin asks for the permission for GPS. This should also happen for SIGNED production build.

**Steps to reproduce:**
Run the code below in an ionic 6.5.0 project. If you add the android platform build a signed production APK with zipalign and apksigner and  it on a android 13 device it doesn't ask for the location permissions. If you clean your environment, re-add the android platform, and run it directly without the production steps, it works like normal.

**Screenshots**

The production build (sorry for the dutch language), notice it only has 3 options and
![MicrosoftTeams-image](https://github.com/dpa99c/cordova-diagnostic-plugin/assets/31033654/484ce3ca-3d1f-4f65-8bf7-231f446eeb22)

The debug build, it has an extra option " always allow"
![MicrosoftTeams-image (1)](https://github.com/dpa99c/cordova-diagnostic-plugin/assets/31033654/3122bbec-8a39-4f9f-a8f6-ba9aec8a5e5b)

**Environment information**

- Cordova CLI version 
	- 10.0.0 (cordova-lib@10.1.0)
- Cordova platform version
	- Android 10.1.2
- Plugins & versions installed in project (including this plugin)
    -  cordova-background-geolocation-lt 4.10.0 "BackgroundGeolocation"
    -   cordova-custom-config 5.1.0 "cordova-custom-config"
    -   cordova-plugin-actionsheet 2.3.3 "ActionSheet"
    -   cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
    -   cordova-plugin-app-version 0.1.14 "AppVersion"
    -   cordova-plugin-background-fetch 7.1.2 "CDVBackgroundFetch"
    -   cordova-plugin-background-mode 0.7.3 "BackgroundMode"
    -   cordova-plugin-ble-central 1.6.1 "BLE"
    -   cordova-plugin-camera-preview 0.12.3 "cordova-plugin-camera-preview"
    -   cordova-plugin-camera 6.0.0 "Camera"
    -   cordova-plugin-device 2.0.3 "Device"
    -   cordova-plugin-geolocation 4.1.0 "Geolocation"
    -   cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    -   cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
    -   cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
    -   cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
    -   cordova-plugin-splashscreen 6.0.0 "Splashscreen"
    -   cordova-plugin-statusbar 2.4.3 "StatusBar"
    -   cordova-plugin-vibration 3.1.1 "Vibration"
    -   cordova-support-android-plugin 1.0.0 "cordova-support-android-plugin"
    -   cordova.plugins.diagnostic 6.1.0 "Diagnostic" (also tried it with 7.1.2
    -   es6-promise-plugin 4.2.2 "Promise"
    -   phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
    -   uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.5 "Launch Navigator"

- Dev machine OS and version, e.g.
    - OSX 12.1
        
_Runtime issue_
- Device details
    - OnePlus and Samsung
- OS details
    - Android 13
	
_Android build issue:_	
- Node JS version
    - 16.16.0
- Gradle version
	- 7.3.3
- Target Android SDK version
	- 31

**Related code:**
```
@Injectable()
export class AuthorizationService {

    constructor(private diagnostic: Diagnostic, private platform: Platform) {}

    public async checkAllAuthorizations(): Promise<void> {
        try {
            await this.diagnostic.requestRuntimePermissions([this.diagnostic.permission.ACCESS_COARSE_LOCATION, this.diagnostic.permission.ACCESS_FINE_LOCATION]);
            // Check location
            const locationResponse: string = await this.checkForLocationAuthorization();
            this.isLocationAuthorized = this.convertAuthorizationResponse(locationResponse);

            // Check motion
            const motionResponse: string = await this.checkForMotionAuthorization();
            this.isMotionAvailable = this.convertAuthorizationResponse(motionResponse);

            // Check background location
            const backgroundLocationResponse: string = await this.checkForBackgroundLocalization();
            this.isBackgroundLocalizationAuthorized = this.convertAuthorizationResponse(backgroundLocationResponse);
        } catch (error) {
            alert('Error when asking for permissions' + String(error));
        }
    }

    private async handleAuthorization(
        isAuthorizedFunction: Promise<boolean>,
        requestAuthorizationFunction: Promise<any>
    ): Promise<string> {
        return new Promise<string>(async (resolve, reject) => {
            // Check if the diagnostic plugin is currently not requesting any other permission on android
            if (this.platform.is('ios') || (this.platform.is('android') && !this.diagnostic.isRequestingPermission())) {
                const isAuthorized: boolean = await isAuthorizedFunction;
                if (!isAuthorized) {
                    const response: string = await requestAuthorizationFunction;
                    return resolve(response);
                } else {
                    return resolve(AuthorizationType.GRANTED);
                }
            } else {
                if (this.platform.is('android')) {
                    this.diagnostic.registerPermissionRequestCompleteHandler(async () => {
                        this.diagnostic.registerPermissionRequestCompleteHandler(null);
                        const response: string = await this.handleAuthorization(
                            isAuthorizedFunction,
                            requestAuthorizationFunction
                        );
                        resolve(response);
                    });
                } else {
                    console.error('not ios and not android');
                    reject();
                }
            }
        });
    }
}
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here
There is no output, no errors are loged/thrown.

```

</details><br/><br/>

**Other information:**

tried the workaround in https://github.com/dpa99c/cordova-diagnostic-plugin/issues/422#issuecomment-1206300993 but a few problems;

1. The ionic plugin doesn't have the diagnostic.permission.ACCESS_BACKGROUND_LOCATION
2. The ionic plugin missing features/methods

**Comment by dpa99c** [comment]
This plugin is used in multiple production apps that use background location on both Android & iOS so sounds like a problem with your project/development environment, not this plugin.
The plugin code itself will not behave differently in debug vs release builds.

> 1. The ionic plugin doesn't have the diagnostic.permission.ACCESS_BACKGROUND_LOCATION

https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/android/diagnostic.js#L32

> 2. The ionic plugin missing features/methods

The plugin does not lack the features required to request background location permission on Android 13+ - this is supported and being used in production.

Note that to request background location permission on Android 13+, you must first request and be granted foreground location permission before requesting background location permission:

```
cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
	if(status === cordova.plugins.diagnostic.permissionStatus.GRANTED){
		cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
		   console.log("Background location permission granted");
		}, onError, cordova.plugins.diagnostic.locationAuthorizationMode.ALWAYS, cordova.plugins.diagnostic.locationAccuracyAuthorization.FULL);
	}
}, onError, cordova.plugins.diagnostic.locationAuthorizationMode.WHEN_IN_USE, cordova.plugins.diagnostic.locationAccuracyAuthorization.FULL);
```

You must also include `ACCESS_BACKGROUND_LOCATION` permission in your `AndroidManifest.xml` as well as `ACCESS_FINE_LOCATION`/`ACCESS_COARSE_LOCATION`.

Please refer to the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for reference and to validate the plugin works correctly.

Note this is a Cordova plugin: the Ionic Typescript wrapper for this plugin is not part of the plugin code and is independently maintained.
