### ISSUE TITLE
getBluetoothState() returns OK in SDK 33 even though bluetooth is not enabled/disabled

### ISSUE THREAD

**Issue by mdivya-symplr** [dpa99c/cordova-diagnostic-plugin#496]
Bluetooth is not enabled/ disabled when `getBluetoothState` is called in Android 13 but still returns success response

Starting with Build.VERSION_CODES.TIRAMISU, applications are not allowed to enable/disable Bluetooth.
https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()

**Comment by dpa99c** [comment]
Regression tested with the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) with build SDK = API 33:
`getBluetoothState()` returns the correct result however `setBluetoothState()` has now effect because changing Bluetooth state on API 33+ is not supported.
