### ISSUE TITLE
Android build Error

### ISSUE THREAD

**Issue by nomori7010** [dpa99c/cordova-diagnostic-plugin#498]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

I received the following error.

```
[16:17:25] /tmp/download/platforms/android/app/src/main/java/cordova/plugins/Diagnostic_External_Storage.java:139: error: cannot find symbol
[16:17:25] if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
[16:17:25] ^
[16:17:25] symbol: variable TIRAMISU
[16:17:25] location: class VERSION_CODES
```

When I built the same app two days ago, this error did not occur, and the build was successful.

**Environment information**

- Cordova CLI version 
	- 11.0.0
- Cordova platform version
  - Installed platforms:
  
  - Available platforms: 
    - android ^10.1.1
    - browser ^6.0.0
    - electron ^3.0.0
    - ios ^6.2.0
    - osx ^6.0.0
- Plugins & versions installed in project (including this plugin)
    -  "cordova-custom-config": {},
    -  "cordova-plugin-splashscreen": {},
    - "monaca-plugin-monaca-core": {},
    - "cordova-plugin-camera": {},
    - "cordova-plugin-file": {},
    - "cordova-plugin-inappbrowser": {},
    - "cordova-plugin-geolocation": {},
    - "cordova-plugin-dialogs": {},
    - "ncmb-push-monaca-plugin": {},
    - "cordova.plugins.diagnostic": {},
    - "cordova-plugin-network-information": {},
    - "cordova-plugin-device": {},
    - "cordova-android-support-gradle-release": {},
    - "monaca-plugin-webintent": {},
    - "cordova-plugin-androidx-adapter": {}
- Dev machine OS and version, e.g.
    - OSX
        - 13.4.1（22F82）	

Android build issue:
- Node JS version
    - v18.15.0
- Target Android SDK version
	- 31

**Comment by khurshid444** [comment]
Change the target SDk Version to 33 and build and check . it might work .

**Comment by nomori7010** [comment]
By using 7.1.2, I was able to avoid the problem for now.
