### ISSUE TITLE
Storage permission Issue on Android after updating to API 33

### ISSUE THREAD

**Issue by JeetuChoudhary** [dpa99c/cordova-diagnostic-plugin#499]
**Current behavior:**

After updating the app to target Android API 33. When I try to download an image, it shows the Storage Request dialog stating to allow the app to access files on your device. 

I have tried to request permission again for Android API 33 as you mentioned in the documentation and it doesn't open any permission dialog and shows following message in logs: 

````
Requesting permission for android.permission.READ_EXTERNAL_STORAGE
 
Requesting permissions

Notifying listeners for event pause

No listeners found for event pause

App paused

Unable to find a Capacitor plugin to handle permission requestCode, trying Cordova plugins 0
````

**Expected behavior:**

It should download and store images on the phone after clicking on the download button. 

**Screenshots**

![wxs-screenshot](https://github.com/dpa99c/cordova-diagnostic-plugin/assets/22294704/1fe1eee0-0d42-42cf-b4c0-52dba17245e2)

**Environment information**

 - Ionic CLI: 7.1.1 
 -  Ionic Framework: @ionic/angular 7.2.0
 - @angular/cli: 16.1.0
 - @ionic/angular-toolkit: 9.0.0

Capacitor:
  - Capacitor CLI      : 5.2.2
  - @capacitor/android : 5.2.2
  - @capacitor/core    : 5.2.2
  - @capacitor/ios     : 5.2.2

System:
  - NodeJS : v18.10.0
  - npm    : 8.19.2

- Target Android SDK version
	- `33`
- Plugin Version
	- `"cordova.plugins.diagnostic": "^7.1.2"`

**Comment by Lakshman1996** [comment]
It is happening same after updating to 33. 
https://github.com/apache/cordova-plugin-file/issues/577 Also seems related

**Comment by dpa99c** [comment]
Android 13 / API 33 removes `WRITE_EXTERNAL_STORAGE`/`READ_EXTERNAL_STORAGE` permissions and replaces them with `READ_MEDIA` permissions ([see here](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions))
So requesting `EXTERNAL_STORAGE` permission when build SDK >= 33 will have no effect.
Instead request `READ_MEDIA`, e.g.

```
cordova.plugins.diagnostic.requestRuntimePermission(function(status){
    console.log("Permission: " + status);
}, function(error){
    console.error("The following error occurred: "+error);
}, cordova.plugins.diagnostic.permission.READ_MEDIA_IMAGES);

```

**Comment by gmbad** [comment]
@dpa99c Hi Dave!

Should I use cordova.plugins.diagnostic.permission.READ_MEDIA_IMAGES for both Android < 13 and Android >= 13 ?

Or do I have to check the Android version and if it is < 13, do I continue using cordova.plugins.diagnostic.isExternalStorageAuthorized?

Thank you very much!

Gabriel
