### ISSUE TITLE
Selective Permissions

### ISSUE THREAD

**Issue by jgillard** [dpa99c/cordova-diagnostic-plugin#5]
Is it possible to cherry-pick the different "uses-permissions" for Android? Would like to keep them to a minimum as I'm only using one. Looking through the source and I'm wondering whether this will break the plugin.

**Comment by dpa99c** [comment]
You could fork the git repo and knock out any permissions you don't require in your branched version of the plugin. So long as you don't call plugin methods relating to permissions you've removed, it should be fine. However, if it does cause an issue you can always edit the [Android source code](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/src/android/Diagnostic.java) and remove the offending imports.

**Comment by jgillard** [comment]
That's great! Thanks for your time
