### ISSUE TITLE
Android Permission for Notification asking in Runtime in Android 13

### ISSUE THREAD

**Issue by HASNAI123** [dpa99c/cordova-diagnostic-plugin#506]
Previous version of the Plugin had ability to allow Permission for Notification inside the app but now the only fuction is to go to settings for Android, unable to just turn on with a prompt

**Comment by dpa99c** [comment]
Appears to work fine when tested with an [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) and the latest version of the plugin.

<img width="300" src="https://github.com/dpa99c/cordova-diagnostic-plugin/assets/2345062/daf32ed6-7d03-4f9a-8c0f-8d88521aff2a"/>
