### ISSUE TITLE
cordova diagnostic plugin requestExternalStorageAuthorization is returning DENIES_ALWAYS

### ISSUE THREAD

**Issue by Mahesh-Zeham** [dpa99c/cordova-diagnostic-plugin#507]
# Bug report

**CHECKLIST**
- [*] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-diagnostic-plugin#reporting-issues)

- [*] I confirm this is a suspected bug or issue that will affect other users

- [*] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) or provided the necessary information to reproduce the issue.

- [*] I have read [the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**
It should request the external storage permission.
For example, If i want to access my photo library/file. It should request the permission.

**Steps to reproduce:**

Create a sample cordova app.
Install the cordova-diagnostic-plugin [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin).
Then try to check and request the externalstorage access using the below code as mentioned in the plugin document.

**cordova.plugins.diagnostic.requestExternalStorageAuthorization(function(status){
    console.log("Authorization request for external storage use was " + (status == cordova.plugins.diagnostic.permissionStatus.GRANTED ? "granted" : "denied"));
}, function(error){
    console.error(error);
});**

   ***Here im always getting the status as "DENIED_ALWAYS"***

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
**12.0.0 (cordova-lib@12.0.1)**
- Cordova platform version
	 **android 12.0.1**
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
    **cordova.plugins.diagnostic 7.1.3 "Diagnostic"**
        
_Runtime issue_
- Device details
    **- _e.g. Oneplus 9R, Redmi 9_**
- OS details
    - _e.g. Android 13, 12, Android 9.0_	
	
_Android build issue:_	
- Node JS version **v16.20.1**
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Android SDK version
**"MIN_SDK_VERSION":24,"SDK_VERSION":33,"COMPILE_SDK_VERSION":null,"GRADLE_VERSION":"7.6","MIN_BUILD_TOOLS_VERSION":"33.0.2"**

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>requestExternalStorageAuthorization always returning as DENIED_ALWAYS</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Comment by dpa99c** [comment]
External storage permission is removed in Android 13, so if building with API 33+, you must use the new `MEDIA` permissions instead - [see here](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/499#issuecomment-1740886559)
