### ISSUE TITLE
Requesting Camera or Location Authorization no Popup

### ISSUE THREAD

**Issue by ECaslake** [dpa99c/cordova-diagnostic-plugin#55]
I am using Cordova 5.1.1 against Android Marshmallow.  Once Cordova has initialized I am checking for Camera access like so:
```
	cordova.plugins.diagnostic.getCameraAuthorizationStatus(
		function (access) {
			$constants.HasCameraAccess = access;
		},
		function (error) {
			alert("Camera Authorization Error: " + error);
		}
	);
```

Then when the user attempts to scan a barcode with the application I am checking my HasCameraAccess variable and if it is set to "NOT_REQUESTED" then I am attempting to prompt for access like so:
```
			cordova.plugins.diagnostic.requestCameraAuthorization(
				function (access) {
					$constants.HasCameraAccess = access;
				},
				function (error) {
					alert("Camera Authorization Error: " + error);
				}
			);
```
The issue that I am having is that the pop up to ask the user for permission is never showing, and a second attempt at requestCameraAuthorization is always returning "DENIED_ALWAYS".

Any ideas as to what I'm doing wrong?

Thanks,
Eric

**Comment by dpa99c** [comment]
Have you added the relevant permissions to AndroidManifest.xml? See the documentation on [Android permissions](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions) for details.

**Comment by ECaslake** [comment]
Yes, I had the necessary permissions in the Android Manifest.  The issue was that the Barcode Scanner plugin required CAMERA permission not READ_EXTERNAL_STORAGE.  So I had to specifically request CAMERA permission.

Thank you for taking the time to answer my question.  This is a great plugin.
