### ISSUE TITLE
Always returning permission granted even if disabled

### ISSUE THREAD

**Issue by vivekpd15** [dpa99c/cordova-diagnostic-plugin#56]
On Android Marshmallow, The plugin is returning "Granted" even when I go to settings and disable that specific permission. In my case, I got a "Granted" on camera runtime permission check even when I had disabled it through settings. Android is unable to open camera post that though since the permission is in reality disabled.

**Comment by dpa99c** [comment]
If the plugin is built with API 23 and its supporting libraries, then it will work as documented (i.e. return "DENIED" if permission is revoked) - see [this screencapture video](http://ge.tt/2cIxf0a2) which illustrates this using the [example project app](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) in the Android 6 emulator.

I would suggest building and running the example project in your build environment to confirm you can reproduce the results in the screen capture.

If this works OK, check your implementation when using the plugin.

If not, check the versions of Android Support Library and Repository installed via SDK Manager.

**Comment by trenkwaldermartin** [comment]
I had the same problem. You have to update the android version in your cordova project:

cordova platform update android@5.0.0

**Comment by vivekpd15** [comment]
Problem resolved. Figured that I forgot to set the target android API to 23.
