### ISSUE TITLE
[FEATURE] "App wants to change GPS settings" Confirmation

### ISSUE THREAD

**Issue by roblav96** [dpa99c/cordova-diagnostic-plugin#57]
In google maps, when you have the app open and GPS disabled, it asks you if you would like to enable it and does so within the application without having to go to settings.

Would this be possible to implement by any chance?

**Comment by dpa99c** [comment]
This functionality is implemented in a separate plugin: [cordova-plugin-request-location-accuracy](https://github.com/dpa99c/cordova-plugin-request-location-accuracy)

It's not included as part of this plugin as the functionality depends on the Google Play Services library, which increases the APK size by about 2Mb.

**Comment by roblav96** [comment]
@dpa99c Awesome! thanks man. great thinking on the separate plugin!
