### ISSUE TITLE
unsure about access to the file system on android

### ISSUE THREAD

**Issue by Pushplaybang** [dpa99c/cordova-diagnostic-plugin#60]
Hey There

How would you go about adding permissions in an android app for access to the gallery and media on the device?

**Comment by dpa99c** [comment]
You need to request `READ_EXTERNAL_STORAGE` permission, e.g.

    cordova.plugins.diagnostic.requestRuntimePermission(function(status){
        switch(status){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.NOT_REQUESTED:
                console.log("Permission has not been requested yet");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied - ask again?");
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied");
                break;
        }
    }, function(error){
        console.error("The following error occurred: "+error);
    }, cordova.plugins.diagnostic.runtimePermission.READ_EXTERNAL_STORAGE);


Don't forget to also add the permission to your AndroidManifest.xml - [see here](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions)

**Comment by Pushplaybang** [comment]
thanks!

**Comment by Pushplaybang** [comment]
@dpa99c  - I'm not having much luck here, It requests permissions, but the app crashes out everytime it returns from gallery, I've added it to the manifest using an empty cordova plugin.  These permissions are working in older versions of Android.

Not getting any useful error messages so not sure that this is related to this plugin or if its a separate issue.

**Comment by dpa99c** [comment]
@Pushplaybang When you say "the app crashes out", do you mean that the app restarts when returning from the gallery?

If so, I suspect what you are encountering is a side-effect of the Cordova app lifecycle on Android - [see here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#lifecycle-guide): when you switch to the gallery activity, your Cordova app activity is backgrounded. At this point, the Android OS may choose to kill off your app activity, particularly if resources are low. Android 5 is much more aggressive at this than earlier Android versions and Android 6 is even more aggressive.

The effect of this is that when you return from the gallery, your app is restarted from scratch. The Cordova documentation (linked above) goes into detail and outlines how to handle this scenario from your app's perspective.

**Comment by Pushplaybang** [comment]
Thanks thats really useful, and exactly whats happening, its fine on 5, but on 6  - no dice, will look into the link
