### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Ionian316** [dpa99c/cordova-diagnostic-plugin#61]
I think this issue is similar to #54. This is only happening in the iOS 8.1 and 9.3 simulators (haven't tested on other iOS simulators). I believe it's also not working on the physical devices themselves as it's not working as intended). It works on Android however.

When this line is called
`    cordova.plugins.diagnostic.isLocationEnabled(function (enabled) {`
I see this error in the log:
```
    Apr 29 16:56:28 MacBook-Pro.local Mobile[3817]: Error in Success callbackId: Diagnostic957019734 : TypeError: undefined is not a function (evaluating '$cordovaDevice.getPlatForm()')
    Apr 29 16:56:30 MacBook-Pro.local Mobile[3817]: Location is disabled.
    Apr 29 16:56:30 MacBook-Pro.local Mobile[3817]: Error in Success callbackId: Diagnostic957019735 : TypeError: undefined is not a function (evaluating '$cordovaDevice.getPlatForm()')
```

I'm not calling `$cordovaDevice.getPlatForm()` anywhere, although I do have **cordova-plugin-device 1.1.2** installed.

Any ideas as to why I'm getting this error? Thanks.

**Comment by dpa99c** [comment]
This plugin contains no reference to `$cordovaDevice.getPlatForm()` in its source code, either in the [iOS JS implementation of `isLocationEnabled`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/www/ios/diagnostic.js#L40), or anywhere else - you can confirm this by searching the plugin source.

I would suggest searching your app source code and other plugins for this function call. I also suggest building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for this plugin as validation of the plugin implementation, since it calls `isLocationEnabled()` and is working as expected when tested both in iOS simulators and on devices.

**Comment by GordonDeveloper** [comment]
200 /socket.io/?EIO=3&transport=polling&t=LIZIjkK&sid=_G9CcjYWBNUSWOhyAAAB
undefined TypeError: Cannot read property 'diagnostic' of undefined
    at new 200.


The error I get on Phonegap when testing on an android phone.
using cordova6.1.1

My config.xml :

<+1: ?xml version='1.0' encoding='utf-8'?>
<widget id="com.prosperityhealt.Rescue24" version="0.0.1"
	xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
	<name>Rescue24</name>
	<description>
		A registration and control program for Emed24.
	</description>
	<author email="gordon.berrington@hitasp.com" href="http://www.prosperityhealth.com">
		Prosperity Connect Team
	</author>
	<content src="index.html" />


	<access origin="*" />
	<allow-navigation href="*" />
	<allow-intent href="*" />

	<preference name="webviewbounce" value="false" />
	<preference name="UIWebViewBounce" value="false" />
	<preference name="DisallowOverscroll" value="true" />
	<preference name="android-minSdkVersion" value="16" />
	<preference name="BackupWebStorage" value="none" />
	<preference name="orientation" value="portrait" />
    <plugin name="cordova-plugin-console" spec="1.0.1" source="pgb" />
    <plugin name="cordova-plugin-device" spec="1.0.1" source="pgb" />
    <plugin name="cordova-plugin-splashscreen" spec="2.1.0" source="pgb" />
    <plugin name="cordova.plugins.diagnostic" version="*" />
    <plugin name="cordova-plugin-geolocation" spec="1.0.1" source="pgb" />
    <plugin name="org.apache.cordova.camera" spec="0.3.6" source="pgb" />


    <plugin name="com.indigoway.cordova.whitelist.whitelistplugin"
        version="1.1.1" />
	<feature name="StatusBar">
		<param name="ios-package" value="CDVStatusBar" onload="true" />
	</feature>

and my index.html:
<!DOCTYPE html>


<html ng-app="mainApp">
    <head>

        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="yes">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.min.js"></script>
        <script  src="cordova.js"></script>



        <script src="js/mainApp.js"></script>
        
        <script src="js/controllers/loginService.js"></script>
        <script src="js/controllers/registerService.js"></script>
        <script src="js/controllers/userLogService.js"></script>
        <script src="js/controllers/cameraService.js"></script>
        <script src="js/controllers/storageService.js"></script>
        <script src="js/controllers/emedService.js"></script>
        <script src="js/controllers/passwordService.js"></script>

        <script src="js/controllers/updateService.js"></script>


        

        <script src="js/controllers/loginController.js"></script>
        <script src="js/controllers/profileController.js"></script>
        <script src="js/controllers/registerController.js"></script>
        <script  src="cordova.js"></script>
        <meta charset="utf-8">



        <title>Rescue24</title>
    </head>
    <body >

    <div >

        <div ng-view></div>

        <script type = "text/ng-template" id = "addStudent.htm">
            <h2></h2>
            {{message}}
        </script>

        <script type = "text/ng-template" id = "viewStudents.htm">
            <h2></h2>
            {{message}}
        </script>
        <script type = "text/ng-template" id = "profStudents.htm">
            <h2></h2>
            {{message}}
        </script>
    </div>




    </body>
</html>

my Controller where the call is made: 
mainApp
		.controller(
				'loginController',
				function($scope, storage, $location, loginService) {
					// $location.path('/login')
					$scope.version = {
						number : 'Version 1.1.6'
					};

					$scope.credentials = {
						username : "",
						password : "",
					};
					$scope.register = {};
					$scope.register.haveRegistered = false;
					$scope.register.haveRegistered = storage.get(
							"registrationRequested", false);
                    cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
                        if(!enabled){
                        var infor = ("Your Location settings is off, please switch them on.");
                                                    navigator.notification.alert(infor);
                                                    function alertDismissed() {
                                                                                                        // do something
                                                  cordova.plugins.diagnostic.switchToLocationSettings();


                                                                                                    }

                        };
                    }, function(error){
                        console.error("The following error occurred: "+error);
                    });
.. it displays the error on top when it runs. I do have the cordova.plugins.diagnostic plugin installed.
I just cant get it to work?
Any ideas?

**Comment by dpa99c** [comment]
@GordonDeveloper this is not the same issue as described by @Ionian316, so I have created it as a new issue: #68

**Comment by Ionian316** [comment]
Before I was calling it in the controller, but once I moved it to the `$ionicPlatform.ready()` function, I don't see the error anymore.
