### ISSUE TITLE
requestCameraAuthorization not found ts+ionic2

### ISSUE THREAD

**Issue by ewiggin** [dpa99c/cordova-diagnostic-plugin#64]
Hello,
after installed this plugin i can't request auth to acces camera. Typescript showme error abount function not found, and when i deep into library... not exists! :-0

![seleccion_013](https://cloud.githubusercontent.com/assets/657517/15013344/54ce8e6e-11ff-11e6-9692-3a377b1baf57.png)

**Comment by dpa99c** [comment]
As [stated in the documentation](https://github.com/dpa99c/cordova-diagnostic-plugin#usage), the plugin API is exposed via the `cordova.plugins.diagnostic` global namespace, not `Diagnostic`. Hence, you should be calling `cordova.plugins.diagnostic.requestCameraAuthorization` not `Diagnostic.requestCameraAuthorization`.
