### ISSUE TITLE
[FEATURE] [iOS] Diagnose "Health Updates"

### ISSUE THREAD

**Issue by roblav96** [dpa99c/cordova-diagnostic-plugin#65]
Would it be possible to incorporate iOS "Health Updates" into this plugin? My app uses it to gather `CMMotionActivity` updates.

**Comment by dpa99c** [comment]
I'm working on a major update of this plugin (v3), which will add functionality to check/request permissions for other major functional groups on iOS. Included in this will be the ability to check/request access to Motion via the CoreMotion Framework, and Health via the HealthKit Framework.

However, this plugin is intended as a high-level diagnostic utility, so adding a Framework-specific option such as receiving motion updates is beyond its scope.

**Comment by roblav96** [comment]
This plugin does perfectly what I need it to do. And that's too check for permissions. Absolutely required for any Cordova app. Bravo all around!

**Comment by dpa99c** [comment]
Cool, glad to hear it's useful :) Hopefully v3 should be finished in the next few weeks and that will add a lot of useful functionality.

**Comment by dpa99c** [comment]
As mentioned in #38, adding generic support for iOS HealthKit is far from trivial, hence for now at least, I won't be adding support for this.

**Comment by dpa99c** [comment]
Closed as out of scope
