### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Pushplaybang** [dpa99c/cordova-diagnostic-plugin#66]
Hi There

are there any inherent security risks in using this plugin, that I should be aware of?  I suspect not, from my understanding of it, but it was a concern raised in my team.   Would really appreciate any insight you can provide.  Thanks.

**Comment by dpa99c** [comment]
This plugin is basically a wrapper for the native OS and Core Library APIs that native apps have access to out-of-the-box. As such, it implements very little functionality itself, but rather just provides an interface for Cordova apps to use these APIs which native apps get "for free". So in terms of security, the plugin is basically as secure as those APIs which Apple /Google /Microsoft provide. Which is to say, it's pretty secure :)

**Comment by Pushplaybang** [comment]
Thank you very much @dpa99c I greatly appreciate the feedback.

PS:  I've written about my success using your plugin with meteor recently, here : 
https://medium.com/@pushplaybang/handling-android-marshmallow-run-time-permissions-in-hybrid-mobile-apps-1974c68cc9fb#.kl1jb4v7q

**Comment by dpa99c** [comment]
@Pushplaybang Thanks for the appreciation :) I will close this now as hopefully your question is answered.
