### ISSUE TITLE
Bluetooth and location change handlers/listeners for Android

### ISSUE THREAD

**Issue by JaimeFerBec** [dpa99c/cordova-diagnostic-plugin#67]
I can see that there is a `registerBluetoothStateChangeHandler()` that registers a handler function that will be called whenever the bluetooth state changes, but this functionality is iOS only. Is there a way to do the same thing in Android?
The same question goes for location in both iOS and Android, because `registerLocationAuthorizationStatusChangeHandler()` only listens to changes in location authorization state, not to whether the location service is on or off.

**Comment by dpa99c** [comment]
I'm currently working on a major release of this plugin (v3), which should address these issues and introduce functionality to register state change handlers where possible.

However, currently `registerBluetoothStateChangeHandler()` is implemented only for iOS. For Android, you will need to call [`isBluetoothEnabled()`](https://github.com/dpa99c/cordova-diagnostic-plugin#isbluetoothenabled) to check current state.

There's also currently not a way to register for notification of a change in location service/mode - you will need to call [`isLocationEnabled()`](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationenabled).

In most scenarios, the user must background the app to change these modes, so re-checking state when the onResume event is fired is one way to be notified of the change.

`registerLocationAuthorizationStatusChangeHandler()` is only called on iOS in response to calling [`requestLocationAuthorization()`](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization), hence it is now deprecated in favour of passing the result to the success callback of `requestLocationAuthorization()`.

**Comment by dpa99c** [comment]
v3.0.0 implements [registerBluetoothStateChangeHandler()](https://github.com/dpa99c/cordova-diagnostic-plugin#registerbluetoothstatechangehandler) and [registerLocationStateChangeHandler()](https://github.com/dpa99c/cordova-diagnostic-plugin#registerlocationstatechangehandler) for both Android and iOS
