### ISSUE TITLE
undefined TypeError: Cannot read property 'diagnostic' of undefined

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-diagnostic-plugin#68]
@GordonDeveloper

200 /socket.io/?EIO=3&transport=polling&t=LIZIjkK&sid=_G9CcjYWBNUSWOhyAAAB
undefined TypeError: Cannot read property 'diagnostic' of undefined
    at new 200.

The error I get on Phonegap when testing on an android phone.
using cordova6.1.1

My config.xml :

    <+1: ?xml version='1.0' encoding='utf-8'?>
    <widget id="com.prosperityhealt.Rescue24" version="0.0.1"
    xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Rescue24</name>
    <description>
        A registration and control program for Emed24.
    </description>
    <author email="gordon.berrington@hitasp.com" href="http://www.prosperityhealth.com">
        Prosperity Connect Team
    </author>
    <content src="index.html" />

    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="*" />

    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="orientation" value="portrait" />
    <plugin name="cordova-plugin-console" spec="1.0.1" source="pgb" />
    <plugin name="cordova-plugin-device" spec="1.0.1" source="pgb" />
    <plugin name="cordova-plugin-splashscreen" spec="2.1.0" source="pgb" />
    <plugin name="cordova.plugins.diagnostic" version="*" />
    <plugin name="cordova-plugin-geolocation" spec="1.0.1" source="pgb" />
    <plugin name="org.apache.cordova.camera" spec="0.3.6" source="pgb" />

    <plugin name="com.indigoway.cordova.whitelist.whitelistplugin"
        version="1.1.1" />
    <feature name="StatusBar">
        <param name="ios-package" value="CDVStatusBar" onload="true" />
    </feature>

and my index.html:
    <!DOCTYPE html>

    <html ng-app="mainApp">
        <head>

            <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
            <meta name="format-detection" content="telephone=no">
            <meta name="msapplication-tap-highlight" content="yes">
            <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height">
            <link rel="stylesheet" type="text/css" href="css/index.css">
            <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
            <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.min.js"></script>
            <script  src="cordova.js"></script>

            <script src="js/mainApp.js"></script>
            
            <script src="js/controllers/loginService.js"></script>
            <script src="js/controllers/registerService.js"></script>
            <script src="js/controllers/userLogService.js"></script>
            <script src="js/controllers/cameraService.js"></script>
            <script src="js/controllers/storageService.js"></script>
            <script src="js/controllers/emedService.js"></script>
            <script src="js/controllers/passwordService.js"></script>

            <script src="js/controllers/updateService.js"></script>

            

            <script src="js/controllers/loginController.js"></script>
            <script src="js/controllers/profileController.js"></script>
            <script src="js/controllers/registerController.js"></script>
            <script  src="cordova.js"></script>
            <meta charset="utf-8">

            <title>Rescue24</title>
        </head>
        <body >

        <div >

            <div ng-view></div>

            <script type = "text/ng-template" id = "addStudent.htm">
                <h2></h2>
                {{message}}
            </script>

            <script type = "text/ng-template" id = "viewStudents.htm">
                <h2></h2>
                {{message}}
            </script>
            <script type = "text/ng-template" id = "profStudents.htm">
                <h2></h2>
                {{message}}
            </script>
        </div>

        </body>
    </html>

my Controller where the call is made: 
    
    mainApp
        .controller(
                'loginController',
                function($scope, storage, $location, loginService) {
                    // $location.path('/login')
                    $scope.version = {
                        number : 'Version 1.1.6'
                    };

                    $scope.credentials = {
                        username : "",
                        password : "",
                    };
                    $scope.register = {};
                    $scope.register.haveRegistered = false;
                    $scope.register.haveRegistered = storage.get(
                            "registrationRequested", false);
                    cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
                        if(!enabled){
                        var infor = ("Your Location settings is off, please switch them on.");
                                                    navigator.notification.alert(infor);
                                                    function alertDismissed() {
                                                                                                        // do something
                                                  cordova.plugins.diagnostic.switchToLocationSettings();

                                                                                                    }

                        };
                    }, function(error){
                        console.error("The following error occurred: "+error);
                    });
                    
.. it displays the error on top when it runs. I do have the cordova.plugins.diagnostic plugin installed.
I just cant get it to work?
Any ideas?

**Comment by dpa99c** [comment]
@GordonDeveloper without seeing the full project source code, it's hard to know the exact cause. But please check that the function in `mainApp.controller` is being called only after the Cordova `deviceready` event has fired. Cordova now dynamically loads plugin modules, so calling a plugin before the `deviceready` event has fired would result in the plugin being undefined.

You can also connect a remote debugger via Chrome dev tools and place a breakpoint on the call to the plugin. At this point, you can check if the `diagnostic.js` source file has been loaded into the page.

You may also want to try building and running the [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) for reference.

**Comment by GordonDeveloper** [comment]
@dpa99, I moved the location settings into one of the functions that fires after the program is ready, and it stil just hangs on the same place. I have started a new app and rebuild it, still same error. seems the diagnostic.js is not been loaded. how can I fix that?
.

**Comment by dpa99c** [comment]
@GordonDeveloper The [example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) illustrates use of all the functionality that this plugin supports, including `isLocationEnabled`. The app includes the cordova camera and geolocation plugins simply to validate that these services are actually available to the app.

Try building and running this very simply test project: [test_project.zip](https://github.com/dpa99c/cordova-diagnostic-plugin/files/261295/test_project.zip)

Here is the result of it running in my android 4.4.2 emulator:
![2016-05-12_133724](https://cloud.githubusercontent.com/assets/2345062/15214756/d3542bca-1846-11e6-992e-d6faf3f71049.jpg)

It makes just one call to `cordova.plugins.diagnostic.isLocationEnabled` and illustrates that the plugin works fine.

**Comment by GordonDeveloper** [comment]
200 /__api__/appzip
200 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=LIc2GJZ
200 /socket.io/?EIO=3&transport=polling&t=LIc2GL3&sid=dcy5pXjXOQVn5I00AAAB
200 /socket.io/?EIO=3&transport=polling&t=LIc2GN7&sid=dcy5pXjXOQVn5I00AAAB
undefined deviceready
undefined An exception occurred: Cannot read property 'diagnostic' of undefined
 
This is the display on phonegap

**Comment by dpa99c** [comment]
If that simple example doesn't work, then the problem is in your build environment - the plugin is not being installed/loaded properly into the app. 

Can you provide the following info:

Entire verbose output of the build process (can attach as text file).
Build environment: local or cloud service (e.g. Phonegap Build / Intel XDK)? 

If possible, can you zip up the entire simple project that you've built and attach it here as a ZIP?

**Comment by GordonDeveloper** [comment]
[RescueMed.zip](https://github.com/dpa99c/cordova-diagnostic-plugin/files/262062/RescueMed.zip)

theresthe zipped app. I have changed the app a bit to add the cordova in after looking for the navigator getlocation, if no rsult is returned, all info for you is in loginController.
Thanks.

**Comment by dpa99c** [comment]
Sorry, to be clear, I'd like you to build the simply test project: [test_project.zip](https://github.com/dpa99c/cordova-diagnostic-plugin/files/261295/test_project.zip) and then attach the entire resulting project as a ZIP.

**Comment by GordonDeveloper** [comment]
Hi dpa99c.
The problem was that it has to be in an OnDeviceReady function to work, and only works in an build on the phone self. Thanks for your time
