### ISSUE TITLE
isCameraPresent() strange result

### ISSUE THREAD

**Issue by hadrien-toma** [dpa99c/cordova-diagnostic-plugin#70]
Hi, I implemented this amazing plugin in Ionic and tested it on my Nexus 6. All is working as expected exept the callback of the function _isCameraPresent()_ : a single **number** (instead of **boolean**) is passed as parameter, in my case this is **1**. May be **1** might be **true**?

Anyway, very good job done in this plugin, well done!

PS : Sorry for my last issue due to a bad log analysis.

**Comment by dpa99c** [comment]
Yes, looks like you are correct, I missed this one when enforcing booleans.
