### ISSUE TITLE
[FEATURE] Memory/CPU Usage and Profiler

### ISSUE THREAD

**Issue by roblav96** [dpa99c/cordova-diagnostic-plugin#71]
While developing my cordova applications, I'm always very conscious of my memory usage.

In Android, I use:
```
performance.memory
```
but it would be nice to have the same on iOS.

Is this an easy to implement kinda thing?

Thank you!

**Comment by dpa99c** [comment]
Not sure how easy it would be to implement, but I think it's outside the scope of this plugin which is specifically focussed on managing devices settings and permissions. It would probably be best done in an iOS-only standalone plugin.

**Comment by roblav96** [comment]
Yes that's true, good point. Thanks!
