### ISSUE TITLE
[FEATURE] Device IP Information

### ISSUE THREAD

**Issue by gjkr** [dpa99c/cordova-diagnostic-plugin#84]
Would it possible to include IP formation of the device. E.g. IP address and router IP, SSID and Wifi name.
Inspiration can be found her:
- https://github.com/vallieres/cordova-plugin-get-router-ip-address
- https://github.com/salbahra/cordova-plugin-networkinterface
  Cordova App also runs on Desktop PC. So LAN IP information would also be nice to have.
  Otherwise excellent plugin

**Comment by deliverymanager** [comment]
+1 for this feature
