### ISSUE TITLE
[android 6] isLocationEnabled()

### ISSUE THREAD

**Issue by gurumelo** [dpa99c/cordova-diagnostic-plugin#86]
Hello. thanks for the plugin.

When i use isLocationEnabled in android 6 for see if device GPS is on or off. In case that is on getcurrentposition (cordova-plugin-geolocation) doesn't shows alert with allow permissions to location. Code. If i comment isLocationEnabled. getcurrentposition alerts about allow location permission in android 6. Can i use diagnostic plugin in android 6 for know that only device GPS is on or off?

```

function relocalizar() {
	cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
		if (estado == 0) {
			if (enabled) {
				//console.log('habilitado');
				// Estado 1 por si hay un resume que no vuelva a.
				estado = 1;
				lalocalizacion();
			} else {
                                //Not requesting permissions always enter here
				//console.log('deshabilitado');
				myApp.alert('Actívelo para situarle', 'GPS', function () {
					cordova.plugins.diagnostic.switchToLocationSettings();
				});
			}
		}
	}, function(error){
		console.error("GPS error: "+error);
	});
}

function lalocalizacion() {
	var options = { maximumAge: 1, enableHighAccuracy: true };
	navigator.geolocation.getCurrentPosition(obtenida, noobtenida, options);
        
}
```

**Comment by dpa99c** [comment]
On Android, `isLocationEnabled()` returns true if Location Mode is enabled and any mode is selected (e.g. Battery saving, Device only, High accuracy) **and** (on Android 6.0 / API 23) if use of location has runtime authorisation. `isLocationEnabled()` enforces that runtime permission for location is granted before returning `true` because, without being granted runtime permission to use location, it is irrelevant whether the device setting for GPS is ON or OFF, since the app can't access location data anyway.

So in your code, if `enabled == true`, this means that both Location Mode is switched ON **and** (on Android 6.0) that the app already has permission to use location, and therefore calling `navigator.geolocation.getCurrentPosition()` will not show the permission request dialog because your app already has location permission. 

You can explicitly check if the app has permission to use location by calling [isLocationAuthorized()](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationauthorized), so to check if Location Mode is enabled, you can do something like this:

    function onError(error){
        console.error("The following error occurred: "+error);
    }

    function checkLocationIsEnabled(){
        cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
            if (enabled) {
                console.log("Location Mode is enabled and location is available");
            } else {
                console.log("Location Mode is disabled so location is unavailable");
            }
        }, onError);
    }

    cordova.plugins.diagnostic.isLocationAuthorized(function(authorized){
        if(authorized){
            console.log("Location authorised for use");
            checkLocationIsEnabled();
        }else{
            console.log("Location not authorised for use");
            cordova.plugins.diagnostic.requestLocationAuthorization(function(status){        
                if(status == cordova.plugins.diagnostic.permissionStatus.GRANTED){
                    console.log("Permission granted");
                    checkLocationIsEnabled();
                }else{
                    console.warn("Permission denied");
                }
            }, onError);
        }
    }, onError);

**Comment by gurumelo** [comment]
Thank you

```
function permisos(){
	
	window.plugins.insomnia.keepAwake();
	
    cordova.plugins.diagnostic.requestRuntimePermission(function(status){
        switch(status){
            case cordova.plugins.diagnostic.runtimePermissionStatus.GRANTED:
                console.log("Permission granted (or already granted) - call the plugin");
                relocalizar();
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED:
                console.log("Permission denied - ask again");
                permisos();
                break;
            case cordova.plugins.diagnostic.runtimePermissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied");
				myApp.alert('Salimos. Denegó permiso de localización', 'Localización', function () {
					navigator.app.exitApp();
				});
                navigator.app.exitApp();
                break;
        }
    }, function(error){
        console.error("The following error occurred: "+error);
    }, cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION);
}







function relocalizar() {
	cordova.plugins.diagnostic.isLocationEnabled(function(enabled){
		if (estado == 0) {
			if (enabled) {
				//console.log('habilitado');
				// Estado 1 por si hay un resume que no vuelva a.
				estado = 1;
				lalocalizacion();
			} else {
				//console.log('deshabilitado');
				myApp.alert('Actívelo para situarle', 'GPS', function () {
					cordova.plugins.diagnostic.switchToLocationSettings();
				});
			}
		}
	}, function(error){
		console.error("GPS error: "+error);
	});
}

function lalocalizacion() {
	console.log('dentro de');
	var options = { maximumAge: 1, enableHighAccuracy: true };
	navigator.geolocation.getCurrentPosition(obtenida, noobtenida, options);
}
```

**Comment by dpa99c** [comment]
No problem
