### ISSUE TITLE
Problem in installation?

### ISSUE THREAD

**Issue by jayeshjain24** [dpa99c/cordova-diagnostic-plugin#87]
When I run ```ionic build android``` ,I get this error ```No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'``` . 
So I updated the android library from api22 to api23 and added the below lines to config.xml .
```
<preference name="android-minSdkVersion" value="16"/>
<preference name="android-targetSdkVersion" value="23"/>
```

Then I went to ```/platforms/android/project.properties``` and updated the target=android-23

After this the build was succesful but app crashed after installation. 

Any help? Am I missing something?

cordova -v : 5.3.3
ionic -v : 1.7.7

**Comment by dpa99c** [comment]
Check what version of `cordova-android` platform is installed: `cordova platform ls`.

The version must be 5 or greater, so if not: `cordova platform rm android && cordova platform add android@5`

**Comment by jayeshjain24** [comment]
Thankyou. That worked. closing the issue
