### ISSUE TITLE
Permission Popup doesn't come up

### ISSUE THREAD

**Issue by arvindr21** [dpa99c/cordova-diagnostic-plugin#89]
Hello,

Thanks for the plugin. I have gone through the docs as well as the example application. And I tried integrating the plugin into my existing app. 

I am using a [Wifi plugin](https://github.com/parsonsmatt/WifiWizard) to read Wifis around. This plugin has not been migrated to API 23. So I am using the diagnostic plugin to request permissions and then invoke the Wifi plugin. 

The Wifi plugin needs `android.permission.ACCESS_FINE_LOCATION` and `android.permission.ACCESS_COARSE_LOCATION` permissions. So I am trying to trigger it as shown below

```js
cordova.plugins.diagnostic.getPermissionsAuthorizationStatus(function(statuses){
    for (var permission in statuses){
        switch(statuses[permission]){
            case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                console.log("Permission granted to use "+permission);
                break;
            case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                console.log("Permission to use "+permission+" has not been requested yet");
                break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED:
                console.log("Permission denied to use "+permission+" - ask again?");
                break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                break;
        }
    }
}, function(error){
    console.error("The following error occurred: "+error);
},[
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION
]);
```

And my `config.xml` is set as below

```xml
<!-- snipp -->

<platform name="android">
        <preference name="android-minSdkVersion" value="16" />
        <preference name="android-targetSdkVersion" value="23" />
        <allow-intent href="market:*" />
        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
            <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
        </config-file>

<!-- snipp -->
```

When I launch the app, the permission popup never shows up and when I check the `logcat` using `adb logcat CordovaLog:D` I see the following

```
// snipp
06-23 18:25:55.017 27352 27352 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 27352
06-23 18:25:55.049 27352 27563 V Diagnostic: Get authorisation status for android.permission.ACCESS_FINE_LOCATION
06-23 18:25:55.050 27352 27563 V Diagnostic: Get authorisation status for android.permission.ACCESS_COARSE_LOCATION
06-23 18:25:55.092 27352 27352 I chromium: [INFO:CONSOLE(86)] "Permission permanently denied to use ACCESS_FINE_LOCATION - guess we won't be using it then!", source: file:///android_asset/www/js/controllers.js (86)
06-23 18:25:55.092 27352 27352 I chromium: [INFO:CONSOLE(86)] "Permission permanently denied to use ACCESS_COARSE_LOCATION - guess we won't be using it then!", source: file:///android_asset/www/js/controllers.js (86)
06-23 18:25:55.094   913  3813 E WifiService: Permission denial: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
// snipp
```

I deployed the example app as is on the same device and it works. I have taken the same code and added it to one of the pages in my app and it does not.

Any help is highly appreciated.

Thanks,
Arvind.

**Comment by dpa99c** [comment]
The log message would indicate the `<uses-permission/>` elements are not present in AndroidManifest.xml. You can confirm this by inspecting `platforms/android/AndroidManifest.xml`.

As well as including the `<config-file target="AndroidManifest.xml" parent="/*">` block in you config.xml, have you also added the [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) plugin to your project? 
Because ([as documented](https://github.com/dpa99c/cordova-diagnostic-plugin#android-permissions)) Cordova itself does not process `<config-file/>` blocks in config.xml, so this additional plugin is needed to do so.

**Comment by arvindr21** [comment]
Wow!! What a catch. I uninstalled  cordova-custom-config plugin last night to check something and forgot to add it back! Wasted my complete day!! Appreciate the support. Thanks Again!
