### ISSUE TITLE
requestLocationAuthorization requestCameraAuthorization requestContactsAuthorization: Permissions GRANTED but available after application restart (Android 6.0))

### ISSUE THREAD

**Issue by bognick** [dpa99c/cordova-diagnostic-plugin#92]
I'm using the functions requestLocationAuthorization requestCameraAuthorization requestContactsAuthorization. On Android 6.0 and in the first run of the application the pop up shows exactly as expected but after I hit ALLOW nothing happens. When I restart my application, the pop up never shows but the permissions are already GRANTED and the application performs smoothly. On Android 5.0 everything is fine.

```
	cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
		switch(status){
			case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
				console.log("Location permission not requested");
				break;
			case cordova.plugins.diagnostic.permissionStatus.GRANTED:
				get_location();
				console.log("Location permission granted");
				break;
			case cordova.plugins.diagnostic.permissionStatus.DENIED:
				console.log("Location permission denied");
				break;
			case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
				console.log("Location permission permanently denied");
				break;
		}
	}, function(error){
		console.error(error);
	});
		
	cordova.plugins.diagnostic.requestCameraAuthorization(function(status){
		console.log("Authorization request for camera use was " + (status == cordova.plugins.diagnostic.permissionStatus.GRANTED ? "granted" : "denied"));
		get_camera();
	}, function(error){
		console.error(error);
	});

	cordova.plugins.diagnostic.requestContactsAuthorization(function(status){
		if(status === cordova.plugins.diagnostic.permissionStatus.GRANTED){
			console.log("Contacts use is authorized");
			get_login();
		}
	}, function(error){
		console.error(error);
	});	
```

I tried to use the function requestRuntimePermissions with even less success:

```
cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses){
    for (var permission in statuses){
        switch(statuses[permission]){
            case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                console.log("Permission granted to use "+permission);
                break;
            case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                console.log("Permission to use "+permission+" has not been requested yet");
                break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED:
                console.log("Permission denied to use "+permission+" - ask again?");
                break;
            case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                break;
        }
    }
}, function(error){
    console.error("The following error occurred: "+error);
},[
    cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION,
    cordova.plugins.diagnostic.runtimePermission.RECORD_VIDEO,
    cordova.plugins.diagnostic.runtimePermission.CAMERA,
    cordova.plugins.diagnostic.runtimePermission.GET_ACCOUNTS,
    cordova.plugins.diagnostic.runtimePermission.USE_CREDENTIALS,
    cordova.plugins.diagnostic.runtimePermission.VIBRATE
]);
get_location();
get_camera();
get_login();
```

**Comment by dpa99c** [comment]
>the first run of the application the pop up shows exactly as expected but after I hit ALLOW nothing happens

What are you expecting to happen? 

Once the user presses the "Allow" button, the permission is granted by the Android 6 runtime permissions API. If you inspect the console output, you should see the log message with the outcome of the permission request (whether user pressed "Allow" or "Deny").

I'm guessing here (without seeing what `get_location()`, `get_camera()` and `get_login()` functions do), but if those functions rely on authorisation being granted, then that's your problem: in your second code example (using `requestRuntimePermissions()`), these functions are invoked synchronously after the call to `requestRuntimePermissions()`, so do not await the asynchronous outcome of the permissions dialog result which is passed to the success funtion of `requestRuntimePermissions()`. If this is the case, then you'd need to do something like this:

    cordova.plugins.diagnostic.requestRuntimePermissions(function(statuses){
        for (var permission in statuses){
            switch(statuses[permission]){
                case cordova.plugins.diagnostic.permissionStatus.GRANTED:
                    console.log("Permission granted to use "+permission);
    
                    get_location();
                    get_camera();
                    get_login();
    
                    break;
                case cordova.plugins.diagnostic.permissionStatus.NOT_REQUESTED:
                    console.log("Permission to use "+permission+" has not been requested yet");
                    break;
                case cordova.plugins.diagnostic.permissionStatus.DENIED:
                    console.log("Permission denied to use "+permission+" - ask again?");
                    break;
                case cordova.plugins.diagnostic.permissionStatus.DENIED_ALWAYS:
                    console.log("Permission permanently denied to use "+permission+" - guess we won't be using it then!");
                    break;
            }
        }
    }, function(error){
        console.error("The following error occurred: "+error);
    },[
        cordova.plugins.diagnostic.runtimePermission.ACCESS_FINE_LOCATION,
        cordova.plugins.diagnostic.runtimePermission.ACCESS_COARSE_LOCATION,
        cordova.plugins.diagnostic.runtimePermission.RECORD_VIDEO,
        cordova.plugins.diagnostic.runtimePermission.CAMERA,
        cordova.plugins.diagnostic.runtimePermission.GET_ACCOUNTS,
        cordova.plugins.diagnostic.runtimePermission.USE_CREDENTIALS,
        cordova.plugins.diagnostic.runtimePermission.VIBRATE
    ]);


I also suggest looking at/building the [runtime permissions example project](https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example) which illustrates/validates use of the plugin API.

**Comment by bognick** [comment]
Thanks for the quick response.

Regarding the requestLocationAuthorization function for example I expect the permissions not only being granted but also the location data to be available right after. This is not the case, as I need to restart my application in order for the location data to be actually available.

Regarding the requestRuntimePermissions I have already tried what you suggested, but the problem is that no pop up is displayed so my functions never get to be executed.

I will check your example projects in more detail. Thanks.

**Comment by dpa99c** [comment]
If you build and run the [general example project](https://github.com/dpa99c/cordova-diagnostic-plugin-example) on Android 6, you can observe that after pressing the "Request Location Authorization" button and allowing location permission, you can then press the "Get Current Location" button and location is immediately accessible to the app and should be displayed in a popup dialog.

**Comment by bognick** [comment]
I solved my issue by requesting first for camera and if GRANTED then I request for location.
