### ISSUE TITLE
[FEATURE] [ANDROID] Implement switchToPermissionSettings() Method

### ISSUE THREAD

**Issue by roblav96** [dpa99c/cordova-diagnostic-plugin#93]
Would this be possible?

### switchToPermissionSettings()
Displays permission settings to allow user to enable or disable individual app permissions.
```javascript
cordova.plugins.diagnostic.switchToPermissionSettings();
```

**Comment by dpa99c** [comment]
This is not possible on Android 6 - see here: [http://stackoverflow.com/questions/32822101/how-to-programmatically-open-the-permission-screen-for-a-specific-app-on-android](http://stackoverflow.com/questions/32822101/how-to-programmatically-open-the-permission-screen-for-a-specific-app-on-android)

**Comment by roblav96** [comment]
Ah, OK! thanks
