### ISSUE TITLE
[iOS] Background App Refresh

### ISSUE THREAD

**Issue by roblav96** [dpa99c/cordova-diagnostic-plugin#95]
Possible to add this one? 😄 
[Background App Refresh Example](http://i.imgur.com/S1Ozy0U.jpg)

I'm using [cordova-plugin-background-fetch](https://github.com/christocracy/cordova-plugin-background-fetch) and I'd like to check if my users have disabled this setting. Thank you!!!

**Comment by dpa99c** [comment]
Seems [this stackoverflow answer](http://stackoverflow.com/a/19138393/777265) may provide the solution, so assuming it still works for iOS 9, it should be possible to expose the functionality via this plugin.

**Comment by roblav96** [comment]
Thanks man! I'm gonna try my first native iOS pull request and try to implement this 😀
